name: boost_studio
services:
  boost_studio_backend:
    image: booststudio:latest
    build:
      context: .
      dockerfile: src/Core/Presentation/WebApi/Dockerfile
    container_name: "boost_studio"
    user: "root"
    ports:
      - "9420:8080"
    environment:
      - ConnectionStrings__DefaultConnection=DataSource=/home/app/.local/share/db/app.db;Cache=Shared
    volumes:
      - ./.deploy:/home/app/.local/share/db