
//----------------------
// <auto-generated>
//     This is a generated file! Please edit source .ksy file and use kaitai-struct-compiler to rebuild
// </auto-generated>
//----------------------
using Kaitai;
using System.Collections.Generic;

namespace BoostStudio.Formats
{
    public partial class ProjectileBinaryFormat : KaitaiStruct
    {
        public static ProjectileBinaryFormat FromFile(string fileName)
        {
            return new ProjectileBinaryFormat(new KaitaiStream(fileName));
        }

        public ProjectileBinaryFormat(KaitaiStream p__io, KaitaiStruct p__parent = null, ProjectileBinaryFormat p__root = null, bool write = false) : base(p__io)
        {
            m_parent = p__parent;
            m_root = p__root ?? this;
            f_propertyCount = write;
            f_projectile = write;
            if (!write)
                _read();
        }
        private void _read()
        {
            _fileMagic = m_io.ReadU4be();
            _unk4 = m_io.ReadU4be();
            _unitId = m_io.ReadU4be();
            _dataPointer = m_io.ReadU4be();
            _projectileCount = m_io.ReadU4be();
        }
        public partial class ProjectileBody : KaitaiStruct
        {
            public ProjectileBody(int p_index, KaitaiStream p__io, ProjectileBinaryFormat p__parent = null, ProjectileBinaryFormat p__root = null, bool write = false) : base(p__io)
            {
                m_parent = p__parent;
                m_root = p__root;
                _index = p_index;
                f_offset = write;
                f_projectileProperties = write;
                if (!write)
                    _read();
            }
            private void _read()
            {
                _hash = m_io.ReadU4be();
            }
            private bool f_offset;
            private int _offset;
            public int Offset
            {
                get
                {
                    if (f_offset)
                        return _offset;
                    _offset = (int)((((M_Parent.ProjectileCount * 4) + ((Index * M_Parent.PropertyCount) * 4)) + 20));
                    f_offset = true;
                    return _offset;
                }

                set
                {
                    _offset = value;
                }
            }
            private bool f_projectileProperties;
            private ProjectilePropertiesBody _projectileProperties;
            public ProjectilePropertiesBody ProjectileProperties
            {
                get
                {
                    if (f_projectileProperties)
                        return _projectileProperties;
                    long _pos = m_io.Pos;
                    m_io.Seek(Offset);
                    _projectileProperties = new ProjectilePropertiesBody(m_io, this, m_root);
                    m_io.Seek(_pos);
                    f_projectileProperties = true;
                    return _projectileProperties;
                }

                set
                {
                    _projectileProperties = value;
                }
            }
            private uint _hash;
            private int _index;
            private ProjectileBinaryFormat m_root;
            private ProjectileBinaryFormat m_parent;
            public uint Hash
            {
                get { return _hash; }

                set
                {
                    _hash = value;
                }
            }
            public int Index
            {
                get { return _index; }

                set
                {
                    _index = value;
                }
            }
            public ProjectileBinaryFormat M_Root
            {
                get { return m_root; }

                set
                {
                    m_root = value;
                }
            }
            public ProjectileBinaryFormat M_Parent
            {
                get { return m_parent; }

                set
                {
                    m_parent = value;
                }
            }
        }
        public partial class ProjectilePropertiesBody : KaitaiStruct
        {
            public static ProjectilePropertiesBody FromFile(string fileName)
            {
                return new ProjectilePropertiesBody(new KaitaiStream(fileName));
            }

            public ProjectilePropertiesBody(KaitaiStream p__io, ProjectileBinaryFormat.ProjectileBody p__parent = null, ProjectileBinaryFormat p__root = null, bool write = false) : base(p__io)
            {
                m_parent = p__parent;
                m_root = p__root;
                if (!write)
                    _read();
            }
            private void _read()
            {
                _projectileType = m_io.ReadU4be();
                _hitboxHash = m_io.ReadU4be();
                _modelHash = m_io.ReadU4be();
                _skeletonIndex = m_io.ReadU4be();
                _aimType = m_io.ReadU4be();
                _translateY = m_io.ReadU4be();
                _translateZ = m_io.ReadU4be();
                _translateX = m_io.ReadU4be();
                _rotateX = m_io.ReadU4be();
                _rotateZ = m_io.ReadU4be();
                _cosmeticHash = m_io.ReadU4be();
                _unk44 = m_io.ReadU4be();
                _unk48 = m_io.ReadU4be();
                _unk52 = m_io.ReadU4be();
                _unk56 = m_io.ReadU4be();
                _ammoConsumption = m_io.ReadU4be();
                _durationFrame = m_io.ReadU4be();
                _maxTravelDistance = m_io.ReadF4be();
                _initialSpeed = m_io.ReadF4be();
                _acceleration = m_io.ReadF4be();
                _accelerationStartFrame = m_io.ReadU4be();
                _unk84 = m_io.ReadU4be();
                _maxSpeed = m_io.ReadF4be();
                _reserved92 = m_io.ReadF4be();
                _reserved96 = m_io.ReadF4be();
                _reserved100 = m_io.ReadF4be();
                _reserved104 = m_io.ReadF4be();
                _reserved108 = m_io.ReadF4be();
                _reserved112 = m_io.ReadF4be();
                _reserved116 = m_io.ReadU4be();
                _horizontalGuidance = m_io.ReadF4be();
                _horizontalGuidanceAngle = m_io.ReadF4be();
                _verticalGuidance = m_io.ReadF4be();
                _verticalGuidanceAngle = m_io.ReadF4be();
                _reserved136 = m_io.ReadU4be();
                _reserved140 = m_io.ReadU4be();
                _reserved144 = m_io.ReadF4be();
                _reserved148 = m_io.ReadF4be();
                _reserved152 = m_io.ReadF4be();
                _reserved156 = m_io.ReadF4be();
                _reserved160 = m_io.ReadF4be();
                _reserved164 = m_io.ReadF4be();
                _reserved168 = m_io.ReadU4be();
                _reserved172 = m_io.ReadF4be();
                _size = m_io.ReadF4be();
                _reserved180 = m_io.ReadU4be();
                _reserved184 = m_io.ReadU4be();
                _soundEffectHash = m_io.ReadU4be();
                _reserved192 = m_io.ReadU4be();
                _reserved196 = m_io.ReadU4be();
                _chainedProjectileHash = m_io.ReadU4be();
                _reserved204 = m_io.ReadU4be();
                _reserved208 = m_io.ReadU4be();
                _reserved212 = m_io.ReadU4be();
                _reserved216 = m_io.ReadU4be();
                _reserved220 = m_io.ReadF4be();
                _reserved224 = m_io.ReadF4be();
                _reserved228 = m_io.ReadF4be();
                _reserved232 = m_io.ReadF4be();
                _reserved236 = m_io.ReadF4be();
                _reserved240 = m_io.ReadF4be();
                _reserved244 = m_io.ReadF4be();
                _reserved248 = m_io.ReadF4be();
                _reserved252 = m_io.ReadF4be();
                _reserved256 = m_io.ReadF4be();
                _reserved260 = m_io.ReadF4be();
                _reserved264 = m_io.ReadF4be();
                _reserved268 = m_io.ReadF4be();
                _reserved272 = m_io.ReadF4be();
                _reserved276 = m_io.ReadF4be();
            }
            private uint _projectileType;
            private uint _hitboxHash;
            private uint _modelHash;
            private uint _skeletonIndex;
            private uint _aimType;
            private uint _translateY;
            private uint _translateZ;
            private uint _translateX;
            private uint _rotateX;
            private uint _rotateZ;
            private uint _cosmeticHash;
            private uint _unk44;
            private uint _unk48;
            private uint _unk52;
            private uint _unk56;
            private uint _ammoConsumption;
            private uint _durationFrame;
            private float _maxTravelDistance;
            private float _initialSpeed;
            private float _acceleration;
            private uint _accelerationStartFrame;
            private uint _unk84;
            private float _maxSpeed;
            private float _reserved92;
            private float _reserved96;
            private float _reserved100;
            private float _reserved104;
            private float _reserved108;
            private float _reserved112;
            private uint _reserved116;
            private float _horizontalGuidance;
            private float _horizontalGuidanceAngle;
            private float _verticalGuidance;
            private float _verticalGuidanceAngle;
            private uint _reserved136;
            private uint _reserved140;
            private float _reserved144;
            private float _reserved148;
            private float _reserved152;
            private float _reserved156;
            private float _reserved160;
            private float _reserved164;
            private uint _reserved168;
            private float _reserved172;
            private float _size;
            private uint _reserved180;
            private uint _reserved184;
            private uint _soundEffectHash;
            private uint _reserved192;
            private uint _reserved196;
            private uint _chainedProjectileHash;
            private uint _reserved204;
            private uint _reserved208;
            private uint _reserved212;
            private uint _reserved216;
            private float _reserved220;
            private float _reserved224;
            private float _reserved228;
            private float _reserved232;
            private float _reserved236;
            private float _reserved240;
            private float _reserved244;
            private float _reserved248;
            private float _reserved252;
            private float _reserved256;
            private float _reserved260;
            private float _reserved264;
            private float _reserved268;
            private float _reserved272;
            private float _reserved276;
            private ProjectileBinaryFormat m_root;
            private ProjectileBinaryFormat.ProjectileBody m_parent;
            public uint ProjectileType
            {
                get { return _projectileType; }

                set
                {
                    _projectileType = value;
                }
            }
            public uint HitboxHash
            {
                get { return _hitboxHash; }

                set
                {
                    _hitboxHash = value;
                }
            }
            public uint ModelHash
            {
                get { return _modelHash; }

                set
                {
                    _modelHash = value;
                }
            }
            public uint SkeletonIndex
            {
                get { return _skeletonIndex; }

                set
                {
                    _skeletonIndex = value;
                }
            }
            public uint AimType
            {
                get { return _aimType; }

                set
                {
                    _aimType = value;
                }
            }
            public uint TranslateY
            {
                get { return _translateY; }

                set
                {
                    _translateY = value;
                }
            }
            public uint TranslateZ
            {
                get { return _translateZ; }

                set
                {
                    _translateZ = value;
                }
            }
            public uint TranslateX
            {
                get { return _translateX; }

                set
                {
                    _translateX = value;
                }
            }
            public uint RotateX
            {
                get { return _rotateX; }

                set
                {
                    _rotateX = value;
                }
            }
            public uint RotateZ
            {
                get { return _rotateZ; }

                set
                {
                    _rotateZ = value;
                }
            }
            public uint CosmeticHash
            {
                get { return _cosmeticHash; }

                set
                {
                    _cosmeticHash = value;
                }
            }
            public uint Unk44
            {
                get { return _unk44; }

                set
                {
                    _unk44 = value;
                }
            }
            public uint Unk48
            {
                get { return _unk48; }

                set
                {
                    _unk48 = value;
                }
            }
            public uint Unk52
            {
                get { return _unk52; }

                set
                {
                    _unk52 = value;
                }
            }
            public uint Unk56
            {
                get { return _unk56; }

                set
                {
                    _unk56 = value;
                }
            }
            public uint AmmoConsumption
            {
                get { return _ammoConsumption; }

                set
                {
                    _ammoConsumption = value;
                }
            }
            public uint DurationFrame
            {
                get { return _durationFrame; }

                set
                {
                    _durationFrame = value;
                }
            }
            public float MaxTravelDistance
            {
                get { return _maxTravelDistance; }

                set
                {
                    _maxTravelDistance = value;
                }
            }
            public float InitialSpeed
            {
                get { return _initialSpeed; }

                set
                {
                    _initialSpeed = value;
                }
            }
            public float Acceleration
            {
                get { return _acceleration; }

                set
                {
                    _acceleration = value;
                }
            }
            public uint AccelerationStartFrame
            {
                get { return _accelerationStartFrame; }

                set
                {
                    _accelerationStartFrame = value;
                }
            }
            public uint Unk84
            {
                get { return _unk84; }

                set
                {
                    _unk84 = value;
                }
            }
            public float MaxSpeed
            {
                get { return _maxSpeed; }

                set
                {
                    _maxSpeed = value;
                }
            }
            public float Reserved92
            {
                get { return _reserved92; }

                set
                {
                    _reserved92 = value;
                }
            }
            public float Reserved96
            {
                get { return _reserved96; }

                set
                {
                    _reserved96 = value;
                }
            }
            public float Reserved100
            {
                get { return _reserved100; }

                set
                {
                    _reserved100 = value;
                }
            }
            public float Reserved104
            {
                get { return _reserved104; }

                set
                {
                    _reserved104 = value;
                }
            }
            public float Reserved108
            {
                get { return _reserved108; }

                set
                {
                    _reserved108 = value;
                }
            }
            public float Reserved112
            {
                get { return _reserved112; }

                set
                {
                    _reserved112 = value;
                }
            }
            public uint Reserved116
            {
                get { return _reserved116; }

                set
                {
                    _reserved116 = value;
                }
            }
            public float HorizontalGuidance
            {
                get { return _horizontalGuidance; }

                set
                {
                    _horizontalGuidance = value;
                }
            }
            public float HorizontalGuidanceAngle
            {
                get { return _horizontalGuidanceAngle; }

                set
                {
                    _horizontalGuidanceAngle = value;
                }
            }
            public float VerticalGuidance
            {
                get { return _verticalGuidance; }

                set
                {
                    _verticalGuidance = value;
                }
            }
            public float VerticalGuidanceAngle
            {
                get { return _verticalGuidanceAngle; }

                set
                {
                    _verticalGuidanceAngle = value;
                }
            }
            public uint Reserved136
            {
                get { return _reserved136; }

                set
                {
                    _reserved136 = value;
                }
            }
            public uint Reserved140
            {
                get { return _reserved140; }

                set
                {
                    _reserved140 = value;
                }
            }
            public float Reserved144
            {
                get { return _reserved144; }

                set
                {
                    _reserved144 = value;
                }
            }
            public float Reserved148
            {
                get { return _reserved148; }

                set
                {
                    _reserved148 = value;
                }
            }
            public float Reserved152
            {
                get { return _reserved152; }

                set
                {
                    _reserved152 = value;
                }
            }
            public float Reserved156
            {
                get { return _reserved156; }

                set
                {
                    _reserved156 = value;
                }
            }
            public float Reserved160
            {
                get { return _reserved160; }

                set
                {
                    _reserved160 = value;
                }
            }
            public float Reserved164
            {
                get { return _reserved164; }

                set
                {
                    _reserved164 = value;
                }
            }
            public uint Reserved168
            {
                get { return _reserved168; }

                set
                {
                    _reserved168 = value;
                }
            }
            public float Reserved172
            {
                get { return _reserved172; }

                set
                {
                    _reserved172 = value;
                }
            }
            public float Size
            {
                get { return _size; }

                set
                {
                    _size = value;
                }
            }
            public uint Reserved180
            {
                get { return _reserved180; }

                set
                {
                    _reserved180 = value;
                }
            }
            public uint Reserved184
            {
                get { return _reserved184; }

                set
                {
                    _reserved184 = value;
                }
            }
            public uint SoundEffectHash
            {
                get { return _soundEffectHash; }

                set
                {
                    _soundEffectHash = value;
                }
            }
            public uint Reserved192
            {
                get { return _reserved192; }

                set
                {
                    _reserved192 = value;
                }
            }
            public uint Reserved196
            {
                get { return _reserved196; }

                set
                {
                    _reserved196 = value;
                }
            }
            public uint ChainedProjectileHash
            {
                get { return _chainedProjectileHash; }

                set
                {
                    _chainedProjectileHash = value;
                }
            }
            public uint Reserved204
            {
                get { return _reserved204; }

                set
                {
                    _reserved204 = value;
                }
            }
            public uint Reserved208
            {
                get { return _reserved208; }

                set
                {
                    _reserved208 = value;
                }
            }
            public uint Reserved212
            {
                get { return _reserved212; }

                set
                {
                    _reserved212 = value;
                }
            }
            public uint Reserved216
            {
                get { return _reserved216; }

                set
                {
                    _reserved216 = value;
                }
            }
            public float Reserved220
            {
                get { return _reserved220; }

                set
                {
                    _reserved220 = value;
                }
            }
            public float Reserved224
            {
                get { return _reserved224; }

                set
                {
                    _reserved224 = value;
                }
            }
            public float Reserved228
            {
                get { return _reserved228; }

                set
                {
                    _reserved228 = value;
                }
            }
            public float Reserved232
            {
                get { return _reserved232; }

                set
                {
                    _reserved232 = value;
                }
            }
            public float Reserved236
            {
                get { return _reserved236; }

                set
                {
                    _reserved236 = value;
                }
            }
            public float Reserved240
            {
                get { return _reserved240; }

                set
                {
                    _reserved240 = value;
                }
            }
            public float Reserved244
            {
                get { return _reserved244; }

                set
                {
                    _reserved244 = value;
                }
            }
            public float Reserved248
            {
                get { return _reserved248; }

                set
                {
                    _reserved248 = value;
                }
            }
            public float Reserved252
            {
                get { return _reserved252; }

                set
                {
                    _reserved252 = value;
                }
            }
            public float Reserved256
            {
                get { return _reserved256; }

                set
                {
                    _reserved256 = value;
                }
            }
            public float Reserved260
            {
                get { return _reserved260; }

                set
                {
                    _reserved260 = value;
                }
            }
            public float Reserved264
            {
                get { return _reserved264; }

                set
                {
                    _reserved264 = value;
                }
            }
            public float Reserved268
            {
                get { return _reserved268; }

                set
                {
                    _reserved268 = value;
                }
            }
            public float Reserved272
            {
                get { return _reserved272; }

                set
                {
                    _reserved272 = value;
                }
            }
            public float Reserved276
            {
                get { return _reserved276; }

                set
                {
                    _reserved276 = value;
                }
            }
            public ProjectileBinaryFormat M_Root
            {
                get { return m_root; }

                set
                {
                    m_root = value;
                }
            }
            public ProjectileBinaryFormat.ProjectileBody M_Parent
            {
                get { return m_parent; }

                set
                {
                    m_parent = value;
                }
            }
        }
        private bool f_propertyCount;
        private sbyte _propertyCount;
        public sbyte PropertyCount
        {
            get
            {
                if (f_propertyCount)
                    return _propertyCount;
                _propertyCount = (sbyte)(70);
                f_propertyCount = true;
                return _propertyCount;
            }

            set
            {
                _propertyCount = value;
            }
        }
        private bool f_projectile;
        private List<ProjectileBody> _projectile;
        public List<ProjectileBody> Projectile
        {
            get
            {
                if (f_projectile)
                    return _projectile;
                _projectile = new List<ProjectileBody>();
                for (var i = 0; i < ProjectileCount; i++)
                {
                    _projectile.Add(new ProjectileBody(i, m_io, this, m_root));
                }
                f_projectile = true;
                return _projectile;
            }

            set
            {
                _projectile = value;
            }
        }
        private uint _fileMagic;
        private uint _unk4;
        private uint _unitId;
        private uint _dataPointer;
        private uint _projectileCount;
        private ProjectileBinaryFormat m_root;
        private KaitaiStruct m_parent;
        public uint FileMagic
        {
            get { return _fileMagic; }

            set
            {
                _fileMagic = value;
            }
        }
        public uint Unk4
        {
            get { return _unk4; }

            set
            {
                _unk4 = value;
            }
        }
        public uint UnitId
        {
            get { return _unitId; }

            set
            {
                _unitId = value;
            }
        }
        public uint DataPointer
        {
            get { return _dataPointer; }

            set
            {
                _dataPointer = value;
            }
        }
        public uint ProjectileCount
        {
            get { return _projectileCount; }

            set
            {
                _projectileCount = value;
            }
        }
        public ProjectileBinaryFormat M_Root
        {
            get { return m_root; }

            set
            {
                m_root = value;
            }
        }
        public KaitaiStruct M_Parent
        {
            get { return m_parent; }

            set
            {
                m_parent = value;
            }
        }
    }
}
