namespace BoostStudio.Application.Exvs.UnitStats.Commands.Models;

public class StatDto
{
    public int UnitCost { get; set; }
    public int UnitCost2 { get; set; }
    public int MaxHp { get; set; }
    public int DownValueThreshold { get; set; }
    public int YorukeValueThreshold { get; set; }
    public int Unk20 { get; set; }
    public int Unk24 { get; set; }
    public int Unk28 { get; set; }
    public int MaxBoost { get; set; }
    public float Unk36 { get; set; }
    public float Unk40 { get; set; }
    public int Unk44 { get; set; }
    public float GravityMultiplierAir { get; set; }
    public float GravityMultiplierLand { get; set; }
    public float Unk56 { get; set; }
    public float Unk60 { get; set; }
    public float Unk64 { get; set; }
    public float Unk68 { get; set; }
    public float Unk72 { get; set; }
    public float Unk76 { get; set; }
    public float Unk80 { get; set; }
    public float CameraZoomMultiplier { get; set; }
    public float Unk88 { get; set; }
    public float Unk92 { get; set; }
    public float Unk96 { get; set; }
    public float Unk100 { get; set; }
    public float Unk104 { get; set; }
    public float Unk108 { get; set; }
    public float SizeMultiplier { get; set; }
    public float Unk116 { get; set; }
    public float Unk120 { get; set; }
    public float Unk124 { get; set; }
    public float Unk128 { get; set; }
    public float Unk132 { get; set; }
    public float Unk136 { get; set; }
    public float Unk140 { get; set; }
    public float Unk144 { get; set; }
    public float Unk148 { get; set; }
    public float Unk152 { get; set; }
    public float Unk156 { get; set; }
    public float Unk160 { get; set; }
    public float Unk164 { get; set; }
    public float Unk168 { get; set; }
    public float Unk172 { get; set; }
    public float Unk176 { get; set; }
    public float Unk180 { get; set; }
    public float Unk184 { get; set; }
    public float RedLockRangeMelee { get; set; }
    public float RedLockRange { get; set; }
    public float Unk196 { get; set; }
    public float Unk200 { get; set; }
    public int Unk204 { get; set; }
    public int Unk208 { get; set; }
    public int BoostReplenish { get; set; }
    public int Unk216 { get; set; }
    public int BoostInitialConsumption { get; set; }
    public int BoostFuwaInitialConsumption { get; set; }
    public int BoostFlyConsumption { get; set; }
    public int BoostGroundStepInitialConsumption { get; set; }
    public int BoostGroundStepConsumption { get; set; }
    public int BoostAirStepInitialConsumption { get; set; }
    public int BoostAirStepConsumption { get; set; }
    public int BoostBdInitialConsumption { get; set; }
    public int BoostBdConsumption { get; set; }
    public int Unk256 { get; set; }
    public int Unk260 { get; set; }
    public int Unk264 { get; set; }
    public int Unk268 { get; set; }
    public int BoostTransformInitialConsumption { get; set; }
    public int BoostTransformConsumption { get; set; }
    public int BoostNonVernierActionConsumption { get; set; }
    public int BoostPostActionConsumption { get; set; }
    public int BoostRainbowStepInitialConsumption { get; set; }
    public int Unk292 { get; set; }
    public int Unk296 { get; set; }
    public int Unk300 { get; set; }
    public int Unk304 { get; set; }
    public int Unk308 { get; set; }
    public int Unk312 { get; set; }
    public int Unk316 { get; set; }
    public int Unk320 { get; set; }
    public int Unk324 { get; set; }
    public int Unk328 { get; set; }
    public int Unk332 { get; set; }
    public float AssaultBurstRedLockMelee { get; set; }
    public float AssaultBurstRedLock { get; set; }
    public float AssaultBurstDamageDealtMultiplier { get; set; }
    public float AssaultBurstDamageTakenMultiplier { get; set; }
    public float AssaultBurstMobilityMultiplier { get; set; }
    public float AssaultBurstDownValueDealtMultiplier { get; set; }
    public float AssaultBurstBoostConsumptionMultiplier { get; set; }
    public int Unk364 { get; set; }
    public int Unk368 { get; set; }
    public float AssaultBurstDamageDealtBurstGaugeIncreaseMultiplier { get; set; }
    public float AssaultBurstDamageTakenBurstGaugeIncreaseMultiplier { get; set; }
    public int Unk380 { get; set; }
    public float Unk384 { get; set; }
    public float Unk388 { get; set; }
    public float Unk392 { get; set; }
    public float Unk396 { get; set; }
    public float BlastBurstRedLockMelee { get; set; }
    public float BlastBurstRedLock { get; set; }
    public float BlastBurstDamageDealtMultiplier { get; set; }
    public float BlastBurstDamageTakenMultiplier { get; set; }
    public float BlastBurstMobilityMultiplier { get; set; }
    public float BlastBurstDownValueDealtMultiplier { get; set; }
    public float BlastBurstBoostConsumptionMultiplier { get; set; }
    public int Unk428 { get; set; }
    public int Unk432 { get; set; }
    public float BlastBurstDamageDealtBurstGaugeIncreaseMultiplier { get; set; }
    public float BlastBurstDamageTakenBurstGaugeIncreaseMultiplier { get; set; }
    public int Unk444 { get; set; }
    public float Unk448 { get; set; }
    public float Unk452 { get; set; }
    public float Unk456 { get; set; }
    public float Unk460 { get; set; }
    public float ThirdBurstRedLockMelee { get; set; }
    public float ThirdBurstRedLock { get; set; }
    public float ThirdBurstDamageDealtMultiplier { get; set; }
    public float ThirdBurstDamageTakenMultiplier { get; set; }
    public float ThirdBurstMobilityMultiplier { get; set; }
    public float ThirdBurstDownValueDealtMultiplier { get; set; }
    public float ThirdBurstBoostConsumptionMultiplier { get; set; }
    public float Unk492 { get; set; }
    public int Unk496 { get; set; }
    public float ThirdBurstDamageDealtBurstGaugeIncreaseMultiplier { get; set; }
    public float ThirdBurstDamageTakenBurstGaugeIncreaseMultiplier { get; set; }
    public int Unk508 { get; set; }
    public float Unk512 { get; set; }
    public float Unk516 { get; set; }
    public float Unk520 { get; set; }
    public float Unk524 { get; set; }
    public float FourthBurstRedLockMelee { get; set; }
    public float FourthBurstRedLock { get; set; }
    public float FourthBurstDamageDealtMultiplier { get; set; }
    public float FourthBurstDamageTakenMultiplier { get; set; }
    public float FourthBurstMobilityMultiplier { get; set; }
    public float FourthBurstDownValueDealtMultiplier { get; set; }
    public float FourthBurstBoostConsumptionMultiplier { get; set; }
    public int Unk572 { get; set; }
    public int Unk576 { get; set; }
    public float FourthBurstDamageDealtBurstGaugeIncreaseMultiplier { get; set; }
    public float FourthBurstDamageTakenBurstGaugeIncreaseMultiplier { get; set; }
    public int Unk588 { get; set; }
    public float Unk592 { get; set; }
    public float Unk596 { get; set; }
    public float Unk600 { get; set; }
    public float Unk604 { get; set; }
    public int Unk608 { get; set; }
}
