/* tslint:disable */
/* eslint-disable */
/**
 * BoostStudio.Web | exvs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface AmmoDtoOrder
 */
export interface AmmoDtoOrder {
}

/**
 * Check if a given object implements the AmmoDtoOrder interface.
 */
export function instanceOfAmmoDtoOrder(value: object): value is AmmoDtoOrder {
    return true;
}

export function AmmoDtoOrderFromJSON(json: any): AmmoDtoOrder {
    return AmmoDtoOrderFromJSONTyped(json, false);
}

export function AmmoDtoOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): AmmoDtoOrder {
    return json;
}

export function AmmoDtoOrderToJSON(value?: AmmoDtoOrder | null): any {
    return value;
}

