/* tslint:disable */
/* eslint-disable */
/**
 * BoostStudio.Web | exvs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { GetApiAmmoHashParameterInner } from "./GetApiAmmoHashParameterInner";
import {
  GetApiAmmoHashParameterInnerFromJSON,
  GetApiAmmoHashParameterInnerToJSON
} from "./GetApiAmmoHashParameterInner";
import type { AmmoDtoOrder } from "./AmmoDtoOrder";
import { AmmoDtoOrderFromJSON, AmmoDtoOrderToJSON } from "./AmmoDtoOrder";

/**
 * 
 * @export
 * @interface CreateUnitAmmoSlotCommand
 */
export interface CreateUnitAmmoSlotCommand {
    /**
     * 
     * @type {GetApiAmmoHashParameterInner}
     * @memberof CreateUnitAmmoSlotCommand
     */
    ammoHash: GetApiAmmoHashParameterInner;
    /**
     * 
     * @type {GetApiAmmoHashParameterInner}
     * @memberof CreateUnitAmmoSlotCommand
     */
    unitId: GetApiAmmoHashParameterInner;
    /**
     * 
     * @type {AmmoDtoOrder}
     * @memberof CreateUnitAmmoSlotCommand
     */
    slotOrder: AmmoDtoOrder;
}

/**
 * Check if a given object implements the CreateUnitAmmoSlotCommand interface.
 */
export function instanceOfCreateUnitAmmoSlotCommand(value: object): value is CreateUnitAmmoSlotCommand {
    if (!('ammoHash' in value) || value['ammoHash'] === undefined) return false;
    if (!('unitId' in value) || value['unitId'] === undefined) return false;
    if (!('slotOrder' in value) || value['slotOrder'] === undefined) return false;
    return true;
}

export function CreateUnitAmmoSlotCommandFromJSON(json: any): CreateUnitAmmoSlotCommand {
    return CreateUnitAmmoSlotCommandFromJSONTyped(json, false);
}

export function CreateUnitAmmoSlotCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUnitAmmoSlotCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'ammoHash': GetApiAmmoHashParameterInnerFromJSON(json['ammoHash']),
        'unitId': GetApiAmmoHashParameterInnerFromJSON(json['unitId']),
        'slotOrder': AmmoDtoOrderFromJSON(json['slotOrder']),
    };
}

export function CreateUnitAmmoSlotCommandToJSON(value?: CreateUnitAmmoSlotCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ammoHash': GetApiAmmoHashParameterInnerToJSON(value['ammoHash']),
        'unitId': GetApiAmmoHashParameterInnerToJSON(value['unitId']),
        'slotOrder': AmmoDtoOrderToJSON(value['slotOrder']),
    };
}

