/* tslint:disable */
/* eslint-disable */
/**
 * BoostStudio.Web | exvs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { GetApiAmmoHashParameterInner } from "./GetApiAmmoHashParameterInner";
import {
  GetApiAmmoHashParameterInnerFromJSON,
  GetApiAmmoHashParameterInnerToJSON
} from "./GetApiAmmoHashParameterInner";

/**
 * 
 * @export
 * @interface ExportUnitStatByPathCommand
 */
export interface ExportUnitStatByPathCommand {
    /**
     * 
     * @type {Array<GetApiAmmoHashParameterInner>}
     * @memberof ExportUnitStatByPathCommand
     */
    unitIds?: Array<GetApiAmmoHashParameterInner>;
    /**
     * 
     * @type {string}
     * @memberof ExportUnitStatByPathCommand
     */
    exportPath?: string | null;
}

/**
 * Check if a given object implements the ExportUnitStatByPathCommand interface.
 */
export function instanceOfExportUnitStatByPathCommand(value: object): value is ExportUnitStatByPathCommand {
    return true;
}

export function ExportUnitStatByPathCommandFromJSON(json: any): ExportUnitStatByPathCommand {
    return ExportUnitStatByPathCommandFromJSONTyped(json, false);
}

export function ExportUnitStatByPathCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExportUnitStatByPathCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'unitIds': json['unitIds'] == null ? undefined : ((json['unitIds'] as Array<any>).map(GetApiAmmoHashParameterInnerFromJSON)),
        'exportPath': json['exportPath'] == null ? undefined : json['exportPath'],
    };
}

export function ExportUnitStatByPathCommandToJSON(value?: ExportUnitStatByPathCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'unitIds': value['unitIds'] == null ? undefined : ((value['unitIds'] as Array<any>).map(GetApiAmmoHashParameterInnerToJSON)),
        'exportPath': value['exportPath'],
    };
}

