/* tslint:disable */
/* eslint-disable */
/**
 * BoostStudio.Web | exvs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PatchFileVersion } from "./PatchFileVersion";
import { PatchFileVersionFromJSON, PatchFileVersionToJSON } from "./PatchFileVersion";

/**
 * 
 * @export
 * @interface ExportTblCommand
 */
export interface ExportTblCommand {
    /**
     * 
     * @type {Array<PatchFileVersion>}
     * @memberof ExportTblCommand
     */
    versions?: Array<PatchFileVersion>;
    /**
     * 
     * @type {boolean}
     * @memberof ExportTblCommand
     */
    replaceStaging?: boolean;
}

/**
 * Check if a given object implements the ExportTblCommand interface.
 */
export function instanceOfExportTblCommand(value: object): value is ExportTblCommand {
    return true;
}

export function ExportTblCommandFromJSON(json: any): ExportTblCommand {
    return ExportTblCommandFromJSONTyped(json, false);
}

export function ExportTblCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExportTblCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'versions': json['versions'] == null ? undefined : ((json['versions'] as Array<any>).map(PatchFileVersionFromJSON)),
        'replaceStaging': json['replaceStaging'] == null ? undefined : json['replaceStaging'],
    };
}

export function ExportTblCommandToJSON(value?: ExportTblCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'versions': value['versions'] == null ? undefined : ((value['versions'] as Array<any>).map(PatchFileVersionToJSON)),
        'replaceStaging': value['replaceStaging'],
    };
}

