/* tslint:disable */
/* eslint-disable */
/**
 * BoostStudio.Web | exvs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExportAmmoCommand
 */
export interface ExportAmmoCommand {
    /**
     * 
     * @type {boolean}
     * @memberof ExportAmmoCommand
     */
    replaceWorking?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ExportAmmoCommand
     */
    hotReload?: boolean;
}

/**
 * Check if a given object implements the ExportAmmoCommand interface.
 */
export function instanceOfExportAmmoCommand(value: object): value is ExportAmmoCommand {
    return true;
}

export function ExportAmmoCommandFromJSON(json: any): ExportAmmoCommand {
    return ExportAmmoCommandFromJSONTyped(json, false);
}

export function ExportAmmoCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExportAmmoCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'replaceWorking': json['replaceWorking'] == null ? undefined : json['replaceWorking'],
        'hotReload': json['hotReload'] == null ? undefined : json['hotReload'],
    };
}

export function ExportAmmoCommandToJSON(value?: ExportAmmoCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'replaceWorking': value['replaceWorking'],
        'hotReload': value['hotReload'],
    };
}

