/* tslint:disable */
/* eslint-disable */
/**
 * BoostStudio.Web | exvs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Null } from "./Null";
import { NullFromJSON, NullToJSON } from "./Null";

/**
 * 
 * @export
 * @interface FileContentResult
 */
export interface FileContentResult {
    /**
     * 
     * @type {string}
     * @memberof FileContentResult
     */
    fileContents?: string;
    /**
     * 
     * @type {string}
     * @memberof FileContentResult
     */
    contentType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FileContentResult
     */
    fileDownloadName?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof FileContentResult
     */
    lastModified?: Date | null;
    /**
     * 
     * @type {Null}
     * @memberof FileContentResult
     */
    entityTag?: Null;
    /**
     * 
     * @type {boolean}
     * @memberof FileContentResult
     */
    enableRangeProcessing?: boolean;
}

/**
 * Check if a given object implements the FileContentResult interface.
 */
export function instanceOfFileContentResult(value: object): value is FileContentResult {
    return true;
}

export function FileContentResultFromJSON(json: any): FileContentResult {
    return FileContentResultFromJSONTyped(json, false);
}

export function FileContentResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileContentResult {
    if (json == null) {
        return json;
    }
    return {
        
        'fileContents': json['fileContents'] == null ? undefined : json['fileContents'],
        'contentType': json['contentType'] == null ? undefined : json['contentType'],
        'fileDownloadName': json['fileDownloadName'] == null ? undefined : json['fileDownloadName'],
        'lastModified': json['lastModified'] == null ? undefined : (new Date(json['lastModified'])),
        'entityTag': json['entityTag'] == null ? undefined : NullFromJSON(json['entityTag']),
        'enableRangeProcessing': json['enableRangeProcessing'] == null ? undefined : json['enableRangeProcessing'],
    };
}

export function FileContentResultToJSON(value?: FileContentResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'fileContents': value['fileContents'],
        'contentType': value['contentType'],
        'fileDownloadName': value['fileDownloadName'],
        'lastModified': value['lastModified'] == null ? undefined : ((value['lastModified'] as any).toISOString()),
        'entityTag': NullToJSON(value['entityTag']),
        'enableRangeProcessing': value['enableRangeProcessing'],
    };
}

