/* tslint:disable */
/* eslint-disable */
/**
 * BoostStudio.Web | exvs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetApiConfigs200ResponseInner
 */
export interface GetApiConfigs200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof GetApiConfigs200ResponseInner
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof GetApiConfigs200ResponseInner
     */
    value: string;
}

/**
 * Check if a given object implements the GetApiConfigs200ResponseInner interface.
 */
export function instanceOfGetApiConfigs200ResponseInner(value: object): value is GetApiConfigs200ResponseInner {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function GetApiConfigs200ResponseInnerFromJSON(json: any): GetApiConfigs200ResponseInner {
    return GetApiConfigs200ResponseInnerFromJSONTyped(json, false);
}

export function GetApiConfigs200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetApiConfigs200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'value': json['value'],
    };
}

export function GetApiConfigs200ResponseInnerToJSON(value?: GetApiConfigs200ResponseInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'key': value['key'],
        'value': value['value'],
    };
}

