/* tslint:disable */
/* eslint-disable */
/**
 * BoostStudio.Web | exvs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetApiStats200ResponseItemsInner } from './GetApiStats200ResponseItemsInner';
import {
    GetApiStats200ResponseItemsInnerFromJSON,
    GetApiStats200ResponseItemsInnerFromJSONTyped,
    GetApiStats200ResponseItemsInnerToJSON,
} from './GetApiStats200ResponseItemsInner';

/**
 * 
 * @export
 * @interface GetApiStats200Response
 */
export interface GetApiStats200Response {
    /**
     * 
     * @type {Array<GetApiStats200ResponseItemsInner>}
     * @memberof GetApiStats200Response
     */
    items: Array<GetApiStats200ResponseItemsInner>;
    /**
     * 
     * @type {number}
     * @memberof GetApiStats200Response
     */
    pageNumber: number;
    /**
     * 
     * @type {number}
     * @memberof GetApiStats200Response
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof GetApiStats200Response
     */
    totalCount: number;
    /**
     * 
     * @type {boolean}
     * @memberof GetApiStats200Response
     */
    hasPreviousPage?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GetApiStats200Response
     */
    hasNextPage?: boolean;
}

/**
 * Check if a given object implements the GetApiStats200Response interface.
 */
export function instanceOfGetApiStats200Response(value: object): value is GetApiStats200Response {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pageNumber' in value) || value['pageNumber'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    return true;
}

export function GetApiStats200ResponseFromJSON(json: any): GetApiStats200Response {
    return GetApiStats200ResponseFromJSONTyped(json, false);
}

export function GetApiStats200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetApiStats200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(GetApiStats200ResponseItemsInnerFromJSON)),
        'pageNumber': json['pageNumber'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'totalCount': json['totalCount'],
        'hasPreviousPage': json['hasPreviousPage'] == null ? undefined : json['hasPreviousPage'],
        'hasNextPage': json['hasNextPage'] == null ? undefined : json['hasNextPage'],
    };
}

export function GetApiStats200ResponseToJSON(value?: GetApiStats200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(GetApiStats200ResponseItemsInnerToJSON)),
        'pageNumber': value['pageNumber'],
        'totalPages': value['totalPages'],
        'totalCount': value['totalCount'],
        'hasPreviousPage': value['hasPreviousPage'],
        'hasNextPage': value['hasNextPage'],
    };
}

