/* tslint:disable */
/* eslint-disable */
/**
 * BoostStudio.Web | exvs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const GetUnitSummaryQueryIncludes = {
    Series: 'Series'
} as const;
export type GetUnitSummaryQueryIncludes = typeof GetUnitSummaryQueryIncludes[keyof typeof GetUnitSummaryQueryIncludes];


export function instanceOfGetUnitSummaryQueryIncludes(value: any): boolean {
    for (const key in GetUnitSummaryQueryIncludes) {
        if (Object.prototype.hasOwnProperty.call(GetUnitSummaryQueryIncludes, key)) {
            if ((GetUnitSummaryQueryIncludes as Record<string, GetUnitSummaryQueryIncludes>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function GetUnitSummaryQueryIncludesFromJSON(json: any): GetUnitSummaryQueryIncludes {
    return GetUnitSummaryQueryIncludesFromJSONTyped(json, false);
}

export function GetUnitSummaryQueryIncludesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUnitSummaryQueryIncludes {
    return json as GetUnitSummaryQueryIncludes;
}

export function GetUnitSummaryQueryIncludesToJSON(value?: GetUnitSummaryQueryIncludes | null): any {
    return value as any;
}

