/* tslint:disable */
/* eslint-disable */
/**
 * BoostStudio.Web | exvs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface PackPsarcByPathCommandCompressionLevel
 */
export interface PackPsarcByPathCommandCompressionLevel {
}

/**
 * Check if a given object implements the PackPsarcByPathCommandCompressionLevel interface.
 */
export function instanceOfPackPsarcByPathCommandCompressionLevel(value: object): value is PackPsarcByPathCommandCompressionLevel {
    return true;
}

export function PackPsarcByPathCommandCompressionLevelFromJSON(json: any): PackPsarcByPathCommandCompressionLevel {
    return PackPsarcByPathCommandCompressionLevelFromJSONTyped(json, false);
}

export function PackPsarcByPathCommandCompressionLevelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PackPsarcByPathCommandCompressionLevel {
    return json;
}

export function PackPsarcByPathCommandCompressionLevelToJSON(value?: PackPsarcByPathCommandCompressionLevel | null): any {
    return value;
}

