/* tslint:disable */
/* eslint-disable */
/**
 * BoostStudio.Web | exvs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlayableSeriesDetailsDto } from './PlayableSeriesDetailsDto';
import {
    PlayableSeriesDetailsDtoFromJSON,
    PlayableSeriesDetailsDtoFromJSONTyped,
    PlayableSeriesDetailsDtoToJSON,
} from './PlayableSeriesDetailsDto';

/**
 * 
 * @export
 * @interface PaginatedListOfSeriesDtoItemsInner
 */
export interface PaginatedListOfSeriesDtoItemsInner {
    /**
     * 
     * @type {number}
     * @memberof PaginatedListOfSeriesDtoItemsInner
     */
    id?: number;
    /**
     * 
     * @type {PlayableSeriesDetailsDto}
     * @memberof PaginatedListOfSeriesDtoItemsInner
     */
    playableSeries?: PlayableSeriesDetailsDto | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedListOfSeriesDtoItemsInner
     */
    slugName?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginatedListOfSeriesDtoItemsInner
     */
    nameEnglish?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedListOfSeriesDtoItemsInner
     */
    nameJapanese?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedListOfSeriesDtoItemsInner
     */
    nameChinese?: string | null;
}

/**
 * Check if a given object implements the PaginatedListOfSeriesDtoItemsInner interface.
 */
export function instanceOfPaginatedListOfSeriesDtoItemsInner(value: object): value is PaginatedListOfSeriesDtoItemsInner {
    return true;
}

export function PaginatedListOfSeriesDtoItemsInnerFromJSON(json: any): PaginatedListOfSeriesDtoItemsInner {
    return PaginatedListOfSeriesDtoItemsInnerFromJSONTyped(json, false);
}

export function PaginatedListOfSeriesDtoItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedListOfSeriesDtoItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'playableSeries': json['playableSeries'] == null ? undefined : PlayableSeriesDetailsDtoFromJSON(json['playableSeries']),
        'slugName': json['slugName'] == null ? undefined : json['slugName'],
        'nameEnglish': json['nameEnglish'] == null ? undefined : json['nameEnglish'],
        'nameJapanese': json['nameJapanese'] == null ? undefined : json['nameJapanese'],
        'nameChinese': json['nameChinese'] == null ? undefined : json['nameChinese'],
    };
}

export function PaginatedListOfSeriesDtoItemsInnerToJSON(value?: PaginatedListOfSeriesDtoItemsInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'playableSeries': PlayableSeriesDetailsDtoToJSON(value['playableSeries']),
        'slugName': value['slugName'],
        'nameEnglish': value['nameEnglish'],
        'nameJapanese': value['nameJapanese'],
        'nameChinese': value['nameChinese'],
    };
}

