/* tslint:disable */
/* eslint-disable */
/**
 * BoostStudio.Web | exvs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { HitboxGroupDto } from "./HitboxGroupDto";
import { HitboxGroupDtoFromJSON, HitboxGroupDtoToJSON } from "./HitboxGroupDto";
import type { AmmoDtoOrder } from "./AmmoDtoOrder";
import { AmmoDtoOrderFromJSON, AmmoDtoOrderToJSON } from "./AmmoDtoOrder";

/**
 * 
 * @export
 * @interface PaginatedListOfHitboxGroupDto
 */
export interface PaginatedListOfHitboxGroupDto {
    /**
     * 
     * @type {Array<HitboxGroupDto>}
     * @memberof PaginatedListOfHitboxGroupDto
     */
    items: Array<HitboxGroupDto>;
    /**
     * 
     * @type {AmmoDtoOrder}
     * @memberof PaginatedListOfHitboxGroupDto
     */
    pageNumber: AmmoDtoOrder;
    /**
     * 
     * @type {AmmoDtoOrder}
     * @memberof PaginatedListOfHitboxGroupDto
     */
    totalPages?: AmmoDtoOrder;
    /**
     * 
     * @type {AmmoDtoOrder}
     * @memberof PaginatedListOfHitboxGroupDto
     */
    totalCount: AmmoDtoOrder;
    /**
     * 
     * @type {boolean}
     * @memberof PaginatedListOfHitboxGroupDto
     */
    hasPreviousPage?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PaginatedListOfHitboxGroupDto
     */
    hasNextPage?: boolean;
}

/**
 * Check if a given object implements the PaginatedListOfHitboxGroupDto interface.
 */
export function instanceOfPaginatedListOfHitboxGroupDto(value: object): value is PaginatedListOfHitboxGroupDto {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pageNumber' in value) || value['pageNumber'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    return true;
}

export function PaginatedListOfHitboxGroupDtoFromJSON(json: any): PaginatedListOfHitboxGroupDto {
    return PaginatedListOfHitboxGroupDtoFromJSONTyped(json, false);
}

export function PaginatedListOfHitboxGroupDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedListOfHitboxGroupDto {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(HitboxGroupDtoFromJSON)),
        'pageNumber': AmmoDtoOrderFromJSON(json['pageNumber']),
        'totalPages': json['totalPages'] == null ? undefined : AmmoDtoOrderFromJSON(json['totalPages']),
        'totalCount': AmmoDtoOrderFromJSON(json['totalCount']),
        'hasPreviousPage': json['hasPreviousPage'] == null ? undefined : json['hasPreviousPage'],
        'hasNextPage': json['hasNextPage'] == null ? undefined : json['hasNextPage'],
    };
}

export function PaginatedListOfHitboxGroupDtoToJSON(value?: PaginatedListOfHitboxGroupDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(HitboxGroupDtoToJSON)),
        'pageNumber': AmmoDtoOrderToJSON(value['pageNumber']),
        'totalPages': AmmoDtoOrderToJSON(value['totalPages']),
        'totalCount': AmmoDtoOrderToJSON(value['totalCount']),
        'hasPreviousPage': value['hasPreviousPage'],
        'hasNextPage': value['hasNextPage'],
    };
}

