/* tslint:disable */
/* eslint-disable */
/**
 * BoostStudio.Web | exvs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PatchFileVm } from './PatchFileVm';
import {
    PatchFileVmFromJSON,
    PatchFileVmFromJSONTyped,
    PatchFileVmToJSON,
} from './PatchFileVm';

/**
 * 
 * @export
 * @interface PaginatedListOfPatchFileVm
 */
export interface PaginatedListOfPatchFileVm {
    /**
     * 
     * @type {Array<PatchFileVm>}
     * @memberof PaginatedListOfPatchFileVm
     */
    items: Array<PatchFileVm>;
    /**
     * 
     * @type {number}
     * @memberof PaginatedListOfPatchFileVm
     */
    pageNumber: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedListOfPatchFileVm
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedListOfPatchFileVm
     */
    totalCount: number;
    /**
     * 
     * @type {boolean}
     * @memberof PaginatedListOfPatchFileVm
     */
    hasPreviousPage?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PaginatedListOfPatchFileVm
     */
    hasNextPage?: boolean;
}

/**
 * Check if a given object implements the PaginatedListOfPatchFileVm interface.
 */
export function instanceOfPaginatedListOfPatchFileVm(value: object): value is PaginatedListOfPatchFileVm {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pageNumber' in value) || value['pageNumber'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    return true;
}

export function PaginatedListOfPatchFileVmFromJSON(json: any): PaginatedListOfPatchFileVm {
    return PaginatedListOfPatchFileVmFromJSONTyped(json, false);
}

export function PaginatedListOfPatchFileVmFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedListOfPatchFileVm {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(PatchFileVmFromJSON)),
        'pageNumber': json['pageNumber'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'totalCount': json['totalCount'],
        'hasPreviousPage': json['hasPreviousPage'] == null ? undefined : json['hasPreviousPage'],
        'hasNextPage': json['hasNextPage'] == null ? undefined : json['hasNextPage'],
    };
}

export function PaginatedListOfPatchFileVmToJSON(value?: PaginatedListOfPatchFileVm | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(PatchFileVmToJSON)),
        'pageNumber': value['pageNumber'],
        'totalPages': value['totalPages'],
        'totalCount': value['totalCount'],
        'hasPreviousPage': value['hasPreviousPage'],
        'hasNextPage': value['hasNextPage'],
    };
}

