/* tslint:disable */
/* eslint-disable */
/**
 * BoostStudio.Web | exvs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectileDto } from './ProjectileDto';
import {
    ProjectileDtoFromJSON,
    ProjectileDtoFromJSONTyped,
    ProjectileDtoToJSON,
} from './ProjectileDto';

/**
 * 
 * @export
 * @interface PaginatedListOfProjectileDto
 */
export interface PaginatedListOfProjectileDto {
    /**
     * 
     * @type {Array<ProjectileDto>}
     * @memberof PaginatedListOfProjectileDto
     */
    items: Array<ProjectileDto>;
    /**
     * 
     * @type {number}
     * @memberof PaginatedListOfProjectileDto
     */
    pageNumber: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedListOfProjectileDto
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedListOfProjectileDto
     */
    totalCount: number;
    /**
     * 
     * @type {boolean}
     * @memberof PaginatedListOfProjectileDto
     */
    hasPreviousPage?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PaginatedListOfProjectileDto
     */
    hasNextPage?: boolean;
}

/**
 * Check if a given object implements the PaginatedListOfProjectileDto interface.
 */
export function instanceOfPaginatedListOfProjectileDto(value: object): value is PaginatedListOfProjectileDto {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pageNumber' in value) || value['pageNumber'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    return true;
}

export function PaginatedListOfProjectileDtoFromJSON(json: any): PaginatedListOfProjectileDto {
    return PaginatedListOfProjectileDtoFromJSONTyped(json, false);
}

export function PaginatedListOfProjectileDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedListOfProjectileDto {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ProjectileDtoFromJSON)),
        'pageNumber': json['pageNumber'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'totalCount': json['totalCount'],
        'hasPreviousPage': json['hasPreviousPage'] == null ? undefined : json['hasPreviousPage'],
        'hasNextPage': json['hasNextPage'] == null ? undefined : json['hasNextPage'],
    };
}

export function PaginatedListOfProjectileDtoToJSON(value?: PaginatedListOfProjectileDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(ProjectileDtoToJSON)),
        'pageNumber': value['pageNumber'],
        'totalPages': value['totalPages'],
        'totalCount': value['totalCount'],
        'hasPreviousPage': value['hasPreviousPage'],
        'hasNextPage': value['hasNextPage'],
    };
}

