/* tslint:disable */
/* eslint-disable */
/**
 * BoostStudio.Web | exvs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SeriesDto } from "./SeriesDto";
import { SeriesDtoFromJSON, SeriesDtoToJSON } from "./SeriesDto";
import type { AmmoDtoOrder } from "./AmmoDtoOrder";
import { AmmoDtoOrderFromJSON, AmmoDtoOrderToJSON } from "./AmmoDtoOrder";

/**
 * 
 * @export
 * @interface PaginatedListOfSeriesDto
 */
export interface PaginatedListOfSeriesDto {
    /**
     * 
     * @type {Array<SeriesDto>}
     * @memberof PaginatedListOfSeriesDto
     */
    items: Array<SeriesDto>;
    /**
     * 
     * @type {AmmoDtoOrder}
     * @memberof PaginatedListOfSeriesDto
     */
    pageNumber: AmmoDtoOrder;
    /**
     * 
     * @type {AmmoDtoOrder}
     * @memberof PaginatedListOfSeriesDto
     */
    totalPages?: AmmoDtoOrder;
    /**
     * 
     * @type {AmmoDtoOrder}
     * @memberof PaginatedListOfSeriesDto
     */
    totalCount: AmmoDtoOrder;
    /**
     * 
     * @type {boolean}
     * @memberof PaginatedListOfSeriesDto
     */
    hasPreviousPage?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PaginatedListOfSeriesDto
     */
    hasNextPage?: boolean;
}

/**
 * Check if a given object implements the PaginatedListOfSeriesDto interface.
 */
export function instanceOfPaginatedListOfSeriesDto(value: object): value is PaginatedListOfSeriesDto {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pageNumber' in value) || value['pageNumber'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    return true;
}

export function PaginatedListOfSeriesDtoFromJSON(json: any): PaginatedListOfSeriesDto {
    return PaginatedListOfSeriesDtoFromJSONTyped(json, false);
}

export function PaginatedListOfSeriesDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedListOfSeriesDto {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(SeriesDtoFromJSON)),
        'pageNumber': AmmoDtoOrderFromJSON(json['pageNumber']),
        'totalPages': json['totalPages'] == null ? undefined : AmmoDtoOrderFromJSON(json['totalPages']),
        'totalCount': AmmoDtoOrderFromJSON(json['totalCount']),
        'hasPreviousPage': json['hasPreviousPage'] == null ? undefined : json['hasPreviousPage'],
        'hasNextPage': json['hasNextPage'] == null ? undefined : json['hasNextPage'],
    };
}

export function PaginatedListOfSeriesDtoToJSON(value?: PaginatedListOfSeriesDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(SeriesDtoToJSON)),
        'pageNumber': AmmoDtoOrderToJSON(value['pageNumber']),
        'totalPages': AmmoDtoOrderToJSON(value['totalPages']),
        'totalCount': AmmoDtoOrderToJSON(value['totalCount']),
        'hasPreviousPage': value['hasPreviousPage'],
        'hasNextPage': value['hasNextPage'],
    };
}

