/* tslint:disable */
/* eslint-disable */
/**
 * BoostStudio.Web | exvs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostApiUnitStatsExportRequest
 */
export interface PostApiUnitStatsExportRequest {
    /**
     * 
     * @type {Array<number>}
     * @memberof PostApiUnitStatsExportRequest
     */
    unitIds?: Array<number> | null;
}

/**
 * Check if a given object implements the PostApiUnitStatsExportRequest interface.
 */
export function instanceOfPostApiUnitStatsExportRequest(value: object): value is PostApiUnitStatsExportRequest {
    return true;
}

export function PostApiUnitStatsExportRequestFromJSON(json: any): PostApiUnitStatsExportRequest {
    return PostApiUnitStatsExportRequestFromJSONTyped(json, false);
}

export function PostApiUnitStatsExportRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostApiUnitStatsExportRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'unitIds': json['unitIds'] == null ? undefined : json['unitIds'],
    };
}

export function PostApiUnitStatsExportRequestToJSON(value?: PostApiUnitStatsExportRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'unitIds': value['unitIds'],
    };
}

