/* tslint:disable */
/* eslint-disable */
/**
 * BoostStudio.Web | exvs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostApiHitboxGroupsExportRequest
 */
export interface PostApiHitboxGroupsExportRequest {
    /**
     * 
     * @type {Array<number>}
     * @memberof PostApiHitboxGroupsExportRequest
     */
    hashes?: Array<number> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof PostApiHitboxGroupsExportRequest
     */
    unitIds?: Array<number> | null;
}

/**
 * Check if a given object implements the PostApiHitboxGroupsExportRequest interface.
 */
export function instanceOfPostApiHitboxGroupsExportRequest(value: object): value is PostApiHitboxGroupsExportRequest {
    return true;
}

export function PostApiHitboxGroupsExportRequestFromJSON(json: any): PostApiHitboxGroupsExportRequest {
    return PostApiHitboxGroupsExportRequestFromJSONTyped(json, false);
}

export function PostApiHitboxGroupsExportRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostApiHitboxGroupsExportRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'hashes': json['hashes'] == null ? undefined : json['hashes'],
        'unitIds': json['unitIds'] == null ? undefined : json['unitIds'],
    };
}

export function PostApiHitboxGroupsExportRequestToJSON(value?: PostApiHitboxGroupsExportRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'hashes': value['hashes'],
        'unitIds': value['unitIds'],
    };
}

