/* tslint:disable */
/* eslint-disable */
/**
 * BoostStudio.Web | exvs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Null } from "./Null";
import { NullFromJSON, NullToJSON } from "./Null";
import type { CreateSeriesCommandId } from "./CreateSeriesCommandId";
import { CreateSeriesCommandIdFromJSON, CreateSeriesCommandIdToJSON } from "./CreateSeriesCommandId";

/**
 * 
 * @export
 * @interface SeriesDto
 */
export interface SeriesDto {
    /**
     * 
     * @type {CreateSeriesCommandId}
     * @memberof SeriesDto
     */
    id?: CreateSeriesCommandId;
    /**
     * 
     * @type {Null}
     * @memberof SeriesDto
     */
    playableSeries?: Null;
    /**
     * 
     * @type {string}
     * @memberof SeriesDto
     */
    slugName?: string;
    /**
     * 
     * @type {string}
     * @memberof SeriesDto
     */
    nameEnglish?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SeriesDto
     */
    nameJapanese?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SeriesDto
     */
    nameChinese?: string | null;
}

/**
 * Check if a given object implements the SeriesDto interface.
 */
export function instanceOfSeriesDto(value: object): value is SeriesDto {
    return true;
}

export function SeriesDtoFromJSON(json: any): SeriesDto {
    return SeriesDtoFromJSONTyped(json, false);
}

export function SeriesDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeriesDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : CreateSeriesCommandIdFromJSON(json['id']),
        'playableSeries': json['playableSeries'] == null ? undefined : NullFromJSON(json['playableSeries']),
        'slugName': json['slugName'] == null ? undefined : json['slugName'],
        'nameEnglish': json['nameEnglish'] == null ? undefined : json['nameEnglish'],
        'nameJapanese': json['nameJapanese'] == null ? undefined : json['nameJapanese'],
        'nameChinese': json['nameChinese'] == null ? undefined : json['nameChinese'],
    };
}

export function SeriesDtoToJSON(value?: SeriesDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': CreateSeriesCommandIdToJSON(value['id']),
        'playableSeries': NullToJSON(value['playableSeries']),
        'slugName': value['slugName'],
        'nameEnglish': value['nameEnglish'],
        'nameJapanese': value['nameJapanese'],
        'nameChinese': value['nameChinese'],
    };
}

