/* tslint:disable */
/* eslint-disable */
/**
 * BoostStudio.Web | exvs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { GetApiAmmoHashParameterInner } from "./GetApiAmmoHashParameterInner";
import {
  GetApiAmmoHashParameterInnerFromJSON,
  GetApiAmmoHashParameterInnerToJSON
} from "./GetApiAmmoHashParameterInner";
import type { UnitAmmoSlotDto } from "./UnitAmmoSlotDto";
import { UnitAmmoSlotDtoFromJSON, UnitAmmoSlotDtoToJSON } from "./UnitAmmoSlotDto";

/**
 * 
 * @export
 * @interface UnitStatDto
 */
export interface UnitStatDto {
    /**
     * 
     * @type {string}
     * @memberof UnitStatDto
     */
    id?: string | null;
    /**
     * 
     * @type {GetApiAmmoHashParameterInner}
     * @memberof UnitStatDto
     */
    unitId?: GetApiAmmoHashParameterInner;
    /**
     * 
     * @type {Array<UnitAmmoSlotDto>}
     * @memberof UnitStatDto
     */
    ammoSlots?: Array<UnitAmmoSlotDto>;
}

/**
 * Check if a given object implements the UnitStatDto interface.
 */
export function instanceOfUnitStatDto(value: object): value is UnitStatDto {
    return true;
}

export function UnitStatDtoFromJSON(json: any): UnitStatDto {
    return UnitStatDtoFromJSONTyped(json, false);
}

export function UnitStatDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnitStatDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'unitId': json['unitId'] == null ? undefined : GetApiAmmoHashParameterInnerFromJSON(json['unitId']),
        'ammoSlots': json['ammoSlots'] == null ? undefined : ((json['ammoSlots'] as Array<any>).map(UnitAmmoSlotDtoFromJSON)),
    };
}

export function UnitStatDtoToJSON(value?: UnitStatDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'unitId': GetApiAmmoHashParameterInnerToJSON(value['unitId']),
        'ammoSlots': value['ammoSlots'] == null ? undefined : ((value['ammoSlots'] as Array<any>).map(UnitAmmoSlotDtoToJSON)),
    };
}

