/* tslint:disable */
/* eslint-disable */
/**
 * BoostStudio.Web | exvs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { GetApiAmmoHashParameterInner } from "./GetApiAmmoHashParameterInner";
import {
  GetApiAmmoHashParameterInnerFromJSON,
  GetApiAmmoHashParameterInnerToJSON
} from "./GetApiAmmoHashParameterInner";
import type { Null } from "./Null";
import { NullFromJSON, NullToJSON } from "./Null";
import type { AmmoDtoUnitId } from "./AmmoDtoUnitId";
import { AmmoDtoUnitIdFromJSON, AmmoDtoUnitIdToJSON } from "./AmmoDtoUnitId";

/**
 * 
 * @export
 * @interface UnitSummaryVm
 */
export interface UnitSummaryVm {
    /**
     * 
     * @type {GetApiAmmoHashParameterInner}
     * @memberof UnitSummaryVm
     */
    unitId?: GetApiAmmoHashParameterInner;
    /**
     * 
     * @type {string}
     * @memberof UnitSummaryVm
     */
    slugName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UnitSummaryVm
     */
    nameEnglish?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UnitSummaryVm
     */
    nameJapanese?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UnitSummaryVm
     */
    nameChinese?: string | null;
    /**
     * 
     * @type {AmmoDtoUnitId}
     * @memberof UnitSummaryVm
     */
    seriesId?: AmmoDtoUnitId | null;
    /**
     * 
     * @type {Null}
     * @memberof UnitSummaryVm
     */
    series?: Null;
}

/**
 * Check if a given object implements the UnitSummaryVm interface.
 */
export function instanceOfUnitSummaryVm(value: object): value is UnitSummaryVm {
    return true;
}

export function UnitSummaryVmFromJSON(json: any): UnitSummaryVm {
    return UnitSummaryVmFromJSONTyped(json, false);
}

export function UnitSummaryVmFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnitSummaryVm {
    if (json == null) {
        return json;
    }
    return {
        
        'unitId': json['unitId'] == null ? undefined : GetApiAmmoHashParameterInnerFromJSON(json['unitId']),
        'slugName': json['slugName'] == null ? undefined : json['slugName'],
        'nameEnglish': json['nameEnglish'] == null ? undefined : json['nameEnglish'],
        'nameJapanese': json['nameJapanese'] == null ? undefined : json['nameJapanese'],
        'nameChinese': json['nameChinese'] == null ? undefined : json['nameChinese'],
        'seriesId': json['seriesId'] == null ? undefined : AmmoDtoUnitIdFromJSON(json['seriesId']),
        'series': json['series'] == null ? undefined : NullFromJSON(json['series']),
    };
}

export function UnitSummaryVmToJSON(value?: UnitSummaryVm | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'unitId': GetApiAmmoHashParameterInnerToJSON(value['unitId']),
        'slugName': value['slugName'],
        'nameEnglish': value['nameEnglish'],
        'nameJapanese': value['nameJapanese'],
        'nameChinese': value['nameChinese'],
        'seriesId': AmmoDtoUnitIdToJSON(value['seriesId']),
        'series': NullToJSON(value['series']),
    };
}

