/* tslint:disable */
/* eslint-disable */
/**
 * BoostStudio.Web | exvs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssetFileType } from './AssetFileType';
import {
    AssetFileTypeFromJSON,
    AssetFileTypeFromJSONTyped,
    AssetFileTypeToJSON,
} from './AssetFileType';

/**
 * 
 * @export
 * @interface UpdateAssetFileByHashCommand
 */
export interface UpdateAssetFileByHashCommand {
    /**
     * 
     * @type {number}
     * @memberof UpdateAssetFileByHashCommand
     */
    hash: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateAssetFileByHashCommand
     */
    order?: number;
    /**
     * 
     * @type {Array<AssetFileType>}
     * @memberof UpdateAssetFileByHashCommand
     */
    fileType?: Array<AssetFileType>;
    /**
     * 
     * @type {number}
     * @memberof UpdateAssetFileByHashCommand
     */
    gameUnitId?: number | null;
}

/**
 * Check if a given object implements the UpdateAssetFileByHashCommand interface.
 */
export function instanceOfUpdateAssetFileByHashCommand(value: object): value is UpdateAssetFileByHashCommand {
    if (!('hash' in value) || value['hash'] === undefined) return false;
    return true;
}

export function UpdateAssetFileByHashCommandFromJSON(json: any): UpdateAssetFileByHashCommand {
    return UpdateAssetFileByHashCommandFromJSONTyped(json, false);
}

export function UpdateAssetFileByHashCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAssetFileByHashCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'hash': json['hash'],
        'order': json['order'] == null ? undefined : json['order'],
        'fileType': json['fileType'] == null ? undefined : ((json['fileType'] as Array<any>).map(AssetFileTypeFromJSON)),
        'gameUnitId': json['gameUnitId'] == null ? undefined : json['gameUnitId'],
    };
}

export function UpdateAssetFileByHashCommandToJSON(value?: UpdateAssetFileByHashCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'hash': value['hash'],
        'order': value['order'],
        'fileType': value['fileType'] == null ? undefined : ((value['fileType'] as Array<any>).map(AssetFileTypeToJSON)),
        'gameUnitId': value['gameUnitId'],
    };
}

