/* tslint:disable */
/* eslint-disable */
/**
 * BoostStudio.Web | exvs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { GetApiAmmoHashParameterInner } from "./GetApiAmmoHashParameterInner";
import {
  GetApiAmmoHashParameterInnerFromJSON,
  GetApiAmmoHashParameterInnerToJSON
} from "./GetApiAmmoHashParameterInner";
import type { Null } from "./Null";
import { NullFromJSON, NullToJSON } from "./Null";
import type { AmmoDtoUnitId } from "./AmmoDtoUnitId";
import { AmmoDtoUnitIdFromJSON, AmmoDtoUnitIdToJSON } from "./AmmoDtoUnitId";

/**
 * 
 * @export
 * @interface UpdateUnitCommand
 */
export interface UpdateUnitCommand {
    /**
     * 
     * @type {GetApiAmmoHashParameterInner}
     * @memberof UpdateUnitCommand
     */
    unitId?: GetApiAmmoHashParameterInner;
    /**
     * 
     * @type {string}
     * @memberof UpdateUnitCommand
     */
    slugName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUnitCommand
     */
    nameEnglish?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUnitCommand
     */
    nameJapanese?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUnitCommand
     */
    nameChinese?: string | null;
    /**
     * 
     * @type {AmmoDtoUnitId}
     * @memberof UpdateUnitCommand
     */
    seriesId?: AmmoDtoUnitId | null;
    /**
     * 
     * @type {Null}
     * @memberof UpdateUnitCommand
     */
    series?: Null;
}

/**
 * Check if a given object implements the UpdateUnitCommand interface.
 */
export function instanceOfUpdateUnitCommand(value: object): value is UpdateUnitCommand {
    return true;
}

export function UpdateUnitCommandFromJSON(json: any): UpdateUnitCommand {
    return UpdateUnitCommandFromJSONTyped(json, false);
}

export function UpdateUnitCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUnitCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'unitId': json['unitId'] == null ? undefined : GetApiAmmoHashParameterInnerFromJSON(json['unitId']),
        'slugName': json['slugName'] == null ? undefined : json['slugName'],
        'nameEnglish': json['nameEnglish'] == null ? undefined : json['nameEnglish'],
        'nameJapanese': json['nameJapanese'] == null ? undefined : json['nameJapanese'],
        'nameChinese': json['nameChinese'] == null ? undefined : json['nameChinese'],
        'seriesId': json['seriesId'] == null ? undefined : AmmoDtoUnitIdFromJSON(json['seriesId']),
        'series': json['series'] == null ? undefined : NullFromJSON(json['series']),
    };
}

export function UpdateUnitCommandToJSON(value?: UpdateUnitCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'unitId': GetApiAmmoHashParameterInnerToJSON(value['unitId']),
        'slugName': value['slugName'],
        'nameEnglish': value['nameEnglish'],
        'nameJapanese': value['nameJapanese'],
        'nameChinese': value['nameChinese'],
        'seriesId': AmmoDtoUnitIdToJSON(value['seriesId']),
        'series': NullToJSON(value['series']),
    };
}

