/* tslint:disable */
/* eslint-disable */
/**
 * BoostStudio.Web | exvs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { GetApiAmmoHashParameterInner } from "./GetApiAmmoHashParameterInner";
import {
  GetApiAmmoHashParameterInnerFromJSON,
  GetApiAmmoHashParameterInnerToJSON
} from "./GetApiAmmoHashParameterInner";

/**
 * 
 * @export
 * @interface UpdateHitboxGroupCommand
 */
export interface UpdateHitboxGroupCommand {
    /**
     * 
     * @type {GetApiAmmoHashParameterInner}
     * @memberof UpdateHitboxGroupCommand
     */
    hash: GetApiAmmoHashParameterInner;
    /**
     * 
     * @type {Array<GetApiAmmoHashParameterInner>}
     * @memberof UpdateHitboxGroupCommand
     */
    unitIds?: Array<GetApiAmmoHashParameterInner>;
}

/**
 * Check if a given object implements the UpdateHitboxGroupCommand interface.
 */
export function instanceOfUpdateHitboxGroupCommand(value: object): value is UpdateHitboxGroupCommand {
    if (!('hash' in value) || value['hash'] === undefined) return false;
    return true;
}

export function UpdateHitboxGroupCommandFromJSON(json: any): UpdateHitboxGroupCommand {
    return UpdateHitboxGroupCommandFromJSONTyped(json, false);
}

export function UpdateHitboxGroupCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateHitboxGroupCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'hash': GetApiAmmoHashParameterInnerFromJSON(json['hash']),
        'unitIds': json['unitIds'] == null ? undefined : ((json['unitIds'] as Array<any>).map(GetApiAmmoHashParameterInnerFromJSON)),
    };
}

export function UpdateHitboxGroupCommandToJSON(value?: UpdateHitboxGroupCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'hash': GetApiAmmoHashParameterInnerToJSON(value['hash']),
        'unitIds': value['unitIds'] == null ? undefined : ((value['unitIds'] as Array<any>).map(GetApiAmmoHashParameterInnerToJSON)),
    };
}

