/* tslint:disable */
/* eslint-disable */
/**
 * BoostStudio.Web | exvs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigDto
 */
export interface ConfigDto {
    /**
     * 
     * @type {string}
     * @memberof ConfigDto
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigDto
     */
    value: string;
}

/**
 * Check if a given object implements the ConfigDto interface.
 */
export function instanceOfConfigDto(value: object): value is ConfigDto {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function ConfigDtoFromJSON(json: any): ConfigDto {
    return ConfigDtoFromJSONTyped(json, false);
}

export function ConfigDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigDto {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'value': json['value'],
    };
}

export function ConfigDtoToJSON(value?: ConfigDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'key': value['key'],
        'value': value['value'],
    };
}

