/* tslint:disable */
/* eslint-disable */
/**
 * BoostStudio.Web | exvs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateHitboxCommand
 */
export interface CreateHitboxCommand {
    /**
     * 
     * @type {number}
     * @memberof CreateHitboxCommand
     */
    hitboxType?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateHitboxCommand
     */
    damage?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateHitboxCommand
     */
    unk8?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateHitboxCommand
     */
    downValueThreshold?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateHitboxCommand
     */
    yorukeValueThreshold?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateHitboxCommand
     */
    unk20?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateHitboxCommand
     */
    unk24?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateHitboxCommand
     */
    damageCorrection?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateHitboxCommand
     */
    specialEffect?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateHitboxCommand
     */
    hitEffect?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateHitboxCommand
     */
    flyDirection1?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateHitboxCommand
     */
    flyDirection2?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateHitboxCommand
     */
    flyDirection3?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateHitboxCommand
     */
    enemyCameraShakeMultiplier?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateHitboxCommand
     */
    playerCameraShakeMultiplier?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateHitboxCommand
     */
    unk56?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateHitboxCommand
     */
    knockUpAngle?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateHitboxCommand
     */
    knockUpRange?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateHitboxCommand
     */
    unk68?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateHitboxCommand
     */
    multipleHitIntervalFrame?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateHitboxCommand
     */
    multipleHitCount?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateHitboxCommand
     */
    enemyStunDuration?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateHitboxCommand
     */
    playerStunDuration?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateHitboxCommand
     */
    hitVisualEffect?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateHitboxCommand
     */
    hitVisualEffectSizeMultiplier?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateHitboxCommand
     */
    hitSoundEffectHash?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateHitboxCommand
     */
    unk100?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateHitboxCommand
     */
    friendlyDamageFlag?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateHitboxCommand
     */
    unk108?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateHitboxCommand
     */
    hitboxGroupHash?: number;
}

/**
 * Check if a given object implements the CreateHitboxCommand interface.
 */
export function instanceOfCreateHitboxCommand(value: object): value is CreateHitboxCommand {
    return true;
}

export function CreateHitboxCommandFromJSON(json: any): CreateHitboxCommand {
    return CreateHitboxCommandFromJSONTyped(json, false);
}

export function CreateHitboxCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateHitboxCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'hitboxType': json['hitboxType'] == null ? undefined : json['hitboxType'],
        'damage': json['damage'] == null ? undefined : json['damage'],
        'unk8': json['unk8'] == null ? undefined : json['unk8'],
        'downValueThreshold': json['downValueThreshold'] == null ? undefined : json['downValueThreshold'],
        'yorukeValueThreshold': json['yorukeValueThreshold'] == null ? undefined : json['yorukeValueThreshold'],
        'unk20': json['unk20'] == null ? undefined : json['unk20'],
        'unk24': json['unk24'] == null ? undefined : json['unk24'],
        'damageCorrection': json['damageCorrection'] == null ? undefined : json['damageCorrection'],
        'specialEffect': json['specialEffect'] == null ? undefined : json['specialEffect'],
        'hitEffect': json['hitEffect'] == null ? undefined : json['hitEffect'],
        'flyDirection1': json['flyDirection1'] == null ? undefined : json['flyDirection1'],
        'flyDirection2': json['flyDirection2'] == null ? undefined : json['flyDirection2'],
        'flyDirection3': json['flyDirection3'] == null ? undefined : json['flyDirection3'],
        'enemyCameraShakeMultiplier': json['enemyCameraShakeMultiplier'] == null ? undefined : json['enemyCameraShakeMultiplier'],
        'playerCameraShakeMultiplier': json['playerCameraShakeMultiplier'] == null ? undefined : json['playerCameraShakeMultiplier'],
        'unk56': json['unk56'] == null ? undefined : json['unk56'],
        'knockUpAngle': json['knockUpAngle'] == null ? undefined : json['knockUpAngle'],
        'knockUpRange': json['knockUpRange'] == null ? undefined : json['knockUpRange'],
        'unk68': json['unk68'] == null ? undefined : json['unk68'],
        'multipleHitIntervalFrame': json['multipleHitIntervalFrame'] == null ? undefined : json['multipleHitIntervalFrame'],
        'multipleHitCount': json['multipleHitCount'] == null ? undefined : json['multipleHitCount'],
        'enemyStunDuration': json['enemyStunDuration'] == null ? undefined : json['enemyStunDuration'],
        'playerStunDuration': json['playerStunDuration'] == null ? undefined : json['playerStunDuration'],
        'hitVisualEffect': json['hitVisualEffect'] == null ? undefined : json['hitVisualEffect'],
        'hitVisualEffectSizeMultiplier': json['hitVisualEffectSizeMultiplier'] == null ? undefined : json['hitVisualEffectSizeMultiplier'],
        'hitSoundEffectHash': json['hitSoundEffectHash'] == null ? undefined : json['hitSoundEffectHash'],
        'unk100': json['unk100'] == null ? undefined : json['unk100'],
        'friendlyDamageFlag': json['friendlyDamageFlag'] == null ? undefined : json['friendlyDamageFlag'],
        'unk108': json['unk108'] == null ? undefined : json['unk108'],
        'hitboxGroupHash': json['hitboxGroupHash'] == null ? undefined : json['hitboxGroupHash'],
    };
}

export function CreateHitboxCommandToJSON(value?: CreateHitboxCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'hitboxType': value['hitboxType'],
        'damage': value['damage'],
        'unk8': value['unk8'],
        'downValueThreshold': value['downValueThreshold'],
        'yorukeValueThreshold': value['yorukeValueThreshold'],
        'unk20': value['unk20'],
        'unk24': value['unk24'],
        'damageCorrection': value['damageCorrection'],
        'specialEffect': value['specialEffect'],
        'hitEffect': value['hitEffect'],
        'flyDirection1': value['flyDirection1'],
        'flyDirection2': value['flyDirection2'],
        'flyDirection3': value['flyDirection3'],
        'enemyCameraShakeMultiplier': value['enemyCameraShakeMultiplier'],
        'playerCameraShakeMultiplier': value['playerCameraShakeMultiplier'],
        'unk56': value['unk56'],
        'knockUpAngle': value['knockUpAngle'],
        'knockUpRange': value['knockUpRange'],
        'unk68': value['unk68'],
        'multipleHitIntervalFrame': value['multipleHitIntervalFrame'],
        'multipleHitCount': value['multipleHitCount'],
        'enemyStunDuration': value['enemyStunDuration'],
        'playerStunDuration': value['playerStunDuration'],
        'hitVisualEffect': value['hitVisualEffect'],
        'hitVisualEffectSizeMultiplier': value['hitVisualEffectSizeMultiplier'],
        'hitSoundEffectHash': value['hitSoundEffectHash'],
        'unk100': value['unk100'],
        'friendlyDamageFlag': value['friendlyDamageFlag'],
        'unk108': value['unk108'],
        'hitboxGroupHash': value['hitboxGroupHash'],
    };
}

