/* tslint:disable */
/* eslint-disable */
/**
 * BoostStudio.Web | exvs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssetFileType } from './AssetFileType';
import {
    AssetFileTypeFromJSON,
    AssetFileTypeFromJSONTyped,
    AssetFileTypeToJSON,
} from './AssetFileType';

/**
 * 
 * @export
 * @interface CreateAssetFileCommand
 */
export interface CreateAssetFileCommand {
    /**
     * 
     * @type {number}
     * @memberof CreateAssetFileCommand
     */
    order?: number;
    /**
     * 
     * @type {AssetFileType}
     * @memberof CreateAssetFileCommand
     */
    fileType?: AssetFileType;
    /**
     * 
     * @type {number}
     * @memberof CreateAssetFileCommand
     */
    gameUnitId?: number | null;
}

/**
 * Check if a given object implements the CreateAssetFileCommand interface.
 */
export function instanceOfCreateAssetFileCommand(value: object): value is CreateAssetFileCommand {
    return true;
}

export function CreateAssetFileCommandFromJSON(json: any): CreateAssetFileCommand {
    return CreateAssetFileCommandFromJSONTyped(json, false);
}

export function CreateAssetFileCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAssetFileCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'order': json['order'] == null ? undefined : json['order'],
        'fileType': json['fileType'] == null ? undefined : AssetFileTypeFromJSON(json['fileType']),
        'gameUnitId': json['gameUnitId'] == null ? undefined : json['gameUnitId'],
    };
}

export function CreateAssetFileCommandToJSON(value?: CreateAssetFileCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'order': value['order'],
        'fileType': AssetFileTypeToJSON(value['fileType']),
        'gameUnitId': value['gameUnitId'],
    };
}

