/* tslint:disable */
/* eslint-disable */
/**
 * BoostStudio.Web | exvs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateUnitCommand
 */
export interface CreateUnitCommand {
    /**
     * 
     * @type {number}
     * @memberof CreateUnitCommand
     */
    unitId?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateUnitCommand
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUnitCommand
     */
    nameJapanese?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUnitCommand
     */
    nameChinese?: string;
}

/**
 * Check if a given object implements the CreateUnitCommand interface.
 */
export function instanceOfCreateUnitCommand(value: object): value is CreateUnitCommand {
    return true;
}

export function CreateUnitCommandFromJSON(json: any): CreateUnitCommand {
    return CreateUnitCommandFromJSONTyped(json, false);
}

export function CreateUnitCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUnitCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'unitId': json['unitId'] == null ? undefined : json['unitId'],
        'name': json['name'] == null ? undefined : json['name'],
        'nameJapanese': json['nameJapanese'] == null ? undefined : json['nameJapanese'],
        'nameChinese': json['nameChinese'] == null ? undefined : json['nameChinese'],
    };
}

export function CreateUnitCommandToJSON(value?: CreateUnitCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'unitId': value['unitId'],
        'name': value['name'],
        'nameJapanese': value['nameJapanese'],
        'nameChinese': value['nameChinese'],
    };
}

