/* tslint:disable */
/* eslint-disable */
/**
 * BoostStudio.Web | exvs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetApiProjectilesByHash200Response } from './GetApiProjectilesByHash200Response';
import {
    GetApiProjectilesByHash200ResponseFromJSON,
    GetApiProjectilesByHash200ResponseFromJSONTyped,
    GetApiProjectilesByHash200ResponseToJSON,
} from './GetApiProjectilesByHash200Response';

/**
 * 
 * @export
 * @interface GetApiProjectiles200Response
 */
export interface GetApiProjectiles200Response {
    /**
     * 
     * @type {Array<GetApiProjectilesByHash200Response>}
     * @memberof GetApiProjectiles200Response
     */
    items: Array<GetApiProjectilesByHash200Response>;
    /**
     * 
     * @type {number}
     * @memberof GetApiProjectiles200Response
     */
    pageNumber: number;
    /**
     * 
     * @type {number}
     * @memberof GetApiProjectiles200Response
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof GetApiProjectiles200Response
     */
    totalCount: number;
    /**
     * 
     * @type {boolean}
     * @memberof GetApiProjectiles200Response
     */
    hasPreviousPage?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GetApiProjectiles200Response
     */
    hasNextPage?: boolean;
}

/**
 * Check if a given object implements the GetApiProjectiles200Response interface.
 */
export function instanceOfGetApiProjectiles200Response(value: object): value is GetApiProjectiles200Response {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pageNumber' in value) || value['pageNumber'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    return true;
}

export function GetApiProjectiles200ResponseFromJSON(json: any): GetApiProjectiles200Response {
    return GetApiProjectiles200ResponseFromJSONTyped(json, false);
}

export function GetApiProjectiles200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetApiProjectiles200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(GetApiProjectilesByHash200ResponseFromJSON)),
        'pageNumber': json['pageNumber'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'totalCount': json['totalCount'],
        'hasPreviousPage': json['hasPreviousPage'] == null ? undefined : json['hasPreviousPage'],
        'hasNextPage': json['hasNextPage'] == null ? undefined : json['hasNextPage'],
    };
}

export function GetApiProjectiles200ResponseToJSON(value?: GetApiProjectiles200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(GetApiProjectilesByHash200ResponseToJSON)),
        'pageNumber': value['pageNumber'],
        'totalPages': value['totalPages'],
        'totalCount': value['totalCount'],
        'hasPreviousPage': value['hasPreviousPage'],
        'hasNextPage': value['hasNextPage'],
    };
}

