/* tslint:disable */
/* eslint-disable */
/**
 * BoostStudio.Web | exvs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetApiTblById200Response
 */
export interface GetApiTblById200Response {
    /**
     * 
     * @type {string}
     * @memberof GetApiTblById200Response
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof GetApiTblById200Response
     */
    cumulativeAssetIndex?: number;
}

/**
 * Check if a given object implements the GetApiTblById200Response interface.
 */
export function instanceOfGetApiTblById200Response(value: object): value is GetApiTblById200Response {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function GetApiTblById200ResponseFromJSON(json: any): GetApiTblById200Response {
    return GetApiTblById200ResponseFromJSONTyped(json, false);
}

export function GetApiTblById200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetApiTblById200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'cumulativeAssetIndex': json['cumulativeAssetIndex'] == null ? undefined : json['cumulativeAssetIndex'],
    };
}

export function GetApiTblById200ResponseToJSON(value?: GetApiTblById200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'cumulativeAssetIndex': value['cumulativeAssetIndex'],
    };
}

