/* tslint:disable */
/* eslint-disable */
/**
 * BoostStudio.Web | exvs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const NullableOfCompressionType = {
    None: 'None',
    Zlib: 'Zlib',
    Lzma: 'Lzma',
    Null: 'null'
} as const;
export type NullableOfCompressionType = typeof NullableOfCompressionType[keyof typeof NullableOfCompressionType];


export function instanceOfNullableOfCompressionType(value: any): boolean {
    for (const key in NullableOfCompressionType) {
        if (Object.prototype.hasOwnProperty.call(NullableOfCompressionType, key)) {
            if ((NullableOfCompressionType as Record<string, NullableOfCompressionType>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function NullableOfCompressionTypeFromJSON(json: any): NullableOfCompressionType {
    return NullableOfCompressionTypeFromJSONTyped(json, false);
}

export function NullableOfCompressionTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): NullableOfCompressionType {
    return json as NullableOfCompressionType;
}

export function NullableOfCompressionTypeToJSON(value?: NullableOfCompressionType | null): any {
    return value as any;
}

