/* tslint:disable */
/* eslint-disable */
/**
 * BoostStudio.Web | exvs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PathInfoDto } from './PathInfoDto';
import {
    PathInfoDtoFromJSON,
    PathInfoDtoFromJSONTyped,
    PathInfoDtoToJSON,
} from './PathInfoDto';
import type { AssetFileDto } from './AssetFileDto';
import {
    AssetFileDtoFromJSON,
    AssetFileDtoFromJSONTyped,
    AssetFileDtoToJSON,
} from './AssetFileDto';
import type { PatchFileVersion } from './PatchFileVersion';
import {
    PatchFileVersionFromJSON,
    PatchFileVersionFromJSONTyped,
    PatchFileVersionToJSON,
} from './PatchFileVersion';
import type { FileInfoDto } from './FileInfoDto';
import {
    FileInfoDtoFromJSON,
    FileInfoDtoFromJSONTyped,
    FileInfoDtoToJSON,
} from './FileInfoDto';

/**
 * 
 * @export
 * @interface PatchFileSummaryVm
 */
export interface PatchFileSummaryVm {
    /**
     * 
     * @type {AssetFileDto}
     * @memberof PatchFileSummaryVm
     */
    assetFile?: AssetFileDto | null;
    /**
     * 
     * @type {string}
     * @memberof PatchFileSummaryVm
     */
    id: string | null;
    /**
     * 
     * @type {PatchFileVersion}
     * @memberof PatchFileSummaryVm
     */
    tblId: PatchFileVersion;
    /**
     * 
     * @type {PathInfoDto}
     * @memberof PatchFileSummaryVm
     */
    pathInfo?: PathInfoDto | null;
    /**
     * 
     * @type {FileInfoDto}
     * @memberof PatchFileSummaryVm
     */
    fileInfo?: FileInfoDto | null;
    /**
     * 
     * @type {number}
     * @memberof PatchFileSummaryVm
     */
    assetFileHash?: number | null;
}

/**
 * Check if a given object implements the PatchFileSummaryVm interface.
 */
export function instanceOfPatchFileSummaryVm(value: object): value is PatchFileSummaryVm {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('tblId' in value) || value['tblId'] === undefined) return false;
    return true;
}

export function PatchFileSummaryVmFromJSON(json: any): PatchFileSummaryVm {
    return PatchFileSummaryVmFromJSONTyped(json, false);
}

export function PatchFileSummaryVmFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchFileSummaryVm {
    if (json == null) {
        return json;
    }
    return {
        
        'assetFile': json['assetFile'] == null ? undefined : AssetFileDtoFromJSON(json['assetFile']),
        'id': json['id'],
        'tblId': PatchFileVersionFromJSON(json['tblId']),
        'pathInfo': json['pathInfo'] == null ? undefined : PathInfoDtoFromJSON(json['pathInfo']),
        'fileInfo': json['fileInfo'] == null ? undefined : FileInfoDtoFromJSON(json['fileInfo']),
        'assetFileHash': json['assetFileHash'] == null ? undefined : json['assetFileHash'],
    };
}

export function PatchFileSummaryVmToJSON(value?: PatchFileSummaryVm | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'assetFile': AssetFileDtoToJSON(value['assetFile']),
        'id': value['id'],
        'tblId': PatchFileVersionToJSON(value['tblId']),
        'pathInfo': PathInfoDtoToJSON(value['pathInfo']),
        'fileInfo': FileInfoDtoToJSON(value['fileInfo']),
        'assetFileHash': value['assetFileHash'],
    };
}

