/* tslint:disable */
/* eslint-disable */
/**
 * BoostStudio.Web | exvs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostApiAmmoByHashRequest
 */
export interface PostApiAmmoByHashRequest {
    /**
     * 
     * @type {number}
     * @memberof PostApiAmmoByHashRequest
     */
    hash: number;
    /**
     * 
     * @type {number}
     * @memberof PostApiAmmoByHashRequest
     */
    ammoType?: number;
    /**
     * 
     * @type {number}
     * @memberof PostApiAmmoByHashRequest
     */
    maxAmmo?: number;
    /**
     * 
     * @type {number}
     * @memberof PostApiAmmoByHashRequest
     */
    initialAmmo?: number;
    /**
     * 
     * @type {number}
     * @memberof PostApiAmmoByHashRequest
     */
    timedDurationFrame?: number;
    /**
     * 
     * @type {number}
     * @memberof PostApiAmmoByHashRequest
     */
    unk16?: number;
    /**
     * 
     * @type {number}
     * @memberof PostApiAmmoByHashRequest
     */
    reloadType?: number;
    /**
     * 
     * @type {number}
     * @memberof PostApiAmmoByHashRequest
     */
    cooldownDurationFrame?: number;
    /**
     * 
     * @type {number}
     * @memberof PostApiAmmoByHashRequest
     */
    reloadDurationFrame?: number;
    /**
     * 
     * @type {number}
     * @memberof PostApiAmmoByHashRequest
     */
    assaultBurstReloadDurationFrame?: number;
    /**
     * 
     * @type {number}
     * @memberof PostApiAmmoByHashRequest
     */
    blastBurstReloadDurationFrame?: number;
    /**
     * 
     * @type {number}
     * @memberof PostApiAmmoByHashRequest
     */
    unk40?: number;
    /**
     * 
     * @type {number}
     * @memberof PostApiAmmoByHashRequest
     */
    unk44?: number;
    /**
     * 
     * @type {number}
     * @memberof PostApiAmmoByHashRequest
     */
    inactiveUnk48?: number;
    /**
     * 
     * @type {number}
     * @memberof PostApiAmmoByHashRequest
     */
    inactiveCooldownDurationFrame?: number;
    /**
     * 
     * @type {number}
     * @memberof PostApiAmmoByHashRequest
     */
    inactiveReloadDurationFrame?: number;
    /**
     * 
     * @type {number}
     * @memberof PostApiAmmoByHashRequest
     */
    inactiveAssaultBurstReloadDurationFrame?: number;
    /**
     * 
     * @type {number}
     * @memberof PostApiAmmoByHashRequest
     */
    inactiveBlastBurstReloadDurationFrame?: number;
    /**
     * 
     * @type {number}
     * @memberof PostApiAmmoByHashRequest
     */
    inactiveUnk68?: number;
    /**
     * 
     * @type {number}
     * @memberof PostApiAmmoByHashRequest
     */
    inactiveUnk72?: number;
    /**
     * 
     * @type {number}
     * @memberof PostApiAmmoByHashRequest
     */
    burstReplenish?: number;
    /**
     * 
     * @type {number}
     * @memberof PostApiAmmoByHashRequest
     */
    unk80?: number;
    /**
     * 
     * @type {number}
     * @memberof PostApiAmmoByHashRequest
     */
    unk84?: number;
    /**
     * 
     * @type {number}
     * @memberof PostApiAmmoByHashRequest
     */
    unk88?: number;
    /**
     * 
     * @type {number}
     * @memberof PostApiAmmoByHashRequest
     */
    chargeInput?: number;
    /**
     * 
     * @type {number}
     * @memberof PostApiAmmoByHashRequest
     */
    chargeDurationFrame?: number;
    /**
     * 
     * @type {number}
     * @memberof PostApiAmmoByHashRequest
     */
    assaultBurstChargeDurationFrame?: number;
    /**
     * 
     * @type {number}
     * @memberof PostApiAmmoByHashRequest
     */
    blastBurstChargeDurationFrame?: number;
    /**
     * 
     * @type {number}
     * @memberof PostApiAmmoByHashRequest
     */
    unk108?: number;
    /**
     * 
     * @type {number}
     * @memberof PostApiAmmoByHashRequest
     */
    unk112?: number;
    /**
     * 
     * @type {number}
     * @memberof PostApiAmmoByHashRequest
     */
    releaseChargeLingerDurationFrame?: number;
    /**
     * 
     * @type {number}
     * @memberof PostApiAmmoByHashRequest
     */
    maxChargeLevel?: number;
    /**
     * 
     * @type {number}
     * @memberof PostApiAmmoByHashRequest
     */
    unk124?: number;
    /**
     * 
     * @type {number}
     * @memberof PostApiAmmoByHashRequest
     */
    unk128?: number;
    /**
     * 
     * @type {number}
     * @memberof PostApiAmmoByHashRequest
     */
    order?: number;
    /**
     * 
     * @type {number}
     * @memberof PostApiAmmoByHashRequest
     */
    unitId?: number | null;
}

/**
 * Check if a given object implements the PostApiAmmoByHashRequest interface.
 */
export function instanceOfPostApiAmmoByHashRequest(value: object): value is PostApiAmmoByHashRequest {
    if (!('hash' in value) || value['hash'] === undefined) return false;
    return true;
}

export function PostApiAmmoByHashRequestFromJSON(json: any): PostApiAmmoByHashRequest {
    return PostApiAmmoByHashRequestFromJSONTyped(json, false);
}

export function PostApiAmmoByHashRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostApiAmmoByHashRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'hash': json['hash'],
        'ammoType': json['ammoType'] == null ? undefined : json['ammoType'],
        'maxAmmo': json['maxAmmo'] == null ? undefined : json['maxAmmo'],
        'initialAmmo': json['initialAmmo'] == null ? undefined : json['initialAmmo'],
        'timedDurationFrame': json['timedDurationFrame'] == null ? undefined : json['timedDurationFrame'],
        'unk16': json['unk16'] == null ? undefined : json['unk16'],
        'reloadType': json['reloadType'] == null ? undefined : json['reloadType'],
        'cooldownDurationFrame': json['cooldownDurationFrame'] == null ? undefined : json['cooldownDurationFrame'],
        'reloadDurationFrame': json['reloadDurationFrame'] == null ? undefined : json['reloadDurationFrame'],
        'assaultBurstReloadDurationFrame': json['assaultBurstReloadDurationFrame'] == null ? undefined : json['assaultBurstReloadDurationFrame'],
        'blastBurstReloadDurationFrame': json['blastBurstReloadDurationFrame'] == null ? undefined : json['blastBurstReloadDurationFrame'],
        'unk40': json['unk40'] == null ? undefined : json['unk40'],
        'unk44': json['unk44'] == null ? undefined : json['unk44'],
        'inactiveUnk48': json['inactiveUnk48'] == null ? undefined : json['inactiveUnk48'],
        'inactiveCooldownDurationFrame': json['inactiveCooldownDurationFrame'] == null ? undefined : json['inactiveCooldownDurationFrame'],
        'inactiveReloadDurationFrame': json['inactiveReloadDurationFrame'] == null ? undefined : json['inactiveReloadDurationFrame'],
        'inactiveAssaultBurstReloadDurationFrame': json['inactiveAssaultBurstReloadDurationFrame'] == null ? undefined : json['inactiveAssaultBurstReloadDurationFrame'],
        'inactiveBlastBurstReloadDurationFrame': json['inactiveBlastBurstReloadDurationFrame'] == null ? undefined : json['inactiveBlastBurstReloadDurationFrame'],
        'inactiveUnk68': json['inactiveUnk68'] == null ? undefined : json['inactiveUnk68'],
        'inactiveUnk72': json['inactiveUnk72'] == null ? undefined : json['inactiveUnk72'],
        'burstReplenish': json['burstReplenish'] == null ? undefined : json['burstReplenish'],
        'unk80': json['unk80'] == null ? undefined : json['unk80'],
        'unk84': json['unk84'] == null ? undefined : json['unk84'],
        'unk88': json['unk88'] == null ? undefined : json['unk88'],
        'chargeInput': json['chargeInput'] == null ? undefined : json['chargeInput'],
        'chargeDurationFrame': json['chargeDurationFrame'] == null ? undefined : json['chargeDurationFrame'],
        'assaultBurstChargeDurationFrame': json['assaultBurstChargeDurationFrame'] == null ? undefined : json['assaultBurstChargeDurationFrame'],
        'blastBurstChargeDurationFrame': json['blastBurstChargeDurationFrame'] == null ? undefined : json['blastBurstChargeDurationFrame'],
        'unk108': json['unk108'] == null ? undefined : json['unk108'],
        'unk112': json['unk112'] == null ? undefined : json['unk112'],
        'releaseChargeLingerDurationFrame': json['releaseChargeLingerDurationFrame'] == null ? undefined : json['releaseChargeLingerDurationFrame'],
        'maxChargeLevel': json['maxChargeLevel'] == null ? undefined : json['maxChargeLevel'],
        'unk124': json['unk124'] == null ? undefined : json['unk124'],
        'unk128': json['unk128'] == null ? undefined : json['unk128'],
        'order': json['order'] == null ? undefined : json['order'],
        'unitId': json['unitId'] == null ? undefined : json['unitId'],
    };
}

export function PostApiAmmoByHashRequestToJSON(value?: PostApiAmmoByHashRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'hash': value['hash'],
        'ammoType': value['ammoType'],
        'maxAmmo': value['maxAmmo'],
        'initialAmmo': value['initialAmmo'],
        'timedDurationFrame': value['timedDurationFrame'],
        'unk16': value['unk16'],
        'reloadType': value['reloadType'],
        'cooldownDurationFrame': value['cooldownDurationFrame'],
        'reloadDurationFrame': value['reloadDurationFrame'],
        'assaultBurstReloadDurationFrame': value['assaultBurstReloadDurationFrame'],
        'blastBurstReloadDurationFrame': value['blastBurstReloadDurationFrame'],
        'unk40': value['unk40'],
        'unk44': value['unk44'],
        'inactiveUnk48': value['inactiveUnk48'],
        'inactiveCooldownDurationFrame': value['inactiveCooldownDurationFrame'],
        'inactiveReloadDurationFrame': value['inactiveReloadDurationFrame'],
        'inactiveAssaultBurstReloadDurationFrame': value['inactiveAssaultBurstReloadDurationFrame'],
        'inactiveBlastBurstReloadDurationFrame': value['inactiveBlastBurstReloadDurationFrame'],
        'inactiveUnk68': value['inactiveUnk68'],
        'inactiveUnk72': value['inactiveUnk72'],
        'burstReplenish': value['burstReplenish'],
        'unk80': value['unk80'],
        'unk84': value['unk84'],
        'unk88': value['unk88'],
        'chargeInput': value['chargeInput'],
        'chargeDurationFrame': value['chargeDurationFrame'],
        'assaultBurstChargeDurationFrame': value['assaultBurstChargeDurationFrame'],
        'blastBurstChargeDurationFrame': value['blastBurstChargeDurationFrame'],
        'unk108': value['unk108'],
        'unk112': value['unk112'],
        'releaseChargeLingerDurationFrame': value['releaseChargeLingerDurationFrame'],
        'maxChargeLevel': value['maxChargeLevel'],
        'unk124': value['unk124'],
        'unk128': value['unk128'],
        'order': value['order'],
        'unitId': value['unitId'],
    };
}

