/* tslint:disable */
/* eslint-disable */
/**
 * BoostStudio.Web | exvs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostApiAmmoExportPathRequest
 */
export interface PostApiAmmoExportPathRequest {
    /**
     * 
     * @type {string}
     * @memberof PostApiAmmoExportPathRequest
     */
    exportPath?: string | null;
}

/**
 * Check if a given object implements the PostApiAmmoExportPathRequest interface.
 */
export function instanceOfPostApiAmmoExportPathRequest(value: object): value is PostApiAmmoExportPathRequest {
    return true;
}

export function PostApiAmmoExportPathRequestFromJSON(json: any): PostApiAmmoExportPathRequest {
    return PostApiAmmoExportPathRequestFromJSONTyped(json, false);
}

export function PostApiAmmoExportPathRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostApiAmmoExportPathRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'exportPath': json['exportPath'] == null ? undefined : json['exportPath'],
    };
}

export function PostApiAmmoExportPathRequestToJSON(value?: PostApiAmmoExportPathRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'exportPath': value['exportPath'],
    };
}

