/* tslint:disable */
/* eslint-disable */
/**
 * BoostStudio.Web | exvs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostApiTblDeserialize200ResponseFileMetadataInner } from './PostApiTblDeserialize200ResponseFileMetadataInner';
import {
    PostApiTblDeserialize200ResponseFileMetadataInnerFromJSON,
    PostApiTblDeserialize200ResponseFileMetadataInnerFromJSONTyped,
    PostApiTblDeserialize200ResponseFileMetadataInnerToJSON,
} from './PostApiTblDeserialize200ResponseFileMetadataInner';

/**
 * 
 * @export
 * @interface TblMetadata2
 */
export interface TblMetadata2 {
    /**
     * 
     * @type {number}
     * @memberof TblMetadata2
     */
    cumulativeFileInfoCount: number;
    /**
     * 
     * @type {Array<PostApiTblDeserialize200ResponseFileMetadataInner>}
     * @memberof TblMetadata2
     */
    fileMetadata: Array<PostApiTblDeserialize200ResponseFileMetadataInner>;
    /**
     * 
     * @type {Array<string>}
     * @memberof TblMetadata2
     */
    pathOrder?: Array<string> | null;
}

/**
 * Check if a given object implements the TblMetadata2 interface.
 */
export function instanceOfTblMetadata2(value: object): value is TblMetadata2 {
    if (!('cumulativeFileInfoCount' in value) || value['cumulativeFileInfoCount'] === undefined) return false;
    if (!('fileMetadata' in value) || value['fileMetadata'] === undefined) return false;
    return true;
}

export function TblMetadata2FromJSON(json: any): TblMetadata2 {
    return TblMetadata2FromJSONTyped(json, false);
}

export function TblMetadata2FromJSONTyped(json: any, ignoreDiscriminator: boolean): TblMetadata2 {
    if (json == null) {
        return json;
    }
    return {
        
        'cumulativeFileInfoCount': json['cumulativeFileInfoCount'],
        'fileMetadata': ((json['fileMetadata'] as Array<any>).map(PostApiTblDeserialize200ResponseFileMetadataInnerFromJSON)),
        'pathOrder': json['pathOrder'] == null ? undefined : json['pathOrder'],
    };
}

export function TblMetadata2ToJSON(value?: TblMetadata2 | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'cumulativeFileInfoCount': value['cumulativeFileInfoCount'],
        'fileMetadata': ((value['fileMetadata'] as Array<any>).map(PostApiTblDeserialize200ResponseFileMetadataInnerToJSON)),
        'pathOrder': value['pathOrder'],
    };
}

