/* tslint:disable */
/* eslint-disable */
/**
 * BoostStudio.Web | exvs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PatchFileVersion } from './PatchFileVersion';
import {
    PatchFileVersionFromJSON,
    PatchFileVersionFromJSONTyped,
    PatchFileVersionToJSON,
} from './PatchFileVersion';

/**
 * 
 * @export
 * @interface UnpackPsarcByPatchFilesCommand
 */
export interface UnpackPsarcByPatchFilesCommand {
    /**
     * 
     * @type {Array<PatchFileVersion>}
     * @memberof UnpackPsarcByPatchFilesCommand
     */
    patchFileVersions?: Array<PatchFileVersion> | null;
}

/**
 * Check if a given object implements the UnpackPsarcByPatchFilesCommand interface.
 */
export function instanceOfUnpackPsarcByPatchFilesCommand(value: object): value is UnpackPsarcByPatchFilesCommand {
    return true;
}

export function UnpackPsarcByPatchFilesCommandFromJSON(json: any): UnpackPsarcByPatchFilesCommand {
    return UnpackPsarcByPatchFilesCommandFromJSONTyped(json, false);
}

export function UnpackPsarcByPatchFilesCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnpackPsarcByPatchFilesCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'patchFileVersions': json['patchFileVersions'] == null ? undefined : ((json['patchFileVersions'] as Array<any>).map(PatchFileVersionFromJSON)),
    };
}

export function UnpackPsarcByPatchFilesCommandToJSON(value?: UnpackPsarcByPatchFilesCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'patchFileVersions': value['patchFileVersions'] == null ? undefined : ((value['patchFileVersions'] as Array<any>).map(PatchFileVersionToJSON)),
    };
}

