/* tslint:disable */
/* eslint-disable */
/**
 * BoostStudio.Web | exvs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UnpackPsarcByPathCommand
 */
export interface UnpackPsarcByPathCommand {
    /**
     * 
     * @type {string}
     * @memberof UnpackPsarcByPathCommand
     */
    sourceFilePath: string;
    /**
     * 
     * @type {string}
     * @memberof UnpackPsarcByPathCommand
     */
    outputDirectoryPath: string;
}

/**
 * Check if a given object implements the UnpackPsarcByPathCommand interface.
 */
export function instanceOfUnpackPsarcByPathCommand(value: object): value is UnpackPsarcByPathCommand {
    if (!('sourceFilePath' in value) || value['sourceFilePath'] === undefined) return false;
    if (!('outputDirectoryPath' in value) || value['outputDirectoryPath'] === undefined) return false;
    return true;
}

export function UnpackPsarcByPathCommandFromJSON(json: any): UnpackPsarcByPathCommand {
    return UnpackPsarcByPathCommandFromJSONTyped(json, false);
}

export function UnpackPsarcByPathCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnpackPsarcByPathCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'sourceFilePath': json['sourceFilePath'],
        'outputDirectoryPath': json['outputDirectoryPath'],
    };
}

export function UnpackPsarcByPathCommandToJSON(value?: UnpackPsarcByPathCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'sourceFilePath': value['sourceFilePath'],
        'outputDirectoryPath': value['outputDirectoryPath'],
    };
}

