/* tslint:disable */
/* eslint-disable */
/**
 * BoostStudio.Web | exvs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpsertConfigCommand
 */
export interface UpsertConfigCommand {
    /**
     * 
     * @type {string}
     * @memberof UpsertConfigCommand
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof UpsertConfigCommand
     */
    value: string;
}

/**
 * Check if a given object implements the UpsertConfigCommand interface.
 */
export function instanceOfUpsertConfigCommand(value: object): value is UpsertConfigCommand {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function UpsertConfigCommandFromJSON(json: any): UpsertConfigCommand {
    return UpsertConfigCommandFromJSONTyped(json, false);
}

export function UpsertConfigCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpsertConfigCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'value': json['value'],
    };
}

export function UpsertConfigCommandToJSON(value?: UpsertConfigCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'key': value['key'],
        'value': value['value'],
    };
}

