# @name PATCH_01.TBL
POST https://localhost:5001/api/tbl/deserialize
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="PATCH_01.TBL"

< ./PATCH_01.TBL
--WebAppBoundary--
###

# @name PATCH_02.TBL
POST https://localhost:5001/api/tbl/deserialize
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="PATCH_02.TBL"

< ./PATCH_02.TBL
--WebAppBoundary--
###

# @name PATCH_03.TBL
POST https://localhost:5001/api/tbl/deserialize
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="PATCH_03.TBL"

< ./PATCH_03.TBL
--WebAppBoundary--
###

# @name PATCH_04.TBL
POST https://localhost:5001/api/tbl/deserialize
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="PATCH_04.TBL"

< ./PATCH_04.TBL
--WebAppBoundary--
###

# @name PATCH_05.TBL
POST https://localhost:5001/api/tbl/deserialize
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="PATCH_05.TBL"

< ./PATCH_05.TBL
--WebAppBoundary--

###

# @name PATCH_06.TBL
POST https://localhost:5001/api/tbl/deserialize
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="PATCH_06.TBL"

< ./PATCH_06.TBL
--WebAppBoundary--
###
