// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://src` | (string & {});
};

export type AmmoDto = {
    hash?: number | string;
    ammoType?: number | string;
    maxAmmo?: number | string;
    initialAmmo?: number | string;
    timedDurationFrame?: number | string;
    unk16?: number | string;
    reloadType?: number | string;
    cooldownDurationFrame?: number | string;
    reloadDurationFrame?: number | string;
    assaultBurstReloadDurationFrame?: number | string;
    blastBurstReloadDurationFrame?: number | string;
    unk40?: number | string;
    unk44?: number | string;
    inactiveUnk48?: number | string;
    inactiveCooldownDurationFrame?: number | string;
    inactiveReloadDurationFrame?: number | string;
    inactiveAssaultBurstReloadDurationFrame?: number | string;
    inactiveBlastBurstReloadDurationFrame?: number | string;
    inactiveUnk68?: number | string;
    inactiveUnk72?: number | string;
    burstReplenish?: number | string;
    unk80?: number | string;
    unk84?: number | string;
    unk88?: number | string;
    chargeInput?: number | string;
    chargeDurationFrame?: number | string;
    assaultBurstChargeDurationFrame?: number | string;
    blastBurstChargeDurationFrame?: number | string;
    unk108?: number | string;
    unk112?: number | string;
    releaseChargeLingerDurationFrame?: number | string;
    maxChargeLevel?: number | string;
    unk124?: number | string;
    chargeMultiLockFlag?: number | string;
    order?: number | string;
    unitId?: null | number | string;
};

export type AssetFileDto = null | {
    hash: number | string;
    order: number | string;
    fileType: Array<AssetFileType>;
    units: Array<UnitSummaryVm>;
};

export type AssetFileType = 'Unknown' | 'Dummy' | 'Animations' | 'ModelAndTexture' | 'Data' | 'Effects' | 'SoundEffects' | 'InGamePilotVoiceLines' | 'SpriteFrames' | 'WeaponSprites' | 'VoiceLinesMetadata' | 'PilotVoiceLines' | 'ArcadeSelectionCostume1Sprite' | 'ArcadeSelectionCostume2Sprite' | 'ArcadeSelectionCostume3Sprite' | 'LoadingLeftCostume1Sprite' | 'LoadingLeftCostume2Sprite' | 'LoadingLeftCostume3Sprite' | 'LoadingRightCostume1Sprite' | 'LoadingRightCostume2Sprite' | 'LoadingRightCostume3Sprite' | 'GenericSelectionCostume1Sprite' | 'GenericSelectionCostume2Sprite' | 'GenericSelectionCostume3Sprite' | 'LoadingTargetUnitSprite' | 'LoadingTargetPilotCostume1Sprite' | 'LoadingTargetPilotCostume2Sprite' | 'LoadingTargetPilotCostume3Sprite' | 'InGameSortieAndAwakeningPilotCostume1Sprite' | 'InGameSortieAndAwakeningPilotCostume2Sprite' | 'InGameSortieAndAwakeningPilotCostume3Sprite' | 'ResultSmallUnitSprite' | 'FigurineSprite' | 'LoadingTargetUnitSmallSprite' | 'CatalogStorePilotCostume2Sprite' | 'CatalogStorePilotCostume3Sprite' | 'Movie' | 'Hitboxes' | 'Projectiles' | 'Ammo' | 'ListInfo' | 'UnitCostInfo' | 'SharedFigurineSprites' | 'MapSelectSprites' | 'ArcadeSelectSmallSprites' | 'ArcadeSelectUnitNameSprites' | 'CameraConfigs' | 'CommonEffects' | 'CommonEffectParticles' | 'CosmeticInfo' | 'TextStrings' | 'SeriesLogoSprites' | 'SeriesLogoSprites2';

export type AssetFileVm = {
    hash: number | string;
    order?: number | string;
    fileType?: Array<AssetFileType>;
    unitIds?: Array<number | string>;
};

export type BulkCreateUnitCommand = {
    units: Array<UnitSummaryVm>;
};

export type CompileScexByPathCommand = {
    sourcePath: string;
    destinationPath: string;
    fileName?: null | string;
    hotReload?: boolean;
};

export type CompileScexByUnitsCommand = {
    unitIds: Array<number | string>;
    replaceWorking?: boolean;
    hotReload?: boolean;
};

export type CompressionFormats = 'Zip' | 'Tar';

export type ConfigDto = {
    key: string;
    value: string;
};

export type CreateAmmoCommand = {
    ammoType?: number | string;
    maxAmmo?: number | string;
    initialAmmo?: number | string;
    timedDurationFrame?: number | string;
    unk16?: number | string;
    reloadType?: number | string;
    cooldownDurationFrame?: number | string;
    reloadDurationFrame?: number | string;
    assaultBurstReloadDurationFrame?: number | string;
    blastBurstReloadDurationFrame?: number | string;
    unk40?: number | string;
    unk44?: number | string;
    inactiveUnk48?: number | string;
    inactiveCooldownDurationFrame?: number | string;
    inactiveReloadDurationFrame?: number | string;
    inactiveAssaultBurstReloadDurationFrame?: number | string;
    inactiveBlastBurstReloadDurationFrame?: number | string;
    inactiveUnk68?: number | string;
    inactiveUnk72?: number | string;
    burstReplenish?: number | string;
    unk80?: number | string;
    unk84?: number | string;
    unk88?: number | string;
    chargeInput?: number | string;
    chargeDurationFrame?: number | string;
    assaultBurstChargeDurationFrame?: number | string;
    blastBurstChargeDurationFrame?: number | string;
    unk108?: number | string;
    unk112?: number | string;
    releaseChargeLingerDurationFrame?: number | string;
    maxChargeLevel?: number | string;
    unk124?: number | string;
    chargeMultiLockFlag?: number | string;
    order?: number | string;
    unitId?: null | number | string;
};

export type CreateAssetFileCommand = {
    order?: number | string;
    fileType?: Array<AssetFileType>;
    unitIds?: Array<number | string>;
};

export type CreateHitboxCommand = {
    hitboxType?: number | string;
    damage?: number | string;
    unk8?: number | string;
    downValueThreshold?: number | string;
    yorukeValueThreshold?: number | string;
    unk20?: number | string;
    unk24?: number | string;
    damageCorrection?: number | string;
    specialEffect?: number | string;
    hitEffect?: number | string;
    flyDirection1?: number | string;
    flyDirection2?: number | string;
    flyDirection3?: number | string;
    enemyCameraShakeMultiplier?: number | string;
    playerCameraShakeMultiplier?: number | string;
    unk56?: number | string;
    knockUpAngle?: number | string;
    knockUpRange?: number | string;
    unk68?: number | string;
    multipleHitIntervalFrame?: number | string;
    multipleHitCount?: number | string;
    enemyStunDuration?: number | string;
    playerStunDuration?: number | string;
    hitVisualEffect?: number | string;
    hitVisualEffectSizeMultiplier?: number | string;
    hitSoundEffectHash?: number | string;
    unk100?: number | string;
    friendlyDamageFlag?: number | string;
    unk108?: number | string;
    hitboxGroupHash?: number | string;
};

export type CreateHitboxGroupCommand = {
    hash: number | string;
    unitIds?: null | Array<number | string>;
};

export type CreatePatchFileCommand = {
    tblId: PatchFileVersion;
    pathInfo?: PathInfoDto;
    fileInfo?: FileInfoDto;
    assetFileHash?: null | number | string;
};

export type CreateProjectileCommand = {
    projectileType?: number | string;
    hitboxHash?: null | number | string;
    modelHash?: number | string;
    skeletonIndex?: number | string;
    aimType?: number | string;
    translateY?: number | string;
    translateZ?: number | string;
    translateX?: number | string;
    rotateX?: number | string;
    rotateZ?: number | string;
    cosmeticHash?: number | string;
    unk44?: number | string;
    unk48?: number | string;
    unk52?: number | string;
    unk56?: number | string;
    ammoConsumption?: number | string;
    durationFrame?: number | string;
    maxTravelDistance?: number | string;
    initialSpeed?: number | string;
    acceleration?: number | string;
    accelerationStartFrame?: number | string;
    unk84?: number | string;
    maxSpeed?: number | string;
    reserved92?: number | string;
    reserved96?: number | string;
    reserved100?: number | string;
    reserved104?: number | string;
    reserved108?: number | string;
    reserved112?: number | string;
    reserved116?: number | string;
    horizontalGuidance?: number | string;
    horizontalGuidanceAngle?: number | string;
    verticalGuidance?: number | string;
    verticalGuidanceAngle?: number | string;
    reserved136?: number | string;
    reserved140?: number | string;
    reserved144?: number | string;
    reserved148?: number | string;
    reserved152?: number | string;
    reserved156?: number | string;
    reserved160?: number | string;
    reserved164?: number | string;
    reserved168?: number | string;
    reserved172?: number | string;
    size?: number | string;
    reserved180?: number | string;
    reserved184?: number | string;
    soundEffectHash?: number | string;
    reserved192?: number | string;
    reserved196?: number | string;
    chainedProjectileHash?: number | string;
    reserved204?: number | string;
    reserved208?: number | string;
    reserved212?: number | string;
    reserved216?: number | string;
    reserved220?: number | string;
    reserved224?: number | string;
    reserved228?: number | string;
    reserved232?: number | string;
    reserved236?: number | string;
    reserved240?: number | string;
    reserved244?: number | string;
    reserved248?: number | string;
    reserved252?: number | string;
    reserved256?: number | string;
    reserved260?: number | string;
    reserved264?: number | string;
    reserved268?: number | string;
    reserved272?: number | string;
    reserved276?: number | string;
    unitId?: null | number | string;
};

export type CreateSeriesCommand = {
    id?: number | string;
    playableSeries?: PlayableSeriesDetailsDto;
    slugName?: string;
    nameEnglish?: null | string;
    nameJapanese?: null | string;
    nameChinese?: null | string;
};

export type CreateStatCommand = {
    unitCost?: number | string;
    unitCost2?: number | string;
    maxHp?: number | string;
    downValueThreshold?: number | string;
    yorukeValueThreshold?: number | string;
    unk20?: number | string;
    unk24?: number | string;
    unk28?: number | string;
    maxBoost?: number | string;
    unk36?: number | string;
    unk40?: number | string;
    unk44?: number | string;
    gravityMultiplierAir?: number | string;
    gravityMultiplierLand?: number | string;
    unk56?: number | string;
    unk60?: number | string;
    unk64?: number | string;
    unk68?: number | string;
    unk72?: number | string;
    unk76?: number | string;
    unk80?: number | string;
    cameraZoomMultiplier?: number | string;
    unk88?: number | string;
    unk92?: number | string;
    unk96?: number | string;
    unk100?: number | string;
    unk104?: number | string;
    unk108?: number | string;
    sizeMultiplier?: number | string;
    unk116?: number | string;
    unk120?: number | string;
    unk124?: number | string;
    unk128?: number | string;
    unk132?: number | string;
    unk136?: number | string;
    unk140?: number | string;
    unk144?: number | string;
    unk148?: number | string;
    unk152?: number | string;
    unk156?: number | string;
    unk160?: number | string;
    unk164?: number | string;
    unk168?: number | string;
    unk172?: number | string;
    unk176?: number | string;
    unk180?: number | string;
    unk184?: number | string;
    redLockRangeMelee?: number | string;
    redLockRange?: number | string;
    unk196?: number | string;
    unk200?: number | string;
    unk204?: number | string;
    unk208?: number | string;
    boostReplenish?: number | string;
    unk216?: number | string;
    boostInitialConsumption?: number | string;
    boostFuwaInitialConsumption?: number | string;
    boostFlyConsumption?: number | string;
    boostGroundStepInitialConsumption?: number | string;
    boostGroundStepConsumption?: number | string;
    boostAirStepInitialConsumption?: number | string;
    boostAirStepConsumption?: number | string;
    boostBdInitialConsumption?: number | string;
    boostBdConsumption?: number | string;
    unk256?: number | string;
    unk260?: number | string;
    unk264?: number | string;
    unk268?: number | string;
    boostTransformInitialConsumption?: number | string;
    boostTransformConsumption?: number | string;
    boostNonVernierActionConsumption?: number | string;
    boostPostActionConsumption?: number | string;
    boostRainbowStepInitialConsumption?: number | string;
    unk292?: number | string;
    unk296?: number | string;
    unk300?: number | string;
    unk304?: number | string;
    unk308?: number | string;
    unk312?: number | string;
    unk316?: number | string;
    unk320?: number | string;
    unk324?: number | string;
    unk328?: number | string;
    unk332?: number | string;
    assaultBurstRedLockMelee?: number | string;
    assaultBurstRedLock?: number | string;
    assaultBurstDamageDealtMultiplier?: number | string;
    assaultBurstDamageTakenMultiplier?: number | string;
    assaultBurstMobilityMultiplier?: number | string;
    assaultBurstDownValueDealtMultiplier?: number | string;
    assaultBurstBoostConsumptionMultiplier?: number | string;
    unk364?: number | string;
    unk368?: number | string;
    assaultBurstDamageDealtBurstGaugeIncreaseMultiplier?: number | string;
    assaultBurstDamageTakenBurstGaugeIncreaseMultiplier?: number | string;
    unk380?: number | string;
    unk384?: number | string;
    unk388?: number | string;
    unk392?: number | string;
    unk396?: number | string;
    blastBurstRedLockMelee?: number | string;
    blastBurstRedLock?: number | string;
    blastBurstDamageDealtMultiplier?: number | string;
    blastBurstDamageTakenMultiplier?: number | string;
    blastBurstMobilityMultiplier?: number | string;
    blastBurstDownValueDealtMultiplier?: number | string;
    blastBurstBoostConsumptionMultiplier?: number | string;
    unk428?: number | string;
    unk432?: number | string;
    blastBurstDamageDealtBurstGaugeIncreaseMultiplier?: number | string;
    blastBurstDamageTakenBurstGaugeIncreaseMultiplier?: number | string;
    unk444?: number | string;
    unk448?: number | string;
    unk452?: number | string;
    unk456?: number | string;
    unk460?: number | string;
    thirdBurstRedLockMelee?: number | string;
    thirdBurstRedLock?: number | string;
    thirdBurstDamageDealtMultiplier?: number | string;
    thirdBurstDamageTakenMultiplier?: number | string;
    thirdBurstMobilityMultiplier?: number | string;
    thirdBurstDownValueDealtMultiplier?: number | string;
    thirdBurstBoostConsumptionMultiplier?: number | string;
    unk492?: number | string;
    unk496?: number | string;
    thirdBurstDamageDealtBurstGaugeIncreaseMultiplier?: number | string;
    thirdBurstDamageTakenBurstGaugeIncreaseMultiplier?: number | string;
    unk508?: number | string;
    unk512?: number | string;
    unk516?: number | string;
    unk520?: number | string;
    unk524?: number | string;
    fourthBurstRedLockMelee?: number | string;
    fourthBurstRedLock?: number | string;
    fourthBurstDamageDealtMultiplier?: number | string;
    fourthBurstDamageTakenMultiplier?: number | string;
    fourthBurstMobilityMultiplier?: number | string;
    fourthBurstDownValueDealtMultiplier?: number | string;
    fourthBurstBoostConsumptionMultiplier?: number | string;
    unk572?: number | string;
    unk576?: number | string;
    fourthBurstDamageDealtBurstGaugeIncreaseMultiplier?: number | string;
    fourthBurstDamageTakenBurstGaugeIncreaseMultiplier?: number | string;
    unk588?: number | string;
    unk592?: number | string;
    unk596?: number | string;
    unk600?: number | string;
    unk604?: number | string;
    unk608?: number | string;
    order?: number | string;
    unitId?: null | number | string;
};

export type CreateUnitAmmoSlotCommand = {
    ammoHash: number | string;
    unitId: number | string;
    slotOrder: number | string;
};

export type CreateUnitCommand = {
    unitId?: number | string;
    slugName?: null | string;
    nameEnglish?: null | string;
    nameJapanese?: null | string;
    nameChinese?: null | string;
    seriesId?: null | number | string;
    series?: SeriesVm;
};

export type DebugCommand = {
    [key: string]: unknown;
};

export type DecompileScexByPathCommand = {
    sourcePath: string;
    destinationPath: string;
    fileName?: null | string;
};

export type DecompileScexByUnitsCommand = {
    unitIds: Array<number | string>;
    replaceScript?: boolean;
};

export type ExportAmmoByPathCommand = {
    exportPath?: null | string;
};

export type ExportAmmoCommand = {
    replaceWorking?: boolean;
    hotReload?: boolean;
};

export type ExportHitboxGroupByPathCommand = {
    hashes?: null | Array<number | string>;
    unitIds?: null | Array<number | string>;
    outputPath?: null | string;
};

export type ExportHitboxGroupCommand = {
    hashes?: null | Array<number | string>;
    unitIds?: null | Array<number | string>;
    replaceWorking?: boolean;
    hotReload?: boolean;
};

export type ExportPlayableCharactersCommand = {
    replaceWorking?: boolean;
};

export type ExportPlayableSeriesCommand = {
    replaceWorking?: boolean;
};

export type ExportTblCommand = {
    versions?: null | Array<PatchFileVersion>;
    replaceStaging?: boolean;
};

export type ExportUnitProjectileByPathCommand = {
    unitIds?: null | Array<number | string>;
    exportPath?: null | string;
};

export type ExportUnitProjectileCommand = {
    unitIds?: null | Array<number | string>;
    replaceWorking?: boolean;
    hotReload?: boolean;
};

export type ExportUnitStatByPathCommand = {
    unitIds?: null | Array<number | string>;
    exportPath?: null | string;
};

export type ExportUnitStatCommand = {
    unitIds?: null | Array<number | string>;
    replaceWorking?: boolean;
};

export type FileContentHttpResult = Blob | File;

export type FileInfoDto = null | {
    version: PatchFileVersion;
    size1: number | string;
    size2: number | string;
    size3: number | string;
    size4: number | string;
};

export type GetUnitSummaryQueryIncludes = 'Series';

export type HitboxDto = {
    hash?: number | string;
    hitboxType?: number | string;
    damage?: number | string;
    unk8?: number | string;
    downValueThreshold?: number | string;
    yorukeValueThreshold?: number | string;
    unk20?: number | string;
    unk24?: number | string;
    damageCorrection?: number | string;
    specialEffect?: number | string;
    hitEffect?: number | string;
    flyDirection1?: number | string;
    flyDirection2?: number | string;
    flyDirection3?: number | string;
    enemyCameraShakeMultiplier?: number | string;
    playerCameraShakeMultiplier?: number | string;
    unk56?: number | string;
    knockUpAngle?: number | string;
    knockUpRange?: number | string;
    unk68?: number | string;
    multipleHitIntervalFrame?: number | string;
    multipleHitCount?: number | string;
    enemyStunDuration?: number | string;
    playerStunDuration?: number | string;
    hitVisualEffect?: number | string;
    hitVisualEffectSizeMultiplier?: number | string;
    hitSoundEffectHash?: number | string;
    unk100?: number | string;
    friendlyDamageFlag?: number | string;
    unk108?: number | string;
    hitboxGroupHash?: number | string;
};

export type HitboxGroupDto = {
    hash?: number | string;
    unitIds?: Array<number | string>;
    hitboxes?: Array<HitboxDto>;
};

export type HotReloadScex = {
    sourcePath: string;
};

export type IFormFile = Blob | File;

export type IFormFileCollection = Array<IFormFile>;

export type LanguageSettings = 'English' | 'Japanese' | 'Chinese';

export type NullableOfCompressionType = 'None' | 'Zlib' | 'Lzma';

export type PackFhmByAssetCommand = {
    assetFileHashes?: null | Array<number | string>;
    assetFileTypes?: null | Array<AssetFileType>;
    unitIds?: null | Array<number | string>;
    patchFileVersions?: null | Array<PatchFileVersion>;
    replaceStaging?: boolean;
};

export type PackPsarcByPatchFilesCommand = {
    patchFileVersions?: null | Array<PatchFileVersion>;
};

export type PackPsarcByPathCommand = {
    sourcePath: string;
    destinationPath: string;
    filename?: null | string;
    compressionType?: NullableOfCompressionType;
    compressionLevel?: null | number | string;
};

export type PaginatedListOfAmmoDto = {
    items: Array<AmmoDto>;
    pageNumber: number | string;
    totalPages?: number | string;
    totalCount: number | string;
    hasPreviousPage?: boolean;
    hasNextPage?: boolean;
};

export type PaginatedListOfAssetFileVm = {
    items: Array<AssetFileVm>;
    pageNumber: number | string;
    totalPages?: number | string;
    totalCount: number | string;
    hasPreviousPage?: boolean;
    hasNextPage?: boolean;
};

export type PaginatedListOfHitboxDto = {
    items: Array<HitboxDto>;
    pageNumber: number | string;
    totalPages?: number | string;
    totalCount: number | string;
    hasPreviousPage?: boolean;
    hasNextPage?: boolean;
};

export type PaginatedListOfHitboxGroupDto = {
    items: Array<HitboxGroupDto>;
    pageNumber: number | string;
    totalPages?: number | string;
    totalCount: number | string;
    hasPreviousPage?: boolean;
    hasNextPage?: boolean;
};

export type PaginatedListOfPatchFileSummaryVm = {
    items: Array<PatchFileSummaryVm>;
    pageNumber: number | string;
    totalPages?: number | string;
    totalCount: number | string;
    hasPreviousPage?: boolean;
    hasNextPage?: boolean;
};

export type PaginatedListOfPatchFileVm = {
    items: Array<PatchFileVm>;
    pageNumber: number | string;
    totalPages?: number | string;
    totalCount: number | string;
    hasPreviousPage?: boolean;
    hasNextPage?: boolean;
};

export type PaginatedListOfProjectileDto = {
    items: Array<ProjectileDto>;
    pageNumber: number | string;
    totalPages?: number | string;
    totalCount: number | string;
    hasPreviousPage?: boolean;
    hasNextPage?: boolean;
};

export type PaginatedListOfSeriesDto = {
    items: Array<SeriesDto>;
    pageNumber: number | string;
    totalPages?: number | string;
    totalCount: number | string;
    hasPreviousPage?: boolean;
    hasNextPage?: boolean;
};

export type PaginatedListOfSeriesUnitsVm = {
    items: Array<SeriesUnitsVm>;
    pageNumber: number | string;
    totalPages?: number | string;
    totalCount: number | string;
    hasPreviousPage?: boolean;
    hasNextPage?: boolean;
};

export type PaginatedListOfStatDto = {
    items: Array<StatDto>;
    pageNumber: number | string;
    totalPages?: number | string;
    totalCount: number | string;
    hasPreviousPage?: boolean;
    hasNextPage?: boolean;
};

export type PaginatedListOfUnitProjectileDto = {
    items: Array<UnitProjectileDto>;
    pageNumber: number | string;
    totalPages?: number | string;
    totalCount: number | string;
    hasPreviousPage?: boolean;
    hasNextPage?: boolean;
};

export type PaginatedListOfUnitStatDto = {
    items: Array<UnitStatDto>;
    pageNumber: number | string;
    totalPages?: number | string;
    totalCount: number | string;
    hasPreviousPage?: boolean;
    hasNextPage?: boolean;
};

export type PaginatedListOfUnitSummaryVm = {
    items: Array<UnitSummaryVm>;
    pageNumber: number | string;
    totalPages?: number | string;
    totalCount: number | string;
    hasPreviousPage?: boolean;
    hasNextPage?: boolean;
};

export type PatchFileMetadataDto = {
    path?: null | string;
    fileInfoMetadata?: TblFileInfoMetadata;
};

export type PatchFileSummaryVm = {
    assetFile?: AssetFileDto;
    id: null | string;
    tblId: PatchFileVersion;
    pathInfo?: PathInfoDto;
    fileInfo?: FileInfoDto;
    assetFileHash?: null | number | string;
};

export type PatchFileVersion = 'Base' | 'Patch1' | 'Patch2' | 'Patch3' | 'Patch4' | 'Patch5' | 'Patch6';

export type PatchFileVm = {
    id: null | string;
    tblId: PatchFileVersion;
    pathInfo?: PathInfoDto;
    fileInfo?: FileInfoDto;
    assetFileHash?: null | number | string;
};

export type PathInfoDto = null | {
    path: string;
    order?: null | number | string;
};

export type PlayableCharacterDto = {
    unitId?: number | string;
    unitIndex?: number | string;
    seriesId?: number | string;
    unk2?: number | string;
    fString?: null | string;
    fOutString?: null | string;
    pString?: null | string;
    unitSelectOrderInSeries?: number | string;
    arcadeSmallSpriteIndex?: number | string;
    arcadeUnitNameSpriteIndex?: number | string;
    unk27?: number | string;
    unk112?: number | string;
    figurineSpriteIndex?: number | string;
    unk114?: number | string;
    unk124?: number | string;
    unk128?: number | string;
    catalogStorePilotCostume2TString?: null | string;
    catalogStorePilotCostume2String?: null | string;
    catalogStorePilotCostume3TString?: null | string;
    catalogStorePilotCostume3String?: null | string;
    unk156?: number | string;
    arcadeSelectionCostume1SpriteAssetHash?: number | string;
    arcadeSelectionCostume2SpriteAssetHash?: number | string;
    arcadeSelectionCostume3SpriteAssetHash?: number | string;
    loadingLeftCostume1SpriteAssetHash?: number | string;
    loadingLeftCostume2SpriteAssetHash?: number | string;
    loadingLeftCostume3SpriteAssetHash?: number | string;
    loadingRightCostume1SpriteAssetHash?: number | string;
    loadingRightCostume2SpriteAssetHash?: number | string;
    loadingRightCostume3SpriteAssetHash?: number | string;
    genericSelectionCostume1SpriteAssetHash?: number | string;
    genericSelectionCostume2SpriteAssetHash?: number | string;
    genericSelectionCostume3SpriteAssetHash?: number | string;
    loadingTargetUnitSpriteAssetHash?: number | string;
    loadingTargetPilotCostume1SpriteAssetHash?: number | string;
    loadingTargetPilotCostume2SpriteAssetHash?: number | string;
    loadingTargetPilotCostume3SpriteAssetHash?: number | string;
    inGameSortieAndAwakeningPilotCostume1SpriteAssetHash?: number | string;
    inGameSortieAndAwakeningPilotCostume2SpriteAssetHash?: number | string;
    inGameSortieAndAwakeningPilotCostume3SpriteAssetHash?: number | string;
    spriteFramesAssetHash?: number | string;
    resultSmallUnitSpriteAssetHash?: number | string;
    figurineSpriteAssetHash?: number | string;
    loadingTargetUnitSmallSpriteAssetHash?: number | string;
    catalogStorePilotCostume2SpriteAssetHash?: number | string;
    catalogStorePilotCostume3SpriteAssetHash?: number | string;
};

export type PlayableSeriesDetailsDto = null | {
    unk2?: number | string;
    unk3?: number | string;
    unk4?: number | string;
    selectOrder?: number | string;
    logoSpriteIndex?: number | string;
    logoSprite2Index?: number | string;
    unk11?: number | string;
    movieAssetHash?: null | number | string;
};

export type ProjectileDto = {
    hash?: number | string;
    projectileType?: number | string;
    hitboxHash?: null | number | string;
    modelHash?: number | string;
    skeletonIndex?: number | string;
    aimType?: number | string;
    translateY?: number | string;
    translateZ?: number | string;
    translateX?: number | string;
    rotateX?: number | string;
    rotateZ?: number | string;
    cosmeticHash?: number | string;
    unk44?: number | string;
    unk48?: number | string;
    unk52?: number | string;
    unk56?: number | string;
    ammoConsumption?: number | string;
    durationFrame?: number | string;
    maxTravelDistance?: number | string;
    initialSpeed?: number | string;
    acceleration?: number | string;
    accelerationStartFrame?: number | string;
    unk84?: number | string;
    maxSpeed?: number | string;
    reserved92?: number | string;
    reserved96?: number | string;
    reserved100?: number | string;
    reserved104?: number | string;
    reserved108?: number | string;
    reserved112?: number | string;
    reserved116?: number | string;
    horizontalGuidance?: number | string;
    horizontalGuidanceAngle?: number | string;
    verticalGuidance?: number | string;
    verticalGuidanceAngle?: number | string;
    reserved136?: number | string;
    reserved140?: number | string;
    reserved144?: number | string;
    reserved148?: number | string;
    reserved152?: number | string;
    reserved156?: number | string;
    reserved160?: number | string;
    reserved164?: number | string;
    reserved168?: number | string;
    reserved172?: number | string;
    size?: number | string;
    reserved180?: number | string;
    reserved184?: number | string;
    soundEffectHash?: number | string;
    reserved192?: number | string;
    reserved196?: number | string;
    chainedProjectileHash?: number | string;
    reserved204?: number | string;
    reserved208?: number | string;
    reserved212?: number | string;
    reserved216?: number | string;
    reserved220?: number | string;
    reserved224?: number | string;
    reserved228?: number | string;
    reserved232?: number | string;
    reserved236?: number | string;
    reserved240?: number | string;
    reserved244?: number | string;
    reserved248?: number | string;
    reserved252?: number | string;
    reserved256?: number | string;
    reserved260?: number | string;
    reserved264?: number | string;
    reserved268?: number | string;
    reserved272?: number | string;
    reserved276?: number | string;
    unitId?: null | number | string;
};

export type ResizePatchFileCommand = {
    ids?: null | Array<string>;
    versions?: null | Array<PatchFileVersion>;
    unitIds?: null | Array<number | string>;
    assetFileTypes?: null | Array<AssetFileType>;
};

export type SerializeTblCommand = {
    cumulativeFileInfoCount: number | string;
    fileMetadata: Array<PatchFileMetadataDto>;
    pathOrder?: null | Array<string>;
};

export type SeriesDto = {
    id?: number | string;
    playableSeries?: PlayableSeriesDetailsDto;
    slugName?: string;
    nameEnglish?: null | string;
    nameJapanese?: null | string;
    nameChinese?: null | string;
};

export type SeriesUnitsVm = {
    units?: Array<UnitSummaryVm>;
    id?: number | string;
    slugName?: string;
    nameEnglish?: null | string;
    nameJapanese?: null | string;
    nameChinese?: null | string;
};

export type SeriesVm = null | {
    id?: number | string;
    slugName?: string;
    nameEnglish?: null | string;
    nameJapanese?: null | string;
    nameChinese?: null | string;
};

export type StatDto = {
    id?: string;
    unitCost?: number | string;
    unitCost2?: number | string;
    maxHp?: number | string;
    downValueThreshold?: number | string;
    yorukeValueThreshold?: number | string;
    unk20?: number | string;
    unk24?: number | string;
    unk28?: number | string;
    maxBoost?: number | string;
    unk36?: number | string;
    unk40?: number | string;
    unk44?: number | string;
    gravityMultiplierAir?: number | string;
    gravityMultiplierLand?: number | string;
    unk56?: number | string;
    unk60?: number | string;
    unk64?: number | string;
    unk68?: number | string;
    unk72?: number | string;
    unk76?: number | string;
    unk80?: number | string;
    cameraZoomMultiplier?: number | string;
    unk88?: number | string;
    unk92?: number | string;
    unk96?: number | string;
    unk100?: number | string;
    unk104?: number | string;
    unk108?: number | string;
    sizeMultiplier?: number | string;
    unk116?: number | string;
    unk120?: number | string;
    unk124?: number | string;
    unk128?: number | string;
    unk132?: number | string;
    unk136?: number | string;
    unk140?: number | string;
    unk144?: number | string;
    unk148?: number | string;
    unk152?: number | string;
    unk156?: number | string;
    unk160?: number | string;
    unk164?: number | string;
    unk168?: number | string;
    unk172?: number | string;
    unk176?: number | string;
    unk180?: number | string;
    unk184?: number | string;
    redLockRangeMelee?: number | string;
    redLockRange?: number | string;
    unk196?: number | string;
    unk200?: number | string;
    unk204?: number | string;
    unk208?: number | string;
    boostReplenish?: number | string;
    unk216?: number | string;
    boostInitialConsumption?: number | string;
    boostFuwaInitialConsumption?: number | string;
    boostFlyConsumption?: number | string;
    boostGroundStepInitialConsumption?: number | string;
    boostGroundStepConsumption?: number | string;
    boostAirStepInitialConsumption?: number | string;
    boostAirStepConsumption?: number | string;
    boostBdInitialConsumption?: number | string;
    boostBdConsumption?: number | string;
    unk256?: number | string;
    unk260?: number | string;
    unk264?: number | string;
    unk268?: number | string;
    boostTransformInitialConsumption?: number | string;
    boostTransformConsumption?: number | string;
    boostNonVernierActionConsumption?: number | string;
    boostPostActionConsumption?: number | string;
    boostRainbowStepInitialConsumption?: number | string;
    unk292?: number | string;
    unk296?: number | string;
    unk300?: number | string;
    unk304?: number | string;
    unk308?: number | string;
    unk312?: number | string;
    unk316?: number | string;
    unk320?: number | string;
    unk324?: number | string;
    unk328?: number | string;
    unk332?: number | string;
    assaultBurstRedLockMelee?: number | string;
    assaultBurstRedLock?: number | string;
    assaultBurstDamageDealtMultiplier?: number | string;
    assaultBurstDamageTakenMultiplier?: number | string;
    assaultBurstMobilityMultiplier?: number | string;
    assaultBurstDownValueDealtMultiplier?: number | string;
    assaultBurstBoostConsumptionMultiplier?: number | string;
    unk364?: number | string;
    unk368?: number | string;
    assaultBurstDamageDealtBurstGaugeIncreaseMultiplier?: number | string;
    assaultBurstDamageTakenBurstGaugeIncreaseMultiplier?: number | string;
    unk380?: number | string;
    unk384?: number | string;
    unk388?: number | string;
    unk392?: number | string;
    unk396?: number | string;
    blastBurstRedLockMelee?: number | string;
    blastBurstRedLock?: number | string;
    blastBurstDamageDealtMultiplier?: number | string;
    blastBurstDamageTakenMultiplier?: number | string;
    blastBurstMobilityMultiplier?: number | string;
    blastBurstDownValueDealtMultiplier?: number | string;
    blastBurstBoostConsumptionMultiplier?: number | string;
    unk428?: number | string;
    unk432?: number | string;
    blastBurstDamageDealtBurstGaugeIncreaseMultiplier?: number | string;
    blastBurstDamageTakenBurstGaugeIncreaseMultiplier?: number | string;
    unk444?: number | string;
    unk448?: number | string;
    unk452?: number | string;
    unk456?: number | string;
    unk460?: number | string;
    thirdBurstRedLockMelee?: number | string;
    thirdBurstRedLock?: number | string;
    thirdBurstDamageDealtMultiplier?: number | string;
    thirdBurstDamageTakenMultiplier?: number | string;
    thirdBurstMobilityMultiplier?: number | string;
    thirdBurstDownValueDealtMultiplier?: number | string;
    thirdBurstBoostConsumptionMultiplier?: number | string;
    unk492?: number | string;
    unk496?: number | string;
    thirdBurstDamageDealtBurstGaugeIncreaseMultiplier?: number | string;
    thirdBurstDamageTakenBurstGaugeIncreaseMultiplier?: number | string;
    unk508?: number | string;
    unk512?: number | string;
    unk516?: number | string;
    unk520?: number | string;
    unk524?: number | string;
    fourthBurstRedLockMelee?: number | string;
    fourthBurstRedLock?: number | string;
    fourthBurstDamageDealtMultiplier?: number | string;
    fourthBurstDamageTakenMultiplier?: number | string;
    fourthBurstMobilityMultiplier?: number | string;
    fourthBurstDownValueDealtMultiplier?: number | string;
    fourthBurstBoostConsumptionMultiplier?: number | string;
    unk572?: number | string;
    unk576?: number | string;
    fourthBurstDamageDealtBurstGaugeIncreaseMultiplier?: number | string;
    fourthBurstDamageTakenBurstGaugeIncreaseMultiplier?: number | string;
    unk588?: number | string;
    unk592?: number | string;
    unk596?: number | string;
    unk600?: number | string;
    unk604?: number | string;
    unk608?: number | string;
    order?: number | string;
    unitId?: null | number | string;
};

export type TblDto = {
    cumulativeFileInfoCount: number | string;
    fileMetadata: Array<PatchFileMetadataDto>;
    pathOrder?: null | Array<string>;
};

export type TblFileInfoMetadata = null | {
    cumulativeIndex: number | string;
    patchNumber: number | string;
    size1: number | string;
    size2: number | string;
    size3: number | string;
    size4: number | string;
    hashName: number | string;
};

export type TblVm = {
    id: string;
    cumulativeAssetIndex?: number | string;
};

export type UnitAmmoSlotDto = {
    id?: null | string;
    slotOrder?: number | string;
    ammoHash?: number | string;
};

export type UnitProjectileDto = {
    unitId?: number | string;
    projectiles?: Array<ProjectileDto>;
};

export type UnitStatDto = {
    id?: null | string;
    unitId?: number | string;
    ammoSlots?: Array<UnitAmmoSlotDto>;
};

export type UnitSummaryVm = {
    unitId?: number | string;
    slugName?: null | string;
    nameEnglish?: null | string;
    nameJapanese?: null | string;
    nameChinese?: null | string;
    seriesId?: null | number | string;
    series?: SeriesVm;
};

export type UnpackFhmByAssetCommand = {
    assetFileHashes?: null | Array<number | string>;
    assetFileTypes?: null | Array<AssetFileType>;
    unitIds?: null | Array<number | string>;
    patchFileVersions?: null | Array<PatchFileVersion>;
    replaceWorking?: boolean;
};

export type UnpackPsarcByPatchFilesCommand = {
    patchFileVersions?: null | Array<PatchFileVersion>;
};

export type UnpackPsarcByPathCommand = {
    sourceFilePath: string;
    outputDirectoryPath: string;
};

export type UpdateAmmoCommand = {
    hash: number | string;
    ammoType?: number | string;
    maxAmmo?: number | string;
    initialAmmo?: number | string;
    timedDurationFrame?: number | string;
    unk16?: number | string;
    reloadType?: number | string;
    cooldownDurationFrame?: number | string;
    reloadDurationFrame?: number | string;
    assaultBurstReloadDurationFrame?: number | string;
    blastBurstReloadDurationFrame?: number | string;
    unk40?: number | string;
    unk44?: number | string;
    inactiveUnk48?: number | string;
    inactiveCooldownDurationFrame?: number | string;
    inactiveReloadDurationFrame?: number | string;
    inactiveAssaultBurstReloadDurationFrame?: number | string;
    inactiveBlastBurstReloadDurationFrame?: number | string;
    inactiveUnk68?: number | string;
    inactiveUnk72?: number | string;
    burstReplenish?: number | string;
    unk80?: number | string;
    unk84?: number | string;
    unk88?: number | string;
    chargeInput?: number | string;
    chargeDurationFrame?: number | string;
    assaultBurstChargeDurationFrame?: number | string;
    blastBurstChargeDurationFrame?: number | string;
    unk108?: number | string;
    unk112?: number | string;
    releaseChargeLingerDurationFrame?: number | string;
    maxChargeLevel?: number | string;
    unk124?: number | string;
    chargeMultiLockFlag?: number | string;
    order?: number | string;
    unitId?: null | number | string;
};

export type UpdateAssetFileByHashCommand = {
    hash: number | string;
    order?: number | string;
    fileType?: Array<AssetFileType>;
    unitIds?: Array<number | string>;
};

export type UpdateHitboxCommand = {
    hash: number | string;
    hitboxType?: number | string;
    damage?: number | string;
    unk8?: number | string;
    downValueThreshold?: number | string;
    yorukeValueThreshold?: number | string;
    unk20?: number | string;
    unk24?: number | string;
    damageCorrection?: number | string;
    specialEffect?: number | string;
    hitEffect?: number | string;
    flyDirection1?: number | string;
    flyDirection2?: number | string;
    flyDirection3?: number | string;
    enemyCameraShakeMultiplier?: number | string;
    playerCameraShakeMultiplier?: number | string;
    unk56?: number | string;
    knockUpAngle?: number | string;
    knockUpRange?: number | string;
    unk68?: number | string;
    multipleHitIntervalFrame?: number | string;
    multipleHitCount?: number | string;
    enemyStunDuration?: number | string;
    playerStunDuration?: number | string;
    hitVisualEffect?: number | string;
    hitVisualEffectSizeMultiplier?: number | string;
    hitSoundEffectHash?: number | string;
    unk100?: number | string;
    friendlyDamageFlag?: number | string;
    unk108?: number | string;
    hitboxGroupHash?: number | string;
};

export type UpdateHitboxGroupCommand = {
    hash: number | string;
    unitIds?: null | Array<number | string>;
};

export type UpdatePatchFileByIdCommand = {
    id: string;
    tblId: PatchFileVersion;
    pathInfo?: PathInfoDto;
    fileInfo?: FileInfoDto;
    assetFileHash?: null | number | string;
};

export type UpdateProjectileByIdCommand = {
    hash: number | string;
    projectileType?: number | string;
    hitboxHash?: null | number | string;
    modelHash?: number | string;
    skeletonIndex?: number | string;
    aimType?: number | string;
    translateY?: number | string;
    translateZ?: number | string;
    translateX?: number | string;
    rotateX?: number | string;
    rotateZ?: number | string;
    cosmeticHash?: number | string;
    unk44?: number | string;
    unk48?: number | string;
    unk52?: number | string;
    unk56?: number | string;
    ammoConsumption?: number | string;
    durationFrame?: number | string;
    maxTravelDistance?: number | string;
    initialSpeed?: number | string;
    acceleration?: number | string;
    accelerationStartFrame?: number | string;
    unk84?: number | string;
    maxSpeed?: number | string;
    reserved92?: number | string;
    reserved96?: number | string;
    reserved100?: number | string;
    reserved104?: number | string;
    reserved108?: number | string;
    reserved112?: number | string;
    reserved116?: number | string;
    horizontalGuidance?: number | string;
    horizontalGuidanceAngle?: number | string;
    verticalGuidance?: number | string;
    verticalGuidanceAngle?: number | string;
    reserved136?: number | string;
    reserved140?: number | string;
    reserved144?: number | string;
    reserved148?: number | string;
    reserved152?: number | string;
    reserved156?: number | string;
    reserved160?: number | string;
    reserved164?: number | string;
    reserved168?: number | string;
    reserved172?: number | string;
    size?: number | string;
    reserved180?: number | string;
    reserved184?: number | string;
    soundEffectHash?: number | string;
    reserved192?: number | string;
    reserved196?: number | string;
    chainedProjectileHash?: number | string;
    reserved204?: number | string;
    reserved208?: number | string;
    reserved212?: number | string;
    reserved216?: number | string;
    reserved220?: number | string;
    reserved224?: number | string;
    reserved228?: number | string;
    reserved232?: number | string;
    reserved236?: number | string;
    reserved240?: number | string;
    reserved244?: number | string;
    reserved248?: number | string;
    reserved252?: number | string;
    reserved256?: number | string;
    reserved260?: number | string;
    reserved264?: number | string;
    reserved268?: number | string;
    reserved272?: number | string;
    reserved276?: number | string;
    unitId?: null | number | string;
};

export type UpdateStatCommand = {
    id: string;
    unitCost?: number | string;
    unitCost2?: number | string;
    maxHp?: number | string;
    downValueThreshold?: number | string;
    yorukeValueThreshold?: number | string;
    unk20?: number | string;
    unk24?: number | string;
    unk28?: number | string;
    maxBoost?: number | string;
    unk36?: number | string;
    unk40?: number | string;
    unk44?: number | string;
    gravityMultiplierAir?: number | string;
    gravityMultiplierLand?: number | string;
    unk56?: number | string;
    unk60?: number | string;
    unk64?: number | string;
    unk68?: number | string;
    unk72?: number | string;
    unk76?: number | string;
    unk80?: number | string;
    cameraZoomMultiplier?: number | string;
    unk88?: number | string;
    unk92?: number | string;
    unk96?: number | string;
    unk100?: number | string;
    unk104?: number | string;
    unk108?: number | string;
    sizeMultiplier?: number | string;
    unk116?: number | string;
    unk120?: number | string;
    unk124?: number | string;
    unk128?: number | string;
    unk132?: number | string;
    unk136?: number | string;
    unk140?: number | string;
    unk144?: number | string;
    unk148?: number | string;
    unk152?: number | string;
    unk156?: number | string;
    unk160?: number | string;
    unk164?: number | string;
    unk168?: number | string;
    unk172?: number | string;
    unk176?: number | string;
    unk180?: number | string;
    unk184?: number | string;
    redLockRangeMelee?: number | string;
    redLockRange?: number | string;
    unk196?: number | string;
    unk200?: number | string;
    unk204?: number | string;
    unk208?: number | string;
    boostReplenish?: number | string;
    unk216?: number | string;
    boostInitialConsumption?: number | string;
    boostFuwaInitialConsumption?: number | string;
    boostFlyConsumption?: number | string;
    boostGroundStepInitialConsumption?: number | string;
    boostGroundStepConsumption?: number | string;
    boostAirStepInitialConsumption?: number | string;
    boostAirStepConsumption?: number | string;
    boostBdInitialConsumption?: number | string;
    boostBdConsumption?: number | string;
    unk256?: number | string;
    unk260?: number | string;
    unk264?: number | string;
    unk268?: number | string;
    boostTransformInitialConsumption?: number | string;
    boostTransformConsumption?: number | string;
    boostNonVernierActionConsumption?: number | string;
    boostPostActionConsumption?: number | string;
    boostRainbowStepInitialConsumption?: number | string;
    unk292?: number | string;
    unk296?: number | string;
    unk300?: number | string;
    unk304?: number | string;
    unk308?: number | string;
    unk312?: number | string;
    unk316?: number | string;
    unk320?: number | string;
    unk324?: number | string;
    unk328?: number | string;
    unk332?: number | string;
    assaultBurstRedLockMelee?: number | string;
    assaultBurstRedLock?: number | string;
    assaultBurstDamageDealtMultiplier?: number | string;
    assaultBurstDamageTakenMultiplier?: number | string;
    assaultBurstMobilityMultiplier?: number | string;
    assaultBurstDownValueDealtMultiplier?: number | string;
    assaultBurstBoostConsumptionMultiplier?: number | string;
    unk364?: number | string;
    unk368?: number | string;
    assaultBurstDamageDealtBurstGaugeIncreaseMultiplier?: number | string;
    assaultBurstDamageTakenBurstGaugeIncreaseMultiplier?: number | string;
    unk380?: number | string;
    unk384?: number | string;
    unk388?: number | string;
    unk392?: number | string;
    unk396?: number | string;
    blastBurstRedLockMelee?: number | string;
    blastBurstRedLock?: number | string;
    blastBurstDamageDealtMultiplier?: number | string;
    blastBurstDamageTakenMultiplier?: number | string;
    blastBurstMobilityMultiplier?: number | string;
    blastBurstDownValueDealtMultiplier?: number | string;
    blastBurstBoostConsumptionMultiplier?: number | string;
    unk428?: number | string;
    unk432?: number | string;
    blastBurstDamageDealtBurstGaugeIncreaseMultiplier?: number | string;
    blastBurstDamageTakenBurstGaugeIncreaseMultiplier?: number | string;
    unk444?: number | string;
    unk448?: number | string;
    unk452?: number | string;
    unk456?: number | string;
    unk460?: number | string;
    thirdBurstRedLockMelee?: number | string;
    thirdBurstRedLock?: number | string;
    thirdBurstDamageDealtMultiplier?: number | string;
    thirdBurstDamageTakenMultiplier?: number | string;
    thirdBurstMobilityMultiplier?: number | string;
    thirdBurstDownValueDealtMultiplier?: number | string;
    thirdBurstBoostConsumptionMultiplier?: number | string;
    unk492?: number | string;
    unk496?: number | string;
    thirdBurstDamageDealtBurstGaugeIncreaseMultiplier?: number | string;
    thirdBurstDamageTakenBurstGaugeIncreaseMultiplier?: number | string;
    unk508?: number | string;
    unk512?: number | string;
    unk516?: number | string;
    unk520?: number | string;
    unk524?: number | string;
    fourthBurstRedLockMelee?: number | string;
    fourthBurstRedLock?: number | string;
    fourthBurstDamageDealtMultiplier?: number | string;
    fourthBurstDamageTakenMultiplier?: number | string;
    fourthBurstMobilityMultiplier?: number | string;
    fourthBurstDownValueDealtMultiplier?: number | string;
    fourthBurstBoostConsumptionMultiplier?: number | string;
    unk572?: number | string;
    unk576?: number | string;
    fourthBurstDamageDealtBurstGaugeIncreaseMultiplier?: number | string;
    fourthBurstDamageTakenBurstGaugeIncreaseMultiplier?: number | string;
    unk588?: number | string;
    unk592?: number | string;
    unk596?: number | string;
    unk600?: number | string;
    unk604?: number | string;
    unk608?: number | string;
    order?: number | string;
    unitId?: null | number | string;
};

export type UpdateUnitAmmoSlotCommand = {
    id: string;
    unitId: number | string;
    slotOrder?: null | number | string;
    ammoHash?: null | number | string;
};

export type UpdateUnitCommand = {
    unitId?: number | string;
    slugName?: null | string;
    nameEnglish?: null | string;
    nameJapanese?: null | string;
    nameChinese?: null | string;
    seriesId?: null | number | string;
    series?: SeriesVm;
};

export type UpsertConfigCommand = {
    key: string;
    value: string;
};

export type UpsertPlayableCharacterCommand = {
    unitId: number | string;
    unitIndex?: number | string;
    seriesId?: number | string;
    unk2?: number | string;
    fString?: null | string;
    fOutString?: null | string;
    pString?: null | string;
    unitSelectOrderInSeries?: number | string;
    arcadeSmallSpriteIndex?: number | string;
    arcadeUnitNameSpriteIndex?: number | string;
    unk27?: number | string;
    unk112?: number | string;
    figurineSpriteIndex?: number | string;
    unk114?: number | string;
    unk124?: number | string;
    unk128?: number | string;
    catalogStorePilotCostume2TString?: null | string;
    catalogStorePilotCostume2String?: null | string;
    catalogStorePilotCostume3TString?: null | string;
    catalogStorePilotCostume3String?: null | string;
    unk156?: number | string;
    arcadeSelectionCostume1SpriteAssetHash?: number | string;
    arcadeSelectionCostume2SpriteAssetHash?: number | string;
    arcadeSelectionCostume3SpriteAssetHash?: number | string;
    loadingLeftCostume1SpriteAssetHash?: number | string;
    loadingLeftCostume2SpriteAssetHash?: number | string;
    loadingLeftCostume3SpriteAssetHash?: number | string;
    loadingRightCostume1SpriteAssetHash?: number | string;
    loadingRightCostume2SpriteAssetHash?: number | string;
    loadingRightCostume3SpriteAssetHash?: number | string;
    genericSelectionCostume1SpriteAssetHash?: number | string;
    genericSelectionCostume2SpriteAssetHash?: number | string;
    genericSelectionCostume3SpriteAssetHash?: number | string;
    loadingTargetUnitSpriteAssetHash?: number | string;
    loadingTargetPilotCostume1SpriteAssetHash?: number | string;
    loadingTargetPilotCostume2SpriteAssetHash?: number | string;
    loadingTargetPilotCostume3SpriteAssetHash?: number | string;
    inGameSortieAndAwakeningPilotCostume1SpriteAssetHash?: number | string;
    inGameSortieAndAwakeningPilotCostume2SpriteAssetHash?: number | string;
    inGameSortieAndAwakeningPilotCostume3SpriteAssetHash?: number | string;
    spriteFramesAssetHash?: number | string;
    resultSmallUnitSpriteAssetHash?: number | string;
    figurineSpriteAssetHash?: number | string;
    loadingTargetUnitSmallSpriteAssetHash?: number | string;
    catalogStorePilotCostume2SpriteAssetHash?: number | string;
    catalogStorePilotCostume3SpriteAssetHash?: number | string;
};

export type PostApiDebugData = {
    body: DebugCommand;
    path?: never;
    query?: never;
    url: '/api/debug';
};

export type PostApiDebugResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiUnitsData = {
    body?: never;
    path?: never;
    query?: {
        Page?: number | string;
        PerPage?: number | string;
        ListAll?: boolean;
        Search?: string;
        UnitIds?: Array<number | string>;
        Languages?: Array<LanguageSettings>;
        Includes?: Array<GetUnitSummaryQueryIncludes>;
    };
    url: '/api/units';
};

export type GetApiUnitsResponses = {
    /**
     * OK
     */
    200: PaginatedListOfUnitSummaryVm;
};

export type GetApiUnitsResponse = GetApiUnitsResponses[keyof GetApiUnitsResponses];

export type PostApiUnitsData = {
    body: CreateUnitCommand;
    path?: never;
    query?: never;
    url: '/api/units';
};

export type PostApiUnitsResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type GetApiUnitsByUnitIdData = {
    body?: never;
    path: {
        unitId: number | string;
    };
    query?: never;
    url: '/api/units/{unitId}';
};

export type GetApiUnitsByUnitIdResponses = {
    /**
     * OK
     */
    200: UnitSummaryVm;
};

export type GetApiUnitsByUnitIdResponse = GetApiUnitsByUnitIdResponses[keyof GetApiUnitsByUnitIdResponses];

export type PostApiUnitsByUnitIdData = {
    body: UpdateUnitCommand;
    path: {
        unitId: number | string;
    };
    query?: never;
    url: '/api/units/{unitId}';
};

export type PostApiUnitsByUnitIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiUnitsByUnitIdResponse = PostApiUnitsByUnitIdResponses[keyof PostApiUnitsByUnitIdResponses];

export type GetApiUnitsByUnitIdPlayableCharactersData = {
    body?: never;
    path: {
        unitId: number | string;
    };
    query?: never;
    url: '/api/units/{unitId}/playable-characters';
};

export type GetApiUnitsByUnitIdPlayableCharactersResponses = {
    /**
     * OK
     */
    200: PlayableCharacterDto;
};

export type GetApiUnitsByUnitIdPlayableCharactersResponse = GetApiUnitsByUnitIdPlayableCharactersResponses[keyof GetApiUnitsByUnitIdPlayableCharactersResponses];

export type PostApiUnitsBulkData = {
    body: BulkCreateUnitCommand;
    path?: never;
    query?: never;
    url: '/api/units/bulk';
};

export type PostApiUnitsBulkResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type DeleteApiUnitsByUnitIdPlayableCharacterData = {
    body?: never;
    path: {
        unitId: number | string;
    };
    query?: never;
    url: '/api/units/{unitId}/playable-character';
};

export type DeleteApiUnitsByUnitIdPlayableCharacterResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiUnitsByUnitIdPlayableCharacterResponse = DeleteApiUnitsByUnitIdPlayableCharacterResponses[keyof DeleteApiUnitsByUnitIdPlayableCharacterResponses];

export type PostApiUnitsByUnitIdPlayableCharacterData = {
    body: UpsertPlayableCharacterCommand;
    path: {
        unitId: number | string;
    };
    query?: never;
    url: '/api/units/{unitId}/playable-character';
};

export type PostApiUnitsByUnitIdPlayableCharacterResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiUnitsByUnitIdPlayableCharacterResponse = PostApiUnitsByUnitIdPlayableCharacterResponses[keyof PostApiUnitsByUnitIdPlayableCharacterResponses];

export type PostApiUnitsPlayableCharactersImportData = {
    body: {
        file: IFormFile;
    };
    path?: never;
    query?: never;
    url: '/api/units/playable-characters/import';
};

export type PostApiUnitsPlayableCharactersImportResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type PostApiUnitsPlayableCharactersExportData = {
    body: ExportPlayableCharactersCommand;
    path?: never;
    query?: never;
    url: '/api/units/playable-characters/export';
};

export type PostApiUnitsPlayableCharactersExportResponses = {
    /**
     * OK
     */
    200: FileContentHttpResult;
};

export type PostApiUnitsPlayableCharactersExportResponse = PostApiUnitsPlayableCharactersExportResponses[keyof PostApiUnitsPlayableCharactersExportResponses];

export type GetApiPatchFilesData = {
    body?: never;
    path?: never;
    query?: {
        Page?: number | string;
        PerPage?: number | string;
        Search?: string;
        Versions?: Array<PatchFileVersion>;
        UnitIds?: Array<number | string>;
    };
    url: '/api/patch-files';
};

export type GetApiPatchFilesResponses = {
    /**
     * OK
     */
    200: PaginatedListOfPatchFileVm;
};

export type GetApiPatchFilesResponse = GetApiPatchFilesResponses[keyof GetApiPatchFilesResponses];

export type PostApiPatchFilesData = {
    body: CreatePatchFileCommand;
    path?: never;
    query?: never;
    url: '/api/patch-files';
};

export type PostApiPatchFilesResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type GetApiPatchFilesSummaryData = {
    body?: never;
    path?: never;
    query?: {
        Page?: number | string;
        PerPage?: number | string;
        Versions?: Array<PatchFileVersion>;
        UnitIds?: Array<number | string>;
        AssetFileHashes?: Array<number | string>;
        AssetFileTypes?: Array<AssetFileType>;
    };
    url: '/api/patch-files/summary';
};

export type GetApiPatchFilesSummaryResponses = {
    /**
     * OK
     */
    200: PaginatedListOfPatchFileSummaryVm;
};

export type GetApiPatchFilesSummaryResponse = GetApiPatchFilesSummaryResponses[keyof GetApiPatchFilesSummaryResponses];

export type DeleteApiPatchFilesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/patch-files/{id}';
};

export type DeleteApiPatchFilesByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiPatchFilesByIdResponse = DeleteApiPatchFilesByIdResponses[keyof DeleteApiPatchFilesByIdResponses];

export type GetApiPatchFilesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/patch-files/{id}';
};

export type GetApiPatchFilesByIdResponses = {
    /**
     * OK
     */
    200: PatchFileVm;
};

export type GetApiPatchFilesByIdResponse = GetApiPatchFilesByIdResponses[keyof GetApiPatchFilesByIdResponses];

export type PostApiPatchFilesByIdData = {
    body: UpdatePatchFileByIdCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/patch-files/{id}';
};

export type PostApiPatchFilesByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiPatchFilesByIdResponse = PostApiPatchFilesByIdResponses[keyof PostApiPatchFilesByIdResponses];

export type PostApiPatchFilesResizeData = {
    body: ResizePatchFileCommand;
    path?: never;
    query?: never;
    url: '/api/patch-files/resize';
};

export type PostApiPatchFilesResizeResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiPatchFilesResizeResponse = PostApiPatchFilesResizeResponses[keyof PostApiPatchFilesResizeResponses];

export type GetApiTblDeserializePathData = {
    body?: never;
    path?: never;
    query: {
        filePath: string;
    };
    url: '/api/tbl/deserialize-path';
};

export type GetApiTblDeserializePathResponses = {
    /**
     * OK
     */
    200: TblDto;
};

export type GetApiTblDeserializePathResponse = GetApiTblDeserializePathResponses[keyof GetApiTblDeserializePathResponses];

export type PostApiTblDeserializeData = {
    body: {
        file: IFormFile;
    };
    path?: never;
    query?: never;
    url: '/api/tbl/deserialize';
};

export type PostApiTblDeserializeResponses = {
    /**
     * OK
     */
    200: TblDto;
};

export type PostApiTblDeserializeResponse = PostApiTblDeserializeResponses[keyof PostApiTblDeserializeResponses];

export type GetApiTblSerializePathData = {
    body?: never;
    path?: never;
    query: {
        filePath: string;
    };
    url: '/api/tbl/serialize-path';
};

export type GetApiTblSerializePathResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiTblSerializeData = {
    body: SerializeTblCommand;
    path?: never;
    query?: never;
    url: '/api/tbl/serialize';
};

export type PostApiTblSerializeResponses = {
    /**
     * OK
     */
    200: FileContentHttpResult;
};

export type PostApiTblSerializeResponse = PostApiTblSerializeResponses[keyof PostApiTblSerializeResponses];

export type GetApiTblByIdData = {
    body?: never;
    path: {
        id: PatchFileVersion;
    };
    query?: never;
    url: '/api/tbl/{id}';
};

export type GetApiTblByIdResponses = {
    /**
     * OK
     */
    200: TblVm;
};

export type GetApiTblByIdResponse = GetApiTblByIdResponses[keyof GetApiTblByIdResponses];

export type PostApiTblImportData = {
    body: {
        files: IFormFileCollection;
    };
    path?: never;
    query?: never;
    url: '/api/tbl/import';
};

export type PostApiTblImportResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type PostApiTblExportData = {
    body: ExportTblCommand;
    path?: never;
    query?: never;
    url: '/api/tbl/export';
};

export type PostApiTblExportResponses = {
    /**
     * OK
     */
    200: FileContentHttpResult;
};

export type PostApiTblExportResponse = PostApiTblExportResponses[keyof PostApiTblExportResponses];

export type GetApiStatsData = {
    body?: never;
    path?: never;
    query?: {
        Page?: number | string;
        PerPage?: number | string;
        Ids?: Array<string>;
        UnitIds?: Array<number | string>;
    };
    url: '/api/stats';
};

export type GetApiStatsResponses = {
    /**
     * OK
     */
    200: PaginatedListOfStatDto;
};

export type GetApiStatsResponse = GetApiStatsResponses[keyof GetApiStatsResponses];

export type PostApiStatsData = {
    body: CreateStatCommand;
    path?: never;
    query?: never;
    url: '/api/stats';
};

export type PostApiStatsResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type DeleteApiStatsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/stats/{id}';
};

export type DeleteApiStatsByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiStatsByIdResponse = DeleteApiStatsByIdResponses[keyof DeleteApiStatsByIdResponses];

export type GetApiStatsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/stats/{id}';
};

export type GetApiStatsByIdResponses = {
    /**
     * OK
     */
    200: StatDto;
};

export type GetApiStatsByIdResponse = GetApiStatsByIdResponses[keyof GetApiStatsByIdResponses];

export type PostApiStatsByIdData = {
    body: UpdateStatCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/stats/{id}';
};

export type PostApiStatsByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiStatsByIdResponse = PostApiStatsByIdResponses[keyof PostApiStatsByIdResponses];

export type GetApiUnitStatsData = {
    body?: never;
    path?: never;
    query?: {
        Page?: number | string;
        PerPage?: number | string;
        UnitIds?: Array<number | string>;
    };
    url: '/api/unit-stats';
};

export type GetApiUnitStatsResponses = {
    /**
     * OK
     */
    200: PaginatedListOfUnitStatDto;
};

export type GetApiUnitStatsResponse = GetApiUnitStatsResponses[keyof GetApiUnitStatsResponses];

export type GetApiUnitStatsByUnitIdData = {
    body?: never;
    path: {
        unitId: number | string;
    };
    query?: never;
    url: '/api/unit-stats/{unitId}';
};

export type GetApiUnitStatsByUnitIdResponses = {
    /**
     * OK
     */
    200: UnitStatDto;
};

export type GetApiUnitStatsByUnitIdResponse = GetApiUnitStatsByUnitIdResponses[keyof GetApiUnitStatsByUnitIdResponses];

export type PostApiUnitStatsImportData = {
    body: {
        files: IFormFileCollection;
    };
    path?: never;
    query?: never;
    url: '/api/unit-stats/import';
};

export type PostApiUnitStatsImportResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type PostApiUnitStatsExportData = {
    body: ExportUnitStatCommand;
    path?: never;
    query?: never;
    url: '/api/unit-stats/export';
};

export type PostApiUnitStatsExportResponses = {
    /**
     * OK
     */
    200: FileContentHttpResult;
};

export type PostApiUnitStatsExportResponse = PostApiUnitStatsExportResponses[keyof PostApiUnitStatsExportResponses];

export type PostApiUnitStatsExportPathData = {
    body: ExportUnitStatByPathCommand;
    path?: never;
    query?: never;
    url: '/api/unit-stats/export/path';
};

export type PostApiUnitStatsExportPathResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiUnitStatsExportPathResponse = PostApiUnitStatsExportPathResponses[keyof PostApiUnitStatsExportPathResponses];

export type GetApiUnitStatsAmmoSlotByUnitIdData = {
    body?: never;
    path: {
        unitId: number | string;
    };
    query?: never;
    url: '/api/unit-stats/ammo-slot/{unitId}';
};

export type GetApiUnitStatsAmmoSlotByUnitIdResponses = {
    /**
     * OK
     */
    200: Array<UnitAmmoSlotDto>;
};

export type GetApiUnitStatsAmmoSlotByUnitIdResponse = GetApiUnitStatsAmmoSlotByUnitIdResponses[keyof GetApiUnitStatsAmmoSlotByUnitIdResponses];

export type PostApiUnitStatsAmmoSlotData = {
    body: CreateUnitAmmoSlotCommand;
    path?: never;
    query?: never;
    url: '/api/unit-stats/ammo-slot';
};

export type PostApiUnitStatsAmmoSlotResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type DeleteApiUnitStatsAmmoSlotByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/unit-stats/ammo-slot/{id}';
};

export type DeleteApiUnitStatsAmmoSlotByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiUnitStatsAmmoSlotByIdResponse = DeleteApiUnitStatsAmmoSlotByIdResponses[keyof DeleteApiUnitStatsAmmoSlotByIdResponses];

export type PostApiUnitStatsAmmoSlotByIdData = {
    body: UpdateUnitAmmoSlotCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/unit-stats/ammo-slot/{id}';
};

export type PostApiUnitStatsAmmoSlotByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiUnitStatsAmmoSlotByIdResponse = PostApiUnitStatsAmmoSlotByIdResponses[keyof PostApiUnitStatsAmmoSlotByIdResponses];

export type GetApiSeriesData = {
    body?: never;
    path?: never;
    query?: {
        Page?: number | string;
        PerPage?: number | string;
        Search?: Array<string>;
        ListAll?: boolean;
    };
    url: '/api/series';
};

export type GetApiSeriesResponses = {
    /**
     * OK
     */
    200: PaginatedListOfSeriesDto;
};

export type GetApiSeriesResponse = GetApiSeriesResponses[keyof GetApiSeriesResponses];

export type PostApiSeriesData = {
    body: CreateSeriesCommand;
    path?: never;
    query?: never;
    url: '/api/series';
};

export type PostApiSeriesResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type GetApiSeriesUnitsData = {
    body?: never;
    path?: never;
    query?: {
        Page?: number | string;
        PerPage?: number | string;
        UnitIds?: Array<number | string>;
        ListAll?: boolean;
    };
    url: '/api/series/units';
};

export type GetApiSeriesUnitsResponses = {
    /**
     * OK
     */
    200: PaginatedListOfSeriesUnitsVm;
};

export type GetApiSeriesUnitsResponse = GetApiSeriesUnitsResponses[keyof GetApiSeriesUnitsResponses];

export type PostApiSeriesImportData = {
    body: {
        file: IFormFile;
    };
    path?: never;
    query?: never;
    url: '/api/series/import';
};

export type PostApiSeriesImportResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type PostApiSeriesExportData = {
    body: ExportPlayableSeriesCommand;
    path?: never;
    query?: never;
    url: '/api/series/export';
};

export type PostApiSeriesExportResponses = {
    /**
     * OK
     */
    200: FileContentHttpResult;
};

export type PostApiSeriesExportResponse = PostApiSeriesExportResponses[keyof PostApiSeriesExportResponses];

export type GetApiScexDecompiledByUnitIdData = {
    body?: never;
    path: {
        unitId: number | string;
    };
    query?: never;
    url: '/api/scex/decompiled/{unitId}';
};

export type GetApiScexDecompiledByUnitIdResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetApiScexDecompiledByUnitIdResponse = GetApiScexDecompiledByUnitIdResponses[keyof GetApiScexDecompiledByUnitIdResponses];

export type PostApiScexCompilePathData = {
    body: CompileScexByPathCommand;
    path?: never;
    query?: never;
    url: '/api/scex/compile/path';
};

export type PostApiScexCompilePathResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiScexCompilePathResponse = PostApiScexCompilePathResponses[keyof PostApiScexCompilePathResponses];

export type PostApiScexDecompilePathData = {
    body: DecompileScexByPathCommand;
    path?: never;
    query?: never;
    url: '/api/scex/decompile/path';
};

export type PostApiScexDecompilePathResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiScexDecompilePathResponse = PostApiScexDecompilePathResponses[keyof PostApiScexDecompilePathResponses];

export type PostApiScexHotReloadPathData = {
    body: HotReloadScex;
    path?: never;
    query?: never;
    url: '/api/scex/hot-reload/path';
};

export type PostApiScexHotReloadPathResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiScexHotReloadPathResponse = PostApiScexHotReloadPathResponses[keyof PostApiScexHotReloadPathResponses];

export type PostApiScexCompileUnitsData = {
    body: CompileScexByUnitsCommand;
    path?: never;
    query?: never;
    url: '/api/scex/compile/units';
};

export type PostApiScexCompileUnitsResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiScexCompileUnitsResponse = PostApiScexCompileUnitsResponses[keyof PostApiScexCompileUnitsResponses];

export type PostApiScexDecompileUnitsData = {
    body: DecompileScexByUnitsCommand;
    path?: never;
    query?: never;
    url: '/api/scex/decompile/units';
};

export type PostApiScexDecompileUnitsResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiScexDecompileUnitsResponse = PostApiScexDecompileUnitsResponses[keyof PostApiScexDecompileUnitsResponses];

export type PostApiPsarcPackPathData = {
    body: PackPsarcByPathCommand;
    path?: never;
    query?: never;
    url: '/api/psarc/pack/path';
};

export type PostApiPsarcPackPathResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiPsarcPackPathResponse = PostApiPsarcPackPathResponses[keyof PostApiPsarcPackPathResponses];

export type PostApiPsarcUnpackPathData = {
    body: UnpackPsarcByPathCommand;
    path?: never;
    query?: never;
    url: '/api/psarc/unpack/path';
};

export type PostApiPsarcUnpackPathResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiPsarcUnpackPathResponse = PostApiPsarcUnpackPathResponses[keyof PostApiPsarcUnpackPathResponses];

export type PostApiPsarcPackPatchFilesData = {
    body: PackPsarcByPatchFilesCommand;
    path?: never;
    query?: never;
    url: '/api/psarc/pack/patch-files';
};

export type PostApiPsarcPackPatchFilesResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiPsarcPackPatchFilesResponse = PostApiPsarcPackPatchFilesResponses[keyof PostApiPsarcPackPatchFilesResponses];

export type PostApiPsarcUnpackPatchFilesData = {
    body: UnpackPsarcByPatchFilesCommand;
    path?: never;
    query?: never;
    url: '/api/psarc/unpack/patch-files';
};

export type PostApiPsarcUnpackPatchFilesResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiPsarcUnpackPatchFilesResponse = PostApiPsarcUnpackPatchFilesResponses[keyof PostApiPsarcUnpackPatchFilesResponses];

export type GetApiProjectilesData = {
    body?: never;
    path?: never;
    query?: {
        Page?: number | string;
        PerPage?: number | string;
        Hashes?: Array<number | string>;
        UnitIds?: Array<number | string>;
        ModelHashes?: Array<number | string>;
        Search?: string;
    };
    url: '/api/projectiles';
};

export type GetApiProjectilesResponses = {
    /**
     * OK
     */
    200: PaginatedListOfProjectileDto;
};

export type GetApiProjectilesResponse = GetApiProjectilesResponses[keyof GetApiProjectilesResponses];

export type PostApiProjectilesData = {
    body: CreateProjectileCommand;
    path?: never;
    query?: never;
    url: '/api/projectiles';
};

export type PostApiProjectilesResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type DeleteApiProjectilesByHashData = {
    body?: never;
    path: {
        hash: number | string;
    };
    query?: never;
    url: '/api/projectiles/{hash}';
};

export type DeleteApiProjectilesByHashResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiProjectilesByHashData = {
    body?: never;
    path: {
        hash: number | string;
    };
    query?: never;
    url: '/api/projectiles/{hash}';
};

export type GetApiProjectilesByHashResponses = {
    /**
     * OK
     */
    200: ProjectileDto;
};

export type GetApiProjectilesByHashResponse = GetApiProjectilesByHashResponses[keyof GetApiProjectilesByHashResponses];

export type PostApiProjectilesByHashData = {
    body: UpdateProjectileByIdCommand;
    path: {
        hash: number | string;
    };
    query?: never;
    url: '/api/projectiles/{hash}';
};

export type PostApiProjectilesByHashResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiUnitProjectilesData = {
    body?: never;
    path?: never;
    query?: {
        Page?: number | string;
        PerPage?: number | string;
        UnitIds?: Array<number | string>;
        Search?: string;
    };
    url: '/api/unit-projectiles';
};

export type GetApiUnitProjectilesResponses = {
    /**
     * OK
     */
    200: PaginatedListOfUnitProjectileDto;
};

export type GetApiUnitProjectilesResponse = GetApiUnitProjectilesResponses[keyof GetApiUnitProjectilesResponses];

export type GetApiUnitProjectilesByUnitIdData = {
    body?: never;
    path: {
        unitId: number | string;
    };
    query?: never;
    url: '/api/unit-projectiles/{unitId}';
};

export type GetApiUnitProjectilesByUnitIdResponses = {
    /**
     * OK
     */
    200: UnitProjectileDto;
};

export type GetApiUnitProjectilesByUnitIdResponse = GetApiUnitProjectilesByUnitIdResponses[keyof GetApiUnitProjectilesByUnitIdResponses];

export type PostApiUnitProjectilesImportData = {
    body: {
        files: IFormFileCollection;
    };
    path?: never;
    query?: never;
    url: '/api/unit-projectiles/import';
};

export type PostApiUnitProjectilesImportResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type PostApiUnitProjectilesImportPathData = {
    body?: never;
    path?: never;
    query: {
        directoryPath: string;
    };
    url: '/api/unit-projectiles/import/path';
};

export type PostApiUnitProjectilesImportPathResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type PostApiUnitProjectilesExportData = {
    body: ExportUnitProjectileCommand;
    path?: never;
    query?: never;
    url: '/api/unit-projectiles/export';
};

export type PostApiUnitProjectilesExportResponses = {
    /**
     * OK
     */
    200: FileContentHttpResult;
};

export type PostApiUnitProjectilesExportResponse = PostApiUnitProjectilesExportResponses[keyof PostApiUnitProjectilesExportResponses];

export type PostApiUnitProjectilesExportPathData = {
    body: ExportUnitProjectileByPathCommand;
    path?: never;
    query?: never;
    url: '/api/unit-projectiles/export/path';
};

export type PostApiUnitProjectilesExportPathResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiUnitProjectilesExportPathResponse = PostApiUnitProjectilesExportPathResponses[keyof PostApiUnitProjectilesExportPathResponses];

export type PostApiNdp3Data = {
    body: {
        ndp3File: IFormFile;
    } & {
        vbnFile?: IFormFile;
    };
    path?: never;
    query?: never;
    url: '/api/ndp3';
};

export type PostApiNdp3Responses = {
    /**
     * OK
     */
    200: FileContentHttpResult;
};

export type PostApiNdp3Response = PostApiNdp3Responses[keyof PostApiNdp3Responses];

export type PostApiNdp3JsonData = {
    body: {
        ndp3File: IFormFile;
    } & {
        vbnFile: IFormFile;
    };
    path?: never;
    query?: never;
    url: '/api/ndp3/json';
};

export type PostApiNdp3JsonResponses = {
    /**
     * OK
     */
    200: FileContentHttpResult;
};

export type PostApiNdp3JsonResponse = PostApiNdp3JsonResponses[keyof PostApiNdp3JsonResponses];

export type GetApiHitboxesData = {
    body?: never;
    path?: never;
    query?: {
        Page?: number | string;
        PerPage?: number | string;
        Hashes?: Array<number | string>;
        UnitIds?: Array<number | string>;
        Search?: string;
    };
    url: '/api/hitboxes';
};

export type GetApiHitboxesResponses = {
    /**
     * OK
     */
    200: PaginatedListOfHitboxDto;
};

export type GetApiHitboxesResponse = GetApiHitboxesResponses[keyof GetApiHitboxesResponses];

export type PostApiHitboxesData = {
    body: CreateHitboxCommand;
    path?: never;
    query?: never;
    url: '/api/hitboxes';
};

export type PostApiHitboxesResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type DeleteApiHitboxesByHashData = {
    body?: never;
    path: {
        hash: number | string;
    };
    query?: never;
    url: '/api/hitboxes/{hash}';
};

export type DeleteApiHitboxesByHashResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiHitboxesByHashResponse = DeleteApiHitboxesByHashResponses[keyof DeleteApiHitboxesByHashResponses];

export type GetApiHitboxesByHashData = {
    body?: never;
    path: {
        hash: number | string;
    };
    query?: never;
    url: '/api/hitboxes/{hash}';
};

export type GetApiHitboxesByHashResponses = {
    /**
     * OK
     */
    200: HitboxDto;
};

export type GetApiHitboxesByHashResponse = GetApiHitboxesByHashResponses[keyof GetApiHitboxesByHashResponses];

export type PostApiHitboxesByHashData = {
    body: UpdateHitboxCommand;
    path: {
        hash: number | string;
    };
    query?: never;
    url: '/api/hitboxes/{hash}';
};

export type PostApiHitboxesByHashResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiHitboxesByHashResponse = PostApiHitboxesByHashResponses[keyof PostApiHitboxesByHashResponses];

export type GetApiHitboxGroupsData = {
    body?: never;
    path?: never;
    query?: {
        Page?: number | string;
        PerPage?: number | string;
        Hashes?: Array<number | string>;
        UnitIds?: Array<number | string>;
    };
    url: '/api/hitbox-groups';
};

export type GetApiHitboxGroupsResponses = {
    /**
     * OK
     */
    200: PaginatedListOfHitboxGroupDto;
};

export type GetApiHitboxGroupsResponse = GetApiHitboxGroupsResponses[keyof GetApiHitboxGroupsResponses];

export type PostApiHitboxGroupsData = {
    body: CreateHitboxGroupCommand;
    path?: never;
    query?: never;
    url: '/api/hitbox-groups';
};

export type PostApiHitboxGroupsResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type GetApiHitboxGroupsHashByHashData = {
    body?: never;
    path: {
        hash: number | string;
    };
    query?: never;
    url: '/api/hitbox-groups/hash/{hash}';
};

export type GetApiHitboxGroupsHashByHashResponses = {
    /**
     * OK
     */
    200: HitboxGroupDto;
};

export type GetApiHitboxGroupsHashByHashResponse = GetApiHitboxGroupsHashByHashResponses[keyof GetApiHitboxGroupsHashByHashResponses];

export type GetApiHitboxGroupsUnitIdByUnitIdData = {
    body?: never;
    path: {
        unitId: number | string;
    };
    query?: never;
    url: '/api/hitbox-groups/unitId/{unitId}';
};

export type GetApiHitboxGroupsUnitIdByUnitIdResponses = {
    /**
     * OK
     */
    200: HitboxGroupDto;
};

export type GetApiHitboxGroupsUnitIdByUnitIdResponse = GetApiHitboxGroupsUnitIdByUnitIdResponses[keyof GetApiHitboxGroupsUnitIdByUnitIdResponses];

export type PostApiHitboxGroupsByHashData = {
    body: UpdateHitboxGroupCommand;
    path: {
        hash: number | string;
    };
    query?: never;
    url: '/api/hitbox-groups/{hash}';
};

export type PostApiHitboxGroupsByHashResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiHitboxGroupsByHashResponse = PostApiHitboxGroupsByHashResponses[keyof PostApiHitboxGroupsByHashResponses];

export type PostApiHitboxGroupsImportData = {
    body: {
        file: IFormFile;
    };
    path?: never;
    query?: {
        unitId?: number | string;
    };
    url: '/api/hitbox-groups/import';
};

export type PostApiHitboxGroupsImportResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type PostApiHitboxGroupsImportPathData = {
    body?: never;
    path?: never;
    query: {
        directoryPath: string;
    };
    url: '/api/hitbox-groups/import/path';
};

export type PostApiHitboxGroupsImportPathResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type PostApiHitboxGroupsExportData = {
    body: ExportHitboxGroupCommand;
    path?: never;
    query?: never;
    url: '/api/hitbox-groups/export';
};

export type PostApiHitboxGroupsExportResponses = {
    /**
     * OK
     */
    200: FileContentHttpResult;
};

export type PostApiHitboxGroupsExportResponse = PostApiHitboxGroupsExportResponses[keyof PostApiHitboxGroupsExportResponses];

export type PostApiHitboxGroupsExportPathData = {
    body: ExportHitboxGroupByPathCommand;
    path?: never;
    query?: never;
    url: '/api/hitbox-groups/export/path';
};

export type PostApiHitboxGroupsExportPathResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiHitboxGroupsExportPathResponse = PostApiHitboxGroupsExportPathResponses[keyof PostApiHitboxGroupsExportPathResponses];

export type GetApiFhmPackPathData = {
    body?: never;
    path?: never;
    query: {
        SourcePath: string;
        DestinationPath: string;
        FileName?: string;
    };
    url: '/api/fhm/pack-path';
};

export type GetApiFhmPackPathResponses = {
    /**
     * No Content
     */
    204: void;
};

export type GetApiFhmPackPathResponse = GetApiFhmPackPathResponses[keyof GetApiFhmPackPathResponses];

export type GetApiFhmUnpackPathData = {
    body?: never;
    path?: never;
    query: {
        SourceFilePath: string;
        OutputDirectoryPath: string;
        MultipleFiles?: boolean;
    };
    url: '/api/fhm/unpack-path';
};

export type GetApiFhmUnpackPathResponses = {
    /**
     * No Content
     */
    204: void;
};

export type GetApiFhmUnpackPathResponse = GetApiFhmUnpackPathResponses[keyof GetApiFhmUnpackPathResponses];

export type PostApiFhmPackData = {
    body: {
        file: IFormFile;
    };
    path?: never;
    query?: never;
    url: '/api/fhm/pack';
};

export type PostApiFhmPackResponses = {
    /**
     * OK
     */
    200: FileContentHttpResult;
};

export type PostApiFhmPackResponse = PostApiFhmPackResponses[keyof PostApiFhmPackResponses];

export type PostApiFhmUnpackData = {
    body: {
        file: IFormFile;
    };
    path?: never;
    query?: {
        compressionFormat?: CompressionFormats;
    };
    url: '/api/fhm/unpack';
};

export type PostApiFhmUnpackResponses = {
    /**
     * OK
     */
    200: FileContentHttpResult;
};

export type PostApiFhmUnpackResponse = PostApiFhmUnpackResponses[keyof PostApiFhmUnpackResponses];

export type PostApiFhmPackAssetData = {
    body: PackFhmByAssetCommand;
    path?: never;
    query?: never;
    url: '/api/fhm/pack/asset';
};

export type PostApiFhmPackAssetResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiFhmPackAssetResponse = PostApiFhmPackAssetResponses[keyof PostApiFhmPackAssetResponses];

export type PostApiFhmUnpackAssetData = {
    body: UnpackFhmByAssetCommand;
    path?: never;
    query?: never;
    url: '/api/fhm/unpack/asset';
};

export type PostApiFhmUnpackAssetResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiFhmUnpackAssetResponse = PostApiFhmUnpackAssetResponses[keyof PostApiFhmUnpackAssetResponses];

export type GetApiConfigsData = {
    body?: never;
    path?: never;
    query: {
        Keys: Array<string>;
    };
    url: '/api/configs';
};

export type GetApiConfigsResponses = {
    /**
     * OK
     */
    200: Array<ConfigDto>;
};

export type GetApiConfigsResponse = GetApiConfigsResponses[keyof GetApiConfigsResponses];

export type PostApiConfigsData = {
    body: UpsertConfigCommand;
    path?: never;
    query?: never;
    url: '/api/configs';
};

export type PostApiConfigsResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiConfigsResponse = PostApiConfigsResponses[keyof PostApiConfigsResponses];

export type DeleteApiConfigsByKeyData = {
    body?: never;
    path: {
        key: string;
    };
    query?: never;
    url: '/api/configs/{key}';
};

export type DeleteApiConfigsByKeyResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiConfigsByKeyResponse = DeleteApiConfigsByKeyResponses[keyof DeleteApiConfigsByKeyResponses];

export type GetApiConfigsByKeyData = {
    body?: never;
    path: {
        key: string;
    };
    query?: never;
    url: '/api/configs/{key}';
};

export type GetApiConfigsByKeyResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetApiConfigsByKeyResponse = GetApiConfigsByKeyResponses[keyof GetApiConfigsByKeyResponses];

export type GetApiAssetsData = {
    body?: never;
    path?: never;
    query?: {
        Page?: number | string;
        PerPage?: number | string;
        UnitIds?: Array<number | string>;
        AssetFileTypes?: Array<AssetFileType>;
        ListAll?: boolean;
    };
    url: '/api/assets';
};

export type GetApiAssetsResponses = {
    /**
     * OK
     */
    200: PaginatedListOfAssetFileVm;
};

export type GetApiAssetsResponse = GetApiAssetsResponses[keyof GetApiAssetsResponses];

export type PostApiAssetsData = {
    body: CreateAssetFileCommand;
    path?: never;
    query?: never;
    url: '/api/assets';
};

export type PostApiAssetsResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type DeleteApiAssetsByHashData = {
    body?: never;
    path: {
        hash: number | string;
    };
    query?: never;
    url: '/api/assets/{hash}';
};

export type DeleteApiAssetsByHashResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiAssetsByHashResponse = DeleteApiAssetsByHashResponses[keyof DeleteApiAssetsByHashResponses];

export type GetApiAssetsByHashData = {
    body?: never;
    path: {
        hash: number | string;
    };
    query?: never;
    url: '/api/assets/{hash}';
};

export type GetApiAssetsByHashResponses = {
    /**
     * OK
     */
    200: AssetFileVm;
};

export type GetApiAssetsByHashResponse = GetApiAssetsByHashResponses[keyof GetApiAssetsByHashResponses];

export type PostApiAssetsByHashData = {
    body: UpdateAssetFileByHashCommand;
    path: {
        hash: number | string;
    };
    query?: never;
    url: '/api/assets/{hash}';
};

export type PostApiAssetsByHashResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiAssetsByHashResponse = PostApiAssetsByHashResponses[keyof PostApiAssetsByHashResponses];

export type PostApiAssetsImportData = {
    body: {
        files: IFormFileCollection;
    };
    path?: never;
    query?: never;
    url: '/api/assets/import';
};

export type PostApiAssetsImportResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type GetApiAmmoData = {
    body?: never;
    path?: never;
    query?: {
        Page?: number | string;
        PerPage?: number | string;
        Hash?: Array<number | string>;
        UnitIds?: Array<number | string>;
        Search?: string;
        ListAll?: boolean;
    };
    url: '/api/ammo';
};

export type GetApiAmmoResponses = {
    /**
     * OK
     */
    200: PaginatedListOfAmmoDto;
};

export type GetApiAmmoResponse = GetApiAmmoResponses[keyof GetApiAmmoResponses];

export type PostApiAmmoData = {
    body: CreateAmmoCommand;
    path?: never;
    query?: never;
    url: '/api/ammo';
};

export type PostApiAmmoResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type DeleteApiAmmoByHashData = {
    body?: never;
    path: {
        hash: number | string;
    };
    query?: never;
    url: '/api/ammo/{hash}';
};

export type DeleteApiAmmoByHashResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiAmmoByHashResponse = DeleteApiAmmoByHashResponses[keyof DeleteApiAmmoByHashResponses];

export type GetApiAmmoByHashData = {
    body?: never;
    path: {
        hash: number | string;
    };
    query?: never;
    url: '/api/ammo/{hash}';
};

export type GetApiAmmoByHashResponses = {
    /**
     * OK
     */
    200: AmmoDto;
};

export type GetApiAmmoByHashResponse = GetApiAmmoByHashResponses[keyof GetApiAmmoByHashResponses];

export type PostApiAmmoByHashData = {
    body: UpdateAmmoCommand;
    path: {
        hash: number | string;
    };
    query?: never;
    url: '/api/ammo/{hash}';
};

export type PostApiAmmoByHashResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiAmmoByHashResponse = PostApiAmmoByHashResponses[keyof PostApiAmmoByHashResponses];

export type PostApiAmmoImportData = {
    body: {
        formFile: IFormFile;
    };
    path?: never;
    query?: never;
    url: '/api/ammo/import';
};

export type PostApiAmmoImportResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type PostApiAmmoExportData = {
    body: ExportAmmoCommand;
    path?: never;
    query?: never;
    url: '/api/ammo/export';
};

export type PostApiAmmoExportResponses = {
    /**
     * OK
     */
    200: FileContentHttpResult;
};

export type PostApiAmmoExportResponse = PostApiAmmoExportResponses[keyof PostApiAmmoExportResponses];

export type PostApiAmmoExportPathData = {
    body: ExportAmmoByPathCommand;
    path?: never;
    query?: never;
    url: '/api/ammo/export/path';
};

export type PostApiAmmoExportPathResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiAmmoExportPathResponse = PostApiAmmoExportPathResponses[keyof PostApiAmmoExportPathResponses];
