// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod";

export const zAmmoDto = z.object({
  hash: z.optional(z.coerce.bigint()),
  ammoType: z.optional(z.coerce.number()),
  maxAmmo: z.optional(z.coerce.number()),
  initialAmmo: z.optional(z.coerce.number()),
  timedDurationFrame: z.optional(z.coerce.number()),
  unk16: z.optional(z.coerce.number()),
  reloadType: z.optional(z.coerce.number()),
  cooldownDurationFrame: z.optional(z.coerce.number()),
  reloadDurationFrame: z.optional(z.coerce.number()),
  assaultBurstReloadDurationFrame: z.optional(z.coerce.number()),
  blastBurstReloadDurationFrame: z.optional(z.coerce.number()),
  unk40: z.optional(z.coerce.number()),
  unk44: z.optional(z.coerce.number()),
  inactiveUnk48: z.optional(z.coerce.number()),
  inactiveCooldownDurationFrame: z.optional(z.coerce.number()),
  inactiveReloadDurationFrame: z.optional(z.coerce.number()),
  inactiveAssaultBurstReloadDurationFrame: z.optional(z.coerce.number()),
  inactiveBlastBurstReloadDurationFrame: z.optional(z.coerce.number()),
  inactiveUnk68: z.optional(z.coerce.number()),
  inactiveUnk72: z.optional(z.coerce.number()),
  burstReplenish: z.optional(z.coerce.number()),
  unk80: z.optional(z.coerce.number()),
  unk84: z.optional(z.coerce.number()),
  unk88: z.optional(z.coerce.number()),
  chargeInput: z.optional(z.coerce.number()),
  chargeDurationFrame: z.optional(z.coerce.number()),
  assaultBurstChargeDurationFrame: z.optional(z.coerce.number()),
  blastBurstChargeDurationFrame: z.optional(z.coerce.number()),
  unk108: z.optional(z.coerce.number()),
  unk112: z.optional(z.coerce.number()),
  releaseChargeLingerDurationFrame: z.optional(z.coerce.number()),
  maxChargeLevel: z.optional(z.coerce.number()),
  unk124: z.optional(z.coerce.number()),
  unk128: z.optional(z.coerce.number()),
  order: z.optional(z.coerce.number()),
  unitId: z.optional(z.union([z.null(), z.coerce.number()])),
});

export const zAssetFileType = z.enum([
  "Unknown",
  "Dummy",
  "Animations",
  "ModelAndTexture",
  "Data",
  "Effects",
  "SoundEffects",
  "InGamePilotVoiceLines",
  "SpriteFrames",
  "WeaponSprites",
  "VoiceLinesMetadata",
  "PilotVoiceLines",
  "ArcadeSelectionCostume1Sprite",
  "ArcadeSelectionCostume2Sprite",
  "ArcadeSelectionCostume3Sprite",
  "LoadingLeftCostume1Sprite",
  "LoadingLeftCostume2Sprite",
  "LoadingLeftCostume3Sprite",
  "LoadingRightCostume1Sprite",
  "LoadingRightCostume2Sprite",
  "LoadingRightCostume3Sprite",
  "GenericSelectionCostume1Sprite",
  "GenericSelectionCostume2Sprite",
  "GenericSelectionCostume3Sprite",
  "LoadingTargetUnitSprite",
  "LoadingTargetPilotCostume1Sprite",
  "LoadingTargetPilotCostume2Sprite",
  "LoadingTargetPilotCostume3Sprite",
  "InGameSortieAndAwakeningPilotCostume1Sprite",
  "InGameSortieAndAwakeningPilotCostume2Sprite",
  "InGameSortieAndAwakeningPilotCostume3Sprite",
  "ResultSmallUnitSprite",
  "FigurineSprite",
  "LoadingTargetUnitSmallSprite",
  "CatalogStorePilotCostume2Sprite",
  "CatalogStorePilotCostume3Sprite",
  "Movie",
  "Hitboxes",
  "Projectiles",
  "Ammo",
  "ListInfo",
  "UnitCostInfo",
  "SharedFigurineSprites",
  "MapSelectSprites",
  "ArcadeSelectSmallSprites",
  "ArcadeSelectUnitNameSprites",
  "CameraConfigs",
  "CommonEffects",
  "CommonEffectParticles",
  "CosmeticInfo",
  "TextStrings",
  "SeriesLogoSprites",
  "SeriesLogoSprites2",
]);

export const zSeriesVm = z.union([
  z.null(),
  z.object({
    id: z.optional(z.coerce.number()),
    slugName: z.optional(z.string()),
    nameEnglish: z.optional(z.union([z.null(), z.string()])),
    nameJapanese: z.optional(z.union([z.null(), z.string()])),
    nameChinese: z.optional(z.union([z.null(), z.string()])),
  }),
]);

export const zUnitSummaryVm = z.object({
  unitId: z.optional(z.coerce.number()),
  slugName: z.optional(z.union([z.null(), z.string()])),
  nameEnglish: z.optional(z.union([z.null(), z.string()])),
  nameJapanese: z.optional(z.union([z.null(), z.string()])),
  nameChinese: z.optional(z.union([z.null(), z.string()])),
  seriesId: z.optional(z.union([z.null(), z.coerce.number()])),
  series: z.optional(zSeriesVm),
});

export const zAssetFileDto = z.union([
  z.null(),
  z.object({
    hash: z.coerce.number(),
    order: z.coerce.number(),
    fileType: z.array(zAssetFileType),
    units: z.array(zUnitSummaryVm),
  }),
]);

export const zAssetFileVm = z.object({
  hash: z.coerce.number(),
  order: z.optional(z.coerce.number()),
  fileType: z.optional(z.array(zAssetFileType)),
  unitIds: z.optional(z.array(z.coerce.number())),
});

export const zBulkCreateUnitCommand = z.object({
  units: z.array(zUnitSummaryVm),
});

export const zCompileScexByPathCommand = z.object({
  sourcePath: z.string(),
  destinationPath: z.string(),
  fileName: z.optional(z.union([z.null(), z.string()])),
  hotReload: z.optional(z.boolean()).default(true),
});

export const zCompileScexByUnitsCommand = z.object({
  unitIds: z.array(z.coerce.number()),
  replaceWorking: z.optional(z.boolean()).default(false),
  hotReload: z.optional(z.boolean()).default(false),
});

export const zCompressionFormats = z.enum(["Zip", "Tar"]);

export const zConfigDto = z.object({
  key: z.string(),
  value: z.string(),
});

export const zCreateAmmoCommand = z.object({
  ammoType: z.optional(z.coerce.number()),
  maxAmmo: z.optional(z.coerce.number()),
  initialAmmo: z.optional(z.coerce.number()),
  timedDurationFrame: z.optional(z.coerce.number()),
  unk16: z.optional(z.coerce.number()),
  reloadType: z.optional(z.coerce.number()),
  cooldownDurationFrame: z.optional(z.coerce.number()),
  reloadDurationFrame: z.optional(z.coerce.number()),
  assaultBurstReloadDurationFrame: z.optional(z.coerce.number()),
  blastBurstReloadDurationFrame: z.optional(z.coerce.number()),
  unk40: z.optional(z.coerce.number()),
  unk44: z.optional(z.coerce.number()),
  inactiveUnk48: z.optional(z.coerce.number()),
  inactiveCooldownDurationFrame: z.optional(z.coerce.number()),
  inactiveReloadDurationFrame: z.optional(z.coerce.number()),
  inactiveAssaultBurstReloadDurationFrame: z.optional(z.coerce.number()),
  inactiveBlastBurstReloadDurationFrame: z.optional(z.coerce.number()),
  inactiveUnk68: z.optional(z.coerce.number()),
  inactiveUnk72: z.optional(z.coerce.number()),
  burstReplenish: z.optional(z.coerce.number()),
  unk80: z.optional(z.coerce.number()),
  unk84: z.optional(z.coerce.number()),
  unk88: z.optional(z.coerce.number()),
  chargeInput: z.optional(z.coerce.number()),
  chargeDurationFrame: z.optional(z.coerce.number()),
  assaultBurstChargeDurationFrame: z.optional(z.coerce.number()),
  blastBurstChargeDurationFrame: z.optional(z.coerce.number()),
  unk108: z.optional(z.coerce.number()),
  unk112: z.optional(z.coerce.number()),
  releaseChargeLingerDurationFrame: z.optional(z.coerce.number()),
  maxChargeLevel: z.optional(z.coerce.number()),
  unk124: z.optional(z.coerce.number()),
  unk128: z.optional(z.coerce.number()),
  order: z.optional(z.coerce.number()),
  unitId: z.optional(z.union([z.null(), z.coerce.number()])),
});

export const zCreateAssetFileCommand = z.object({
  order: z.optional(z.coerce.number()),
  fileType: z.optional(z.array(zAssetFileType)),
  unitIds: z.optional(z.array(z.coerce.number())),
});

export const zCreateHitboxCommand = z.object({
  hitboxType: z.optional(z.coerce.number()),
  damage: z.optional(z.coerce.number()),
  unk8: z.optional(z.coerce.number()),
  downValueThreshold: z.optional(z.coerce.number()),
  yorukeValueThreshold: z.optional(z.coerce.number()),
  unk20: z.optional(z.coerce.number()),
  unk24: z.optional(z.coerce.number()),
  damageCorrection: z.optional(z.coerce.number()),
  specialEffect: z.optional(z.coerce.number()),
  hitEffect: z.optional(z.coerce.number()),
  flyDirection1: z.optional(z.coerce.number()),
  flyDirection2: z.optional(z.coerce.number()),
  flyDirection3: z.optional(z.coerce.number()),
  enemyCameraShakeMultiplier: z.optional(z.coerce.number()),
  playerCameraShakeMultiplier: z.optional(z.coerce.number()),
  unk56: z.optional(z.coerce.number()),
  knockUpAngle: z.optional(z.coerce.number()),
  knockUpRange: z.optional(z.coerce.number()),
  unk68: z.optional(z.coerce.number()),
  multipleHitIntervalFrame: z.optional(z.coerce.number()),
  multipleHitCount: z.optional(z.coerce.number()),
  enemyStunDuration: z.optional(z.coerce.number()),
  playerStunDuration: z.optional(z.coerce.number()),
  hitVisualEffect: z.optional(z.coerce.number()),
  hitVisualEffectSizeMultiplier: z.optional(z.coerce.number()),
  hitSoundEffectHash: z.optional(z.coerce.number()),
  unk100: z.optional(z.coerce.number()),
  friendlyDamageFlag: z.optional(z.coerce.number()),
  unk108: z.optional(z.coerce.number()),
  hitboxGroupHash: z.optional(z.coerce.number()),
});

export const zCreateHitboxGroupCommand = z.object({
  hash: z.coerce.number(),
  unitIds: z.optional(z.union([z.null(), z.array(z.coerce.number())])),
});

export const zPatchFileVersion = z.enum([
  "Base",
  "Patch1",
  "Patch2",
  "Patch3",
  "Patch4",
  "Patch5",
  "Patch6",
]);

export const zPathInfoDto = z.union([
  z.null(),
  z.object({
    path: z.string(),
    order: z.optional(z.union([z.null(), z.coerce.number()])),
  }),
]);

export const zFileInfoDto = z.union([
  z.null(),
  z.object({
    version: zPatchFileVersion,
    size1: z.coerce.number(),
    size2: z.coerce.number(),
    size3: z.coerce.number(),
    size4: z.coerce.number(),
  }),
]);

export const zCreatePatchFileCommand = z.object({
  tblId: zPatchFileVersion,
  pathInfo: z.optional(zPathInfoDto),
  fileInfo: z.optional(zFileInfoDto),
  assetFileHash: z.optional(z.union([z.null(), z.coerce.number()])),
});

export const zCreateProjectileCommand = z.object({
  projectileType: z.optional(z.coerce.number()),
  hitboxHash: z.optional(z.union([z.null(), z.coerce.number()])),
  modelHash: z.optional(z.coerce.number()),
  skeletonIndex: z.optional(z.coerce.number()),
  aimType: z.optional(z.coerce.number()),
  translateY: z.optional(z.coerce.number()),
  translateZ: z.optional(z.coerce.number()),
  translateX: z.optional(z.coerce.number()),
  rotateX: z.optional(z.coerce.number()),
  rotateZ: z.optional(z.coerce.number()),
  cosmeticHash: z.optional(z.coerce.number()),
  unk44: z.optional(z.coerce.number()),
  unk48: z.optional(z.coerce.number()),
  unk52: z.optional(z.coerce.number()),
  unk56: z.optional(z.coerce.number()),
  ammoConsumption: z.optional(z.coerce.number()),
  durationFrame: z.optional(z.coerce.number()),
  maxTravelDistance: z.optional(z.coerce.number()),
  initialSpeed: z.optional(z.coerce.number()),
  acceleration: z.optional(z.coerce.number()),
  accelerationStartFrame: z.optional(z.coerce.number()),
  unk84: z.optional(z.coerce.number()),
  maxSpeed: z.optional(z.coerce.number()),
  reserved92: z.optional(z.coerce.number()),
  reserved96: z.optional(z.coerce.number()),
  reserved100: z.optional(z.coerce.number()),
  reserved104: z.optional(z.coerce.number()),
  reserved108: z.optional(z.coerce.number()),
  reserved112: z.optional(z.coerce.number()),
  reserved116: z.optional(z.coerce.number()),
  horizontalGuidance: z.optional(z.coerce.number()),
  horizontalGuidanceAngle: z.optional(z.coerce.number()),
  verticalGuidance: z.optional(z.coerce.number()),
  verticalGuidanceAngle: z.optional(z.coerce.number()),
  reserved136: z.optional(z.coerce.number()),
  reserved140: z.optional(z.coerce.number()),
  reserved144: z.optional(z.coerce.number()),
  reserved148: z.optional(z.coerce.number()),
  reserved152: z.optional(z.coerce.number()),
  reserved156: z.optional(z.coerce.number()),
  reserved160: z.optional(z.coerce.number()),
  reserved164: z.optional(z.coerce.number()),
  reserved168: z.optional(z.coerce.number()),
  reserved172: z.optional(z.coerce.number()),
  size: z.optional(z.coerce.number()),
  reserved180: z.optional(z.coerce.number()),
  reserved184: z.optional(z.coerce.number()),
  soundEffectHash: z.optional(z.coerce.number()),
  reserved192: z.optional(z.coerce.number()),
  reserved196: z.optional(z.coerce.number()),
  chainedProjectileHash: z.optional(z.coerce.number()),
  reserved204: z.optional(z.coerce.number()),
  reserved208: z.optional(z.coerce.number()),
  reserved212: z.optional(z.coerce.number()),
  reserved216: z.optional(z.coerce.number()),
  reserved220: z.optional(z.coerce.number()),
  reserved224: z.optional(z.coerce.number()),
  reserved228: z.optional(z.coerce.number()),
  reserved232: z.optional(z.coerce.number()),
  reserved236: z.optional(z.coerce.number()),
  reserved240: z.optional(z.coerce.number()),
  reserved244: z.optional(z.coerce.number()),
  reserved248: z.optional(z.coerce.number()),
  reserved252: z.optional(z.coerce.number()),
  reserved256: z.optional(z.coerce.number()),
  reserved260: z.optional(z.coerce.number()),
  reserved264: z.optional(z.coerce.number()),
  reserved268: z.optional(z.coerce.number()),
  reserved272: z.optional(z.coerce.number()),
  reserved276: z.optional(z.coerce.number()),
  unitId: z.optional(z.union([z.null(), z.coerce.number()])),
});

export const zPlayableSeriesDetailsDto = z.union([
  z.null(),
  z.object({
    unk2: z.optional(z.coerce.number()),
    unk3: z.optional(z.coerce.number()),
    unk4: z.optional(z.coerce.number()),
    selectOrder: z.optional(z.coerce.number()),
    logoSpriteIndex: z.optional(z.coerce.number()),
    logoSprite2Index: z.optional(z.coerce.number()),
    unk11: z.optional(z.coerce.number()),
    movieAssetHash: z.optional(z.union([z.null(), z.coerce.number()])),
  }),
]);

export const zCreateSeriesCommand = z.object({
  id: z.optional(z.coerce.number()),
  playableSeries: z.optional(zPlayableSeriesDetailsDto),
  slugName: z.optional(z.string()),
  nameEnglish: z.optional(z.union([z.null(), z.string()])),
  nameJapanese: z.optional(z.union([z.null(), z.string()])),
  nameChinese: z.optional(z.union([z.null(), z.string()])),
});

export const zCreateStatCommand = z.object({
  unitCost: z.optional(z.coerce.number()),
  unitCost2: z.optional(z.coerce.number()),
  maxHp: z.optional(z.coerce.number()),
  downValueThreshold: z.optional(z.coerce.number()),
  yorukeValueThreshold: z.optional(z.coerce.number()),
  unk20: z.optional(z.coerce.number()),
  unk24: z.optional(z.coerce.number()),
  unk28: z.optional(z.coerce.number()),
  maxBoost: z.optional(z.coerce.number()),
  unk36: z.optional(z.coerce.number()),
  unk40: z.optional(z.coerce.number()),
  unk44: z.optional(z.coerce.number()),
  gravityMultiplierAir: z.optional(z.coerce.number()),
  gravityMultiplierLand: z.optional(z.coerce.number()),
  unk56: z.optional(z.coerce.number()),
  unk60: z.optional(z.coerce.number()),
  unk64: z.optional(z.coerce.number()),
  unk68: z.optional(z.coerce.number()),
  unk72: z.optional(z.coerce.number()),
  unk76: z.optional(z.coerce.number()),
  unk80: z.optional(z.coerce.number()),
  cameraZoomMultiplier: z.optional(z.coerce.number()),
  unk88: z.optional(z.coerce.number()),
  unk92: z.optional(z.coerce.number()),
  unk96: z.optional(z.coerce.number()),
  unk100: z.optional(z.coerce.number()),
  unk104: z.optional(z.coerce.number()),
  unk108: z.optional(z.coerce.number()),
  sizeMultiplier: z.optional(z.coerce.number()),
  unk116: z.optional(z.coerce.number()),
  unk120: z.optional(z.coerce.number()),
  unk124: z.optional(z.coerce.number()),
  unk128: z.optional(z.coerce.number()),
  unk132: z.optional(z.coerce.number()),
  unk136: z.optional(z.coerce.number()),
  unk140: z.optional(z.coerce.number()),
  unk144: z.optional(z.coerce.number()),
  unk148: z.optional(z.coerce.number()),
  unk152: z.optional(z.coerce.number()),
  unk156: z.optional(z.coerce.number()),
  unk160: z.optional(z.coerce.number()),
  unk164: z.optional(z.coerce.number()),
  unk168: z.optional(z.coerce.number()),
  unk172: z.optional(z.coerce.number()),
  unk176: z.optional(z.coerce.number()),
  unk180: z.optional(z.coerce.number()),
  unk184: z.optional(z.coerce.number()),
  redLockRangeMelee: z.optional(z.coerce.number()),
  redLockRange: z.optional(z.coerce.number()),
  unk196: z.optional(z.coerce.number()),
  unk200: z.optional(z.coerce.number()),
  unk204: z.optional(z.coerce.number()),
  unk208: z.optional(z.coerce.number()),
  boostReplenish: z.optional(z.coerce.number()),
  unk216: z.optional(z.coerce.number()),
  boostInitialConsumption: z.optional(z.coerce.number()),
  boostFuwaInitialConsumption: z.optional(z.coerce.number()),
  boostFlyConsumption: z.optional(z.coerce.number()),
  boostGroundStepInitialConsumption: z.optional(z.coerce.number()),
  boostGroundStepConsumption: z.optional(z.coerce.number()),
  boostAirStepInitialConsumption: z.optional(z.coerce.number()),
  boostAirStepConsumption: z.optional(z.coerce.number()),
  boostBdInitialConsumption: z.optional(z.coerce.number()),
  boostBdConsumption: z.optional(z.coerce.number()),
  unk256: z.optional(z.coerce.number()),
  unk260: z.optional(z.coerce.number()),
  unk264: z.optional(z.coerce.number()),
  unk268: z.optional(z.coerce.number()),
  boostTransformInitialConsumption: z.optional(z.coerce.number()),
  boostTransformConsumption: z.optional(z.coerce.number()),
  boostNonVernierActionConsumption: z.optional(z.coerce.number()),
  boostPostActionConsumption: z.optional(z.coerce.number()),
  boostRainbowStepInitialConsumption: z.optional(z.coerce.number()),
  unk292: z.optional(z.coerce.number()),
  unk296: z.optional(z.coerce.number()),
  unk300: z.optional(z.coerce.number()),
  unk304: z.optional(z.coerce.number()),
  unk308: z.optional(z.coerce.number()),
  unk312: z.optional(z.coerce.number()),
  unk316: z.optional(z.coerce.number()),
  unk320: z.optional(z.coerce.number()),
  unk324: z.optional(z.coerce.number()),
  unk328: z.optional(z.coerce.number()),
  unk332: z.optional(z.coerce.number()),
  assaultBurstRedLockMelee: z.optional(z.coerce.number()),
  assaultBurstRedLock: z.optional(z.coerce.number()),
  assaultBurstDamageDealtMultiplier: z.optional(z.coerce.number()),
  assaultBurstDamageTakenMultiplier: z.optional(z.coerce.number()),
  assaultBurstMobilityMultiplier: z.optional(z.coerce.number()),
  assaultBurstDownValueDealtMultiplier: z.optional(z.coerce.number()),
  assaultBurstBoostConsumptionMultiplier: z.optional(z.coerce.number()),
  unk364: z.optional(z.coerce.number()),
  unk368: z.optional(z.coerce.number()),
  assaultBurstDamageDealtBurstGaugeIncreaseMultiplier: z.optional(
    z.coerce.number(),
  ),
  assaultBurstDamageTakenBurstGaugeIncreaseMultiplier: z.optional(
    z.coerce.number(),
  ),
  unk380: z.optional(z.coerce.number()),
  unk384: z.optional(z.coerce.number()),
  unk388: z.optional(z.coerce.number()),
  unk392: z.optional(z.coerce.number()),
  unk396: z.optional(z.coerce.number()),
  blastBurstRedLockMelee: z.optional(z.coerce.number()),
  blastBurstRedLock: z.optional(z.coerce.number()),
  blastBurstDamageDealtMultiplier: z.optional(z.coerce.number()),
  blastBurstDamageTakenMultiplier: z.optional(z.coerce.number()),
  blastBurstMobilityMultiplier: z.optional(z.coerce.number()),
  blastBurstDownValueDealtMultiplier: z.optional(z.coerce.number()),
  blastBurstBoostConsumptionMultiplier: z.optional(z.coerce.number()),
  unk428: z.optional(z.coerce.number()),
  unk432: z.optional(z.coerce.number()),
  blastBurstDamageDealtBurstGaugeIncreaseMultiplier: z.optional(
    z.coerce.number(),
  ),
  blastBurstDamageTakenBurstGaugeIncreaseMultiplier: z.optional(
    z.coerce.number(),
  ),
  unk444: z.optional(z.coerce.number()),
  unk448: z.optional(z.coerce.number()),
  unk452: z.optional(z.coerce.number()),
  unk456: z.optional(z.coerce.number()),
  unk460: z.optional(z.coerce.number()),
  thirdBurstRedLockMelee: z.optional(z.coerce.number()),
  thirdBurstRedLock: z.optional(z.coerce.number()),
  thirdBurstDamageDealtMultiplier: z.optional(z.coerce.number()),
  thirdBurstDamageTakenMultiplier: z.optional(z.coerce.number()),
  thirdBurstMobilityMultiplier: z.optional(z.coerce.number()),
  thirdBurstDownValueDealtMultiplier: z.optional(z.coerce.number()),
  thirdBurstBoostConsumptionMultiplier: z.optional(z.coerce.number()),
  unk492: z.optional(z.coerce.number()),
  unk496: z.optional(z.coerce.number()),
  thirdBurstDamageDealtBurstGaugeIncreaseMultiplier: z.optional(
    z.coerce.number(),
  ),
  thirdBurstDamageTakenBurstGaugeIncreaseMultiplier: z.optional(
    z.coerce.number(),
  ),
  unk508: z.optional(z.coerce.number()),
  unk512: z.optional(z.coerce.number()),
  unk516: z.optional(z.coerce.number()),
  unk520: z.optional(z.coerce.number()),
  unk524: z.optional(z.coerce.number()),
  fourthBurstRedLockMelee: z.optional(z.coerce.number()),
  fourthBurstRedLock: z.optional(z.coerce.number()),
  fourthBurstDamageDealtMultiplier: z.optional(z.coerce.number()),
  fourthBurstDamageTakenMultiplier: z.optional(z.coerce.number()),
  fourthBurstMobilityMultiplier: z.optional(z.coerce.number()),
  fourthBurstDownValueDealtMultiplier: z.optional(z.coerce.number()),
  fourthBurstBoostConsumptionMultiplier: z.optional(z.coerce.number()),
  unk572: z.optional(z.coerce.number()),
  unk576: z.optional(z.coerce.number()),
  fourthBurstDamageDealtBurstGaugeIncreaseMultiplier: z.optional(
    z.coerce.number(),
  ),
  fourthBurstDamageTakenBurstGaugeIncreaseMultiplier: z.optional(
    z.coerce.number(),
  ),
  unk588: z.optional(z.coerce.number()),
  unk592: z.optional(z.coerce.number()),
  unk596: z.optional(z.coerce.number()),
  unk600: z.optional(z.coerce.number()),
  unk604: z.optional(z.coerce.number()),
  unk608: z.optional(z.coerce.number()),
  order: z.optional(z.coerce.number()),
  unitId: z.optional(z.union([z.null(), z.coerce.number()])),
});

export const zCreateUnitAmmoSlotCommand = z.object({
  ammoHash: z.coerce.number(),
  unitId: z.coerce.number(),
  slotOrder: z.coerce.number(),
});

export const zCreateUnitCommand = z.object({
  unitId: z.optional(z.coerce.number()),
  slugName: z.optional(z.union([z.null(), z.string()])),
  nameEnglish: z.optional(z.union([z.null(), z.string()])),
  nameJapanese: z.optional(z.union([z.null(), z.string()])),
  nameChinese: z.optional(z.union([z.null(), z.string()])),
  seriesId: z.optional(z.union([z.null(), z.coerce.number()])),
  series: z.optional(zSeriesVm),
});

export const zDebugCommand = z.record(z.string(), z.unknown());

export const zDecompileScexByPathCommand = z.object({
  sourcePath: z.string(),
  destinationPath: z.string(),
  fileName: z.optional(z.union([z.null(), z.string()])),
});

export const zDecompileScexByUnitsCommand = z.object({
  unitIds: z.array(z.coerce.number()),
  replaceScript: z.optional(z.boolean()).default(false),
});

export const zExportAmmoByPathCommand = z.object({
  exportPath: z.optional(z.union([z.null(), z.string()])),
});

export const zExportAmmoCommand = z.object({
  replaceWorking: z.optional(z.boolean()).default(false),
  hotReload: z.optional(z.boolean()).default(false),
});

export const zExportHitboxGroupByPathCommand = z.object({
  hashes: z.optional(z.union([z.null(), z.array(z.coerce.number())])),
  unitIds: z.optional(z.union([z.null(), z.array(z.coerce.number())])),
  outputPath: z.optional(z.union([z.null(), z.string()])),
});

export const zExportHitboxGroupCommand = z.object({
  hashes: z.optional(z.union([z.null(), z.array(z.coerce.number())])),
  unitIds: z.optional(z.union([z.null(), z.array(z.coerce.number())])),
  replaceWorking: z.optional(z.boolean()).default(false),
  hotReload: z.optional(z.boolean()).default(false),
});

export const zExportPlayableCharactersCommand = z.object({
  replaceWorking: z.optional(z.boolean()).default(false),
});

export const zExportPlayableSeriesCommand = z.object({
  replaceWorking: z.optional(z.boolean()).default(false),
});

export const zExportTblCommand = z.object({
  versions: z.optional(z.union([z.null(), z.array(zPatchFileVersion)])),
  replaceStaging: z.optional(z.boolean()).default(false),
});

export const zExportUnitProjectileByPathCommand = z.object({
  unitIds: z.optional(z.union([z.null(), z.array(z.coerce.number())])),
  exportPath: z.optional(z.union([z.null(), z.string()])),
});

export const zExportUnitProjectileCommand = z.object({
  unitIds: z.optional(z.union([z.null(), z.array(z.coerce.number())])),
  replaceWorking: z.optional(z.boolean()).default(false),
  hotReload: z.optional(z.boolean()).default(false),
});

export const zExportUnitStatByPathCommand = z.object({
  unitIds: z.optional(z.union([z.null(), z.array(z.coerce.number())])),
  exportPath: z.optional(z.union([z.null(), z.string()])),
});

export const zExportUnitStatCommand = z.object({
  unitIds: z.optional(z.union([z.null(), z.array(z.coerce.number())])),
  replaceWorking: z.optional(z.boolean()).default(false),
});

export const zFileContentHttpResult = z.string();

export const zGetUnitSummaryQueryIncludes = z.enum(["Series"]);

export const zHitboxDto = z.object({
  hash: z.optional(z.coerce.number()),
  hitboxType: z.optional(z.coerce.number()),
  damage: z.optional(z.coerce.number()),
  unk8: z.optional(z.coerce.number()),
  downValueThreshold: z.optional(z.coerce.number()),
  yorukeValueThreshold: z.optional(z.coerce.number()),
  unk20: z.optional(z.coerce.number()),
  unk24: z.optional(z.coerce.number()),
  damageCorrection: z.optional(z.coerce.number()),
  specialEffect: z.optional(z.coerce.number()),
  hitEffect: z.optional(z.coerce.number()),
  flyDirection1: z.optional(z.coerce.number()),
  flyDirection2: z.optional(z.coerce.number()),
  flyDirection3: z.optional(z.coerce.number()),
  enemyCameraShakeMultiplier: z.optional(z.coerce.number()),
  playerCameraShakeMultiplier: z.optional(z.coerce.number()),
  unk56: z.optional(z.coerce.number()),
  knockUpAngle: z.optional(z.coerce.number()),
  knockUpRange: z.optional(z.coerce.number()),
  unk68: z.optional(z.coerce.number()),
  multipleHitIntervalFrame: z.optional(z.coerce.number()),
  multipleHitCount: z.optional(z.coerce.number()),
  enemyStunDuration: z.optional(z.coerce.number()),
  playerStunDuration: z.optional(z.coerce.number()),
  hitVisualEffect: z.optional(z.coerce.number()),
  hitVisualEffectSizeMultiplier: z.optional(z.coerce.number()),
  hitSoundEffectHash: z.optional(z.coerce.number()),
  unk100: z.optional(z.coerce.number()),
  friendlyDamageFlag: z.optional(z.coerce.number()),
  unk108: z.optional(z.coerce.number()),
  hitboxGroupHash: z.optional(z.coerce.number()),
});

export const zHitboxGroupDto = z.object({
  hash: z.optional(z.coerce.number()),
  unitIds: z.optional(z.array(z.coerce.number())),
  hitboxes: z.optional(z.array(zHitboxDto)),
});

export const zHotReloadScex = z.object({
  sourcePath: z.string(),
});

export const zIFormFile = z.string();

export const zIFormFileCollection = z.array(zIFormFile);

export const zLanguageSettings = z.enum(["English", "Japanese", "Chinese"]);

export const zNullableOfCompressionType = z.enum(["None", "Zlib", "Lzma"]);

export const zPackFhmByAssetCommand = z.object({
  assetFileHashes: z.optional(z.union([z.null(), z.array(z.coerce.number())])),
  assetFileTypes: z.optional(z.union([z.null(), z.array(zAssetFileType)])),
  unitIds: z.optional(z.union([z.null(), z.array(z.coerce.number())])),
  patchFileVersions: z.optional(
    z.union([z.null(), z.array(zPatchFileVersion)]),
  ),
  replaceStaging: z.optional(z.boolean()).default(false),
});

export const zPackPsarcByPatchFilesCommand = z.object({
  patchFileVersions: z.optional(
    z.union([z.null(), z.array(zPatchFileVersion)]),
  ),
});

export const zPackPsarcByPathCommand = z.object({
  sourcePath: z.string(),
  destinationPath: z.string(),
  filename: z.optional(z.union([z.null(), z.string()])),
  compressionType: z.optional(zNullableOfCompressionType),
  compressionLevel: z
    .optional(z.union([z.null(), z.coerce.number().default(9)]))
    .default(9),
});

export const zPaginatedListOfAmmoDto = z.object({
  items: z.array(zAmmoDto),
  pageNumber: z.coerce.number(),
  totalPages: z.optional(z.coerce.number()),
  totalCount: z.coerce.number(),
  hasPreviousPage: z.optional(z.boolean()),
  hasNextPage: z.optional(z.boolean()),
});

export const zPaginatedListOfAssetFileVm = z.object({
  items: z.array(zAssetFileVm),
  pageNumber: z.coerce.number(),
  totalPages: z.optional(z.coerce.number()),
  totalCount: z.coerce.number(),
  hasPreviousPage: z.optional(z.boolean()),
  hasNextPage: z.optional(z.boolean()),
});

export const zPaginatedListOfHitboxDto = z.object({
  items: z.array(zHitboxDto),
  pageNumber: z.coerce.number(),
  totalPages: z.optional(z.coerce.number()),
  totalCount: z.coerce.number(),
  hasPreviousPage: z.optional(z.boolean()),
  hasNextPage: z.optional(z.boolean()),
});

export const zPaginatedListOfHitboxGroupDto = z.object({
  items: z.array(zHitboxGroupDto),
  pageNumber: z.coerce.number(),
  totalPages: z.optional(z.coerce.number()),
  totalCount: z.coerce.number(),
  hasPreviousPage: z.optional(z.boolean()),
  hasNextPage: z.optional(z.boolean()),
});

export const zPatchFileSummaryVm = z.object({
  assetFile: z.optional(zAssetFileDto),
  id: z.union([z.null(), z.string()]),
  tblId: zPatchFileVersion,
  pathInfo: z.optional(zPathInfoDto),
  fileInfo: z.optional(zFileInfoDto),
  assetFileHash: z.optional(z.union([z.null(), z.coerce.number()])),
});

export const zPaginatedListOfPatchFileSummaryVm = z.object({
  items: z.array(zPatchFileSummaryVm),
  pageNumber: z.coerce.number(),
  totalPages: z.optional(z.coerce.number()),
  totalCount: z.coerce.number(),
  hasPreviousPage: z.optional(z.boolean()),
  hasNextPage: z.optional(z.boolean()),
});

export const zPatchFileVm = z.object({
  id: z.union([z.null(), z.string()]),
  tblId: zPatchFileVersion,
  pathInfo: z.optional(zPathInfoDto),
  fileInfo: z.optional(zFileInfoDto),
  assetFileHash: z.optional(z.union([z.null(), z.coerce.number()])),
});

export const zPaginatedListOfPatchFileVm = z.object({
  items: z.array(zPatchFileVm),
  pageNumber: z.coerce.number(),
  totalPages: z.optional(z.coerce.number()),
  totalCount: z.coerce.number(),
  hasPreviousPage: z.optional(z.boolean()),
  hasNextPage: z.optional(z.boolean()),
});

export const zProjectileDto = z.object({
  hash: z.optional(z.coerce.number()),
  projectileType: z.optional(z.coerce.number()),
  hitboxHash: z.optional(z.union([z.null(), z.coerce.number()])),
  modelHash: z.optional(z.coerce.number()),
  skeletonIndex: z.optional(z.coerce.number()),
  aimType: z.optional(z.coerce.number()),
  translateY: z.optional(z.coerce.number()),
  translateZ: z.optional(z.coerce.number()),
  translateX: z.optional(z.coerce.number()),
  rotateX: z.optional(z.coerce.number()),
  rotateZ: z.optional(z.coerce.number()),
  cosmeticHash: z.optional(z.coerce.number()),
  unk44: z.optional(z.coerce.number()),
  unk48: z.optional(z.coerce.number()),
  unk52: z.optional(z.coerce.number()),
  unk56: z.optional(z.coerce.number()),
  ammoConsumption: z.optional(z.coerce.number()),
  durationFrame: z.optional(z.coerce.number()),
  maxTravelDistance: z.optional(z.coerce.number()),
  initialSpeed: z.optional(z.coerce.number()),
  acceleration: z.optional(z.coerce.number()),
  accelerationStartFrame: z.optional(z.coerce.number()),
  unk84: z.optional(z.coerce.number()),
  maxSpeed: z.optional(z.coerce.number()),
  reserved92: z.optional(z.coerce.number()),
  reserved96: z.optional(z.coerce.number()),
  reserved100: z.optional(z.coerce.number()),
  reserved104: z.optional(z.coerce.number()),
  reserved108: z.optional(z.coerce.number()),
  reserved112: z.optional(z.coerce.number()),
  reserved116: z.optional(z.coerce.number()),
  horizontalGuidance: z.optional(z.coerce.number()),
  horizontalGuidanceAngle: z.optional(z.coerce.number()),
  verticalGuidance: z.optional(z.coerce.number()),
  verticalGuidanceAngle: z.optional(z.coerce.number()),
  reserved136: z.optional(z.coerce.number()),
  reserved140: z.optional(z.coerce.number()),
  reserved144: z.optional(z.coerce.number()),
  reserved148: z.optional(z.coerce.number()),
  reserved152: z.optional(z.coerce.number()),
  reserved156: z.optional(z.coerce.number()),
  reserved160: z.optional(z.coerce.number()),
  reserved164: z.optional(z.coerce.number()),
  reserved168: z.optional(z.coerce.number()),
  reserved172: z.optional(z.coerce.number()),
  size: z.optional(z.coerce.number()),
  reserved180: z.optional(z.coerce.number()),
  reserved184: z.optional(z.coerce.number()),
  soundEffectHash: z.optional(z.coerce.number()),
  reserved192: z.optional(z.coerce.number()),
  reserved196: z.optional(z.coerce.number()),
  chainedProjectileHash: z.optional(z.coerce.number()),
  reserved204: z.optional(z.coerce.number()),
  reserved208: z.optional(z.coerce.number()),
  reserved212: z.optional(z.coerce.number()),
  reserved216: z.optional(z.coerce.number()),
  reserved220: z.optional(z.coerce.number()),
  reserved224: z.optional(z.coerce.number()),
  reserved228: z.optional(z.coerce.number()),
  reserved232: z.optional(z.coerce.number()),
  reserved236: z.optional(z.coerce.number()),
  reserved240: z.optional(z.coerce.number()),
  reserved244: z.optional(z.coerce.number()),
  reserved248: z.optional(z.coerce.number()),
  reserved252: z.optional(z.coerce.number()),
  reserved256: z.optional(z.coerce.number()),
  reserved260: z.optional(z.coerce.number()),
  reserved264: z.optional(z.coerce.number()),
  reserved268: z.optional(z.coerce.number()),
  reserved272: z.optional(z.coerce.number()),
  reserved276: z.optional(z.coerce.number()),
  unitId: z.optional(z.union([z.null(), z.coerce.number()])),
});

export const zPaginatedListOfProjectileDto = z.object({
  items: z.array(zProjectileDto),
  pageNumber: z.coerce.number(),
  totalPages: z.optional(z.coerce.number()),
  totalCount: z.coerce.number(),
  hasPreviousPage: z.optional(z.boolean()),
  hasNextPage: z.optional(z.boolean()),
});

export const zSeriesDto = z.object({
  id: z.optional(z.coerce.number()),
  playableSeries: z.optional(zPlayableSeriesDetailsDto),
  slugName: z.optional(z.string()),
  nameEnglish: z.optional(z.union([z.null(), z.string()])),
  nameJapanese: z.optional(z.union([z.null(), z.string()])),
  nameChinese: z.optional(z.union([z.null(), z.string()])),
});

export const zPaginatedListOfSeriesDto = z.object({
  items: z.array(zSeriesDto),
  pageNumber: z.coerce.number(),
  totalPages: z.optional(z.coerce.number()),
  totalCount: z.coerce.number(),
  hasPreviousPage: z.optional(z.boolean()),
  hasNextPage: z.optional(z.boolean()),
});

export const zSeriesUnitsVm = z.object({
  units: z.optional(z.array(zUnitSummaryVm)),
  id: z.optional(z.coerce.number()),
  slugName: z.optional(z.string()),
  nameEnglish: z.optional(z.union([z.null(), z.string()])),
  nameJapanese: z.optional(z.union([z.null(), z.string()])),
  nameChinese: z.optional(z.union([z.null(), z.string()])),
});

export const zPaginatedListOfSeriesUnitsVm = z.object({
  items: z.array(zSeriesUnitsVm),
  pageNumber: z.coerce.number(),
  totalPages: z.optional(z.coerce.number()),
  totalCount: z.coerce.number(),
  hasPreviousPage: z.optional(z.boolean()),
  hasNextPage: z.optional(z.boolean()),
});

export const zStatDto = z.object({
  id: z.optional(z.string()),
  unitCost: z.optional(z.coerce.number()),
  unitCost2: z.optional(z.coerce.number()),
  maxHp: z.optional(z.coerce.number()),
  downValueThreshold: z.optional(z.coerce.number()),
  yorukeValueThreshold: z.optional(z.coerce.number()),
  unk20: z.optional(z.coerce.number()),
  unk24: z.optional(z.coerce.number()),
  unk28: z.optional(z.coerce.number()),
  maxBoost: z.optional(z.coerce.number()),
  unk36: z.optional(z.coerce.number()),
  unk40: z.optional(z.coerce.number()),
  unk44: z.optional(z.coerce.number()),
  gravityMultiplierAir: z.optional(z.coerce.number()),
  gravityMultiplierLand: z.optional(z.coerce.number()),
  unk56: z.optional(z.coerce.number()),
  unk60: z.optional(z.coerce.number()),
  unk64: z.optional(z.coerce.number()),
  unk68: z.optional(z.coerce.number()),
  unk72: z.optional(z.coerce.number()),
  unk76: z.optional(z.coerce.number()),
  unk80: z.optional(z.coerce.number()),
  cameraZoomMultiplier: z.optional(z.coerce.number()),
  unk88: z.optional(z.coerce.number()),
  unk92: z.optional(z.coerce.number()),
  unk96: z.optional(z.coerce.number()),
  unk100: z.optional(z.coerce.number()),
  unk104: z.optional(z.coerce.number()),
  unk108: z.optional(z.coerce.number()),
  sizeMultiplier: z.optional(z.coerce.number()),
  unk116: z.optional(z.coerce.number()),
  unk120: z.optional(z.coerce.number()),
  unk124: z.optional(z.coerce.number()),
  unk128: z.optional(z.coerce.number()),
  unk132: z.optional(z.coerce.number()),
  unk136: z.optional(z.coerce.number()),
  unk140: z.optional(z.coerce.number()),
  unk144: z.optional(z.coerce.number()),
  unk148: z.optional(z.coerce.number()),
  unk152: z.optional(z.coerce.number()),
  unk156: z.optional(z.coerce.number()),
  unk160: z.optional(z.coerce.number()),
  unk164: z.optional(z.coerce.number()),
  unk168: z.optional(z.coerce.number()),
  unk172: z.optional(z.coerce.number()),
  unk176: z.optional(z.coerce.number()),
  unk180: z.optional(z.coerce.number()),
  unk184: z.optional(z.coerce.number()),
  redLockRangeMelee: z.optional(z.coerce.number()),
  redLockRange: z.optional(z.coerce.number()),
  unk196: z.optional(z.coerce.number()),
  unk200: z.optional(z.coerce.number()),
  unk204: z.optional(z.coerce.number()),
  unk208: z.optional(z.coerce.number()),
  boostReplenish: z.optional(z.coerce.number()),
  unk216: z.optional(z.coerce.number()),
  boostInitialConsumption: z.optional(z.coerce.number()),
  boostFuwaInitialConsumption: z.optional(z.coerce.number()),
  boostFlyConsumption: z.optional(z.coerce.number()),
  boostGroundStepInitialConsumption: z.optional(z.coerce.number()),
  boostGroundStepConsumption: z.optional(z.coerce.number()),
  boostAirStepInitialConsumption: z.optional(z.coerce.number()),
  boostAirStepConsumption: z.optional(z.coerce.number()),
  boostBdInitialConsumption: z.optional(z.coerce.number()),
  boostBdConsumption: z.optional(z.coerce.number()),
  unk256: z.optional(z.coerce.number()),
  unk260: z.optional(z.coerce.number()),
  unk264: z.optional(z.coerce.number()),
  unk268: z.optional(z.coerce.number()),
  boostTransformInitialConsumption: z.optional(z.coerce.number()),
  boostTransformConsumption: z.optional(z.coerce.number()),
  boostNonVernierActionConsumption: z.optional(z.coerce.number()),
  boostPostActionConsumption: z.optional(z.coerce.number()),
  boostRainbowStepInitialConsumption: z.optional(z.coerce.number()),
  unk292: z.optional(z.coerce.number()),
  unk296: z.optional(z.coerce.number()),
  unk300: z.optional(z.coerce.number()),
  unk304: z.optional(z.coerce.number()),
  unk308: z.optional(z.coerce.number()),
  unk312: z.optional(z.coerce.number()),
  unk316: z.optional(z.coerce.number()),
  unk320: z.optional(z.coerce.number()),
  unk324: z.optional(z.coerce.number()),
  unk328: z.optional(z.coerce.number()),
  unk332: z.optional(z.coerce.number()),
  assaultBurstRedLockMelee: z.optional(z.coerce.number()),
  assaultBurstRedLock: z.optional(z.coerce.number()),
  assaultBurstDamageDealtMultiplier: z.optional(z.coerce.number()),
  assaultBurstDamageTakenMultiplier: z.optional(z.coerce.number()),
  assaultBurstMobilityMultiplier: z.optional(z.coerce.number()),
  assaultBurstDownValueDealtMultiplier: z.optional(z.coerce.number()),
  assaultBurstBoostConsumptionMultiplier: z.optional(z.coerce.number()),
  unk364: z.optional(z.coerce.number()),
  unk368: z.optional(z.coerce.number()),
  assaultBurstDamageDealtBurstGaugeIncreaseMultiplier: z.optional(
    z.coerce.number(),
  ),
  assaultBurstDamageTakenBurstGaugeIncreaseMultiplier: z.optional(
    z.coerce.number(),
  ),
  unk380: z.optional(z.coerce.number()),
  unk384: z.optional(z.coerce.number()),
  unk388: z.optional(z.coerce.number()),
  unk392: z.optional(z.coerce.number()),
  unk396: z.optional(z.coerce.number()),
  blastBurstRedLockMelee: z.optional(z.coerce.number()),
  blastBurstRedLock: z.optional(z.coerce.number()),
  blastBurstDamageDealtMultiplier: z.optional(z.coerce.number()),
  blastBurstDamageTakenMultiplier: z.optional(z.coerce.number()),
  blastBurstMobilityMultiplier: z.optional(z.coerce.number()),
  blastBurstDownValueDealtMultiplier: z.optional(z.coerce.number()),
  blastBurstBoostConsumptionMultiplier: z.optional(z.coerce.number()),
  unk428: z.optional(z.coerce.number()),
  unk432: z.optional(z.coerce.number()),
  blastBurstDamageDealtBurstGaugeIncreaseMultiplier: z.optional(
    z.coerce.number(),
  ),
  blastBurstDamageTakenBurstGaugeIncreaseMultiplier: z.optional(
    z.coerce.number(),
  ),
  unk444: z.optional(z.coerce.number()),
  unk448: z.optional(z.coerce.number()),
  unk452: z.optional(z.coerce.number()),
  unk456: z.optional(z.coerce.number()),
  unk460: z.optional(z.coerce.number()),
  thirdBurstRedLockMelee: z.optional(z.coerce.number()),
  thirdBurstRedLock: z.optional(z.coerce.number()),
  thirdBurstDamageDealtMultiplier: z.optional(z.coerce.number()),
  thirdBurstDamageTakenMultiplier: z.optional(z.coerce.number()),
  thirdBurstMobilityMultiplier: z.optional(z.coerce.number()),
  thirdBurstDownValueDealtMultiplier: z.optional(z.coerce.number()),
  thirdBurstBoostConsumptionMultiplier: z.optional(z.coerce.number()),
  unk492: z.optional(z.coerce.number()),
  unk496: z.optional(z.coerce.number()),
  thirdBurstDamageDealtBurstGaugeIncreaseMultiplier: z.optional(
    z.coerce.number(),
  ),
  thirdBurstDamageTakenBurstGaugeIncreaseMultiplier: z.optional(
    z.coerce.number(),
  ),
  unk508: z.optional(z.coerce.number()),
  unk512: z.optional(z.coerce.number()),
  unk516: z.optional(z.coerce.number()),
  unk520: z.optional(z.coerce.number()),
  unk524: z.optional(z.coerce.number()),
  fourthBurstRedLockMelee: z.optional(z.coerce.number()),
  fourthBurstRedLock: z.optional(z.coerce.number()),
  fourthBurstDamageDealtMultiplier: z.optional(z.coerce.number()),
  fourthBurstDamageTakenMultiplier: z.optional(z.coerce.number()),
  fourthBurstMobilityMultiplier: z.optional(z.coerce.number()),
  fourthBurstDownValueDealtMultiplier: z.optional(z.coerce.number()),
  fourthBurstBoostConsumptionMultiplier: z.optional(z.coerce.number()),
  unk572: z.optional(z.coerce.number()),
  unk576: z.optional(z.coerce.number()),
  fourthBurstDamageDealtBurstGaugeIncreaseMultiplier: z.optional(
    z.coerce.number(),
  ),
  fourthBurstDamageTakenBurstGaugeIncreaseMultiplier: z.optional(
    z.coerce.number(),
  ),
  unk588: z.optional(z.coerce.number()),
  unk592: z.optional(z.coerce.number()),
  unk596: z.optional(z.coerce.number()),
  unk600: z.optional(z.coerce.number()),
  unk604: z.optional(z.coerce.number()),
  unk608: z.optional(z.coerce.number()),
  order: z.optional(z.coerce.number()),
  unitId: z.optional(z.union([z.null(), z.coerce.number()])),
});

export const zPaginatedListOfStatDto = z.object({
  items: z.array(zStatDto),
  pageNumber: z.coerce.number(),
  totalPages: z.optional(z.coerce.number()),
  totalCount: z.coerce.number(),
  hasPreviousPage: z.optional(z.boolean()),
  hasNextPage: z.optional(z.boolean()),
});

export const zUnitProjectileDto = z.object({
  unitId: z.optional(z.coerce.number()),
  projectiles: z.optional(z.array(zProjectileDto)),
});

export const zPaginatedListOfUnitProjectileDto = z.object({
  items: z.array(zUnitProjectileDto),
  pageNumber: z.coerce.number(),
  totalPages: z.optional(z.coerce.number()),
  totalCount: z.coerce.number(),
  hasPreviousPage: z.optional(z.boolean()),
  hasNextPage: z.optional(z.boolean()),
});

export const zUnitAmmoSlotDto = z.object({
  id: z.optional(z.union([z.null(), z.string()])),
  slotOrder: z.optional(z.coerce.number()),
  ammoHash: z.optional(z.coerce.number()),
});

export const zUnitStatDto = z.object({
  id: z.optional(z.union([z.null(), z.string()])),
  unitId: z.optional(z.coerce.number()),
  ammoSlots: z.optional(z.array(zUnitAmmoSlotDto)),
});

export const zPaginatedListOfUnitStatDto = z.object({
  items: z.array(zUnitStatDto),
  pageNumber: z.coerce.number(),
  totalPages: z.optional(z.coerce.number()),
  totalCount: z.coerce.number(),
  hasPreviousPage: z.optional(z.boolean()),
  hasNextPage: z.optional(z.boolean()),
});

export const zPaginatedListOfUnitSummaryVm = z.object({
  items: z.array(zUnitSummaryVm),
  pageNumber: z.coerce.number(),
  totalPages: z.optional(z.coerce.number()),
  totalCount: z.coerce.number(),
  hasPreviousPage: z.optional(z.boolean()),
  hasNextPage: z.optional(z.boolean()),
});

export const zTblFileInfoMetadata = z.union([
  z.null(),
  z.object({
    cumulativeIndex: z.coerce.number(),
    patchNumber: z.coerce.number(),
    size1: z.coerce.number(),
    size2: z.coerce.number(),
    size3: z.coerce.number(),
    size4: z.coerce.number(),
    hashName: z.coerce.number(),
  }),
]);

export const zPatchFileMetadataDto = z.object({
  path: z.optional(z.union([z.null(), z.string()])),
  fileInfoMetadata: z.optional(zTblFileInfoMetadata),
});

export const zPlayableCharacterDto = z.object({
  unitId: z.optional(z.coerce.number()),
  unitIndex: z.optional(z.coerce.number()),
  seriesId: z.optional(z.coerce.number()),
  unk2: z.optional(z.coerce.number()),
  fString: z.optional(z.union([z.null(), z.string()])),
  fOutString: z.optional(z.union([z.null(), z.string()])),
  pString: z.optional(z.union([z.null(), z.string()])),
  unitSelectOrderInSeries: z.optional(z.coerce.number()),
  arcadeSmallSpriteIndex: z.optional(z.coerce.number()),
  arcadeUnitNameSpriteIndex: z.optional(z.coerce.number()),
  unk27: z.optional(z.coerce.number()),
  unk112: z.optional(z.coerce.number()),
  figurineSpriteIndex: z.optional(z.coerce.number()),
  unk114: z.optional(z.coerce.number()),
  unk124: z.optional(z.coerce.number()),
  unk128: z.optional(z.coerce.number()),
  catalogStorePilotCostume2TString: z.optional(z.union([z.null(), z.string()])),
  catalogStorePilotCostume2String: z.optional(z.union([z.null(), z.string()])),
  catalogStorePilotCostume3TString: z.optional(z.union([z.null(), z.string()])),
  catalogStorePilotCostume3String: z.optional(z.union([z.null(), z.string()])),
  unk156: z.optional(z.coerce.number()),
  arcadeSelectionCostume1SpriteAssetHash: z.optional(z.coerce.number()),
  arcadeSelectionCostume2SpriteAssetHash: z.optional(z.coerce.number()),
  arcadeSelectionCostume3SpriteAssetHash: z.optional(z.coerce.number()),
  loadingLeftCostume1SpriteAssetHash: z.optional(z.coerce.number()),
  loadingLeftCostume2SpriteAssetHash: z.optional(z.coerce.number()),
  loadingLeftCostume3SpriteAssetHash: z.optional(z.coerce.number()),
  loadingRightCostume1SpriteAssetHash: z.optional(z.coerce.number()),
  loadingRightCostume2SpriteAssetHash: z.optional(z.coerce.number()),
  loadingRightCostume3SpriteAssetHash: z.optional(z.coerce.number()),
  genericSelectionCostume1SpriteAssetHash: z.optional(z.coerce.number()),
  genericSelectionCostume2SpriteAssetHash: z.optional(z.coerce.number()),
  genericSelectionCostume3SpriteAssetHash: z.optional(z.coerce.number()),
  loadingTargetUnitSpriteAssetHash: z.optional(z.coerce.number()),
  loadingTargetPilotCostume1SpriteAssetHash: z.optional(z.coerce.number()),
  loadingTargetPilotCostume2SpriteAssetHash: z.optional(z.coerce.number()),
  loadingTargetPilotCostume3SpriteAssetHash: z.optional(z.coerce.number()),
  inGameSortieAndAwakeningPilotCostume1SpriteAssetHash: z.optional(
    z.coerce.number(),
  ),
  inGameSortieAndAwakeningPilotCostume2SpriteAssetHash: z.optional(
    z.coerce.number(),
  ),
  inGameSortieAndAwakeningPilotCostume3SpriteAssetHash: z.optional(
    z.coerce.number(),
  ),
  spriteFramesAssetHash: z.optional(z.coerce.number()),
  resultSmallUnitSpriteAssetHash: z.optional(z.coerce.number()),
  figurineSpriteAssetHash: z.optional(z.coerce.number()),
  loadingTargetUnitSmallSpriteAssetHash: z.optional(z.coerce.number()),
  catalogStorePilotCostume2SpriteAssetHash: z.optional(z.coerce.number()),
  catalogStorePilotCostume3SpriteAssetHash: z.optional(z.coerce.number()),
});

export const zResizePatchFileCommand = z.object({
  ids: z.optional(z.union([z.null(), z.array(z.uuid())])),
  versions: z.optional(z.union([z.null(), z.array(zPatchFileVersion)])),
  unitIds: z.optional(z.union([z.null(), z.array(z.coerce.number())])),
  assetFileTypes: z.optional(z.union([z.null(), z.array(zAssetFileType)])),
});

export const zSerializeTblCommand = z.object({
  cumulativeFileInfoCount: z.coerce.number(),
  fileMetadata: z.array(zPatchFileMetadataDto),
  pathOrder: z.optional(z.union([z.null(), z.array(z.string())])),
});

export const zTblDto = z.object({
  cumulativeFileInfoCount: z.coerce.number(),
  fileMetadata: z.array(zPatchFileMetadataDto),
  pathOrder: z.optional(z.union([z.null(), z.array(z.string())])),
});

export const zTblVm = z.object({
  id: z.string(),
  cumulativeAssetIndex: z.optional(z.coerce.number()),
});

export const zUnpackFhmByAssetCommand = z.object({
  assetFileHashes: z.optional(z.union([z.null(), z.array(z.coerce.number())])),
  assetFileTypes: z.optional(z.union([z.null(), z.array(zAssetFileType)])),
  unitIds: z.optional(z.union([z.null(), z.array(z.coerce.number())])),
  patchFileVersions: z.optional(
    z.union([z.null(), z.array(zPatchFileVersion)]),
  ),
  replaceWorking: z.optional(z.boolean()).default(false),
});

export const zUnpackPsarcByPatchFilesCommand = z.object({
  patchFileVersions: z.optional(
    z.union([z.null(), z.array(zPatchFileVersion)]),
  ),
});

export const zUnpackPsarcByPathCommand = z.object({
  sourceFilePath: z.string(),
  outputDirectoryPath: z.string(),
});

export const zUpdateAmmoCommand = z.object({
  hash: z.coerce.number(),
  ammoType: z.optional(z.coerce.number()),
  maxAmmo: z.optional(z.coerce.number()),
  initialAmmo: z.optional(z.coerce.number()),
  timedDurationFrame: z.optional(z.coerce.number()),
  unk16: z.optional(z.coerce.number()),
  reloadType: z.optional(z.coerce.number()),
  cooldownDurationFrame: z.optional(z.coerce.number()),
  reloadDurationFrame: z.optional(z.coerce.number()),
  assaultBurstReloadDurationFrame: z.optional(z.coerce.number()),
  blastBurstReloadDurationFrame: z.optional(z.coerce.number()),
  unk40: z.optional(z.coerce.number()),
  unk44: z.optional(z.coerce.number()),
  inactiveUnk48: z.optional(z.coerce.number()),
  inactiveCooldownDurationFrame: z.optional(z.coerce.number()),
  inactiveReloadDurationFrame: z.optional(z.coerce.number()),
  inactiveAssaultBurstReloadDurationFrame: z.optional(z.coerce.number()),
  inactiveBlastBurstReloadDurationFrame: z.optional(z.coerce.number()),
  inactiveUnk68: z.optional(z.coerce.number()),
  inactiveUnk72: z.optional(z.coerce.number()),
  burstReplenish: z.optional(z.coerce.number()),
  unk80: z.optional(z.coerce.number()),
  unk84: z.optional(z.coerce.number()),
  unk88: z.optional(z.coerce.number()),
  chargeInput: z.optional(z.coerce.number()),
  chargeDurationFrame: z.optional(z.coerce.number()),
  assaultBurstChargeDurationFrame: z.optional(z.coerce.number()),
  blastBurstChargeDurationFrame: z.optional(z.coerce.number()),
  unk108: z.optional(z.coerce.number()),
  unk112: z.optional(z.coerce.number()),
  releaseChargeLingerDurationFrame: z.optional(z.coerce.number()),
  maxChargeLevel: z.optional(z.coerce.number()),
  unk124: z.optional(z.coerce.number()),
  unk128: z.optional(z.coerce.number()),
  order: z.optional(z.coerce.number()),
  unitId: z.optional(z.union([z.null(), z.coerce.number()])),
});

export const zUpdateAssetFileByHashCommand = z.object({
  hash: z.coerce.number(),
  order: z.optional(z.coerce.number()),
  fileType: z.optional(z.array(zAssetFileType)),
  unitIds: z.optional(z.array(z.coerce.number())),
});

export const zUpdateHitboxCommand = z.object({
  hash: z.coerce.number(),
  hitboxType: z.optional(z.coerce.number()),
  damage: z.optional(z.coerce.number()),
  unk8: z.optional(z.coerce.number()),
  downValueThreshold: z.optional(z.coerce.number()),
  yorukeValueThreshold: z.optional(z.coerce.number()),
  unk20: z.optional(z.coerce.number()),
  unk24: z.optional(z.coerce.number()),
  damageCorrection: z.optional(z.coerce.number()),
  specialEffect: z.optional(z.coerce.number()),
  hitEffect: z.optional(z.coerce.number()),
  flyDirection1: z.optional(z.coerce.number()),
  flyDirection2: z.optional(z.coerce.number()),
  flyDirection3: z.optional(z.coerce.number()),
  enemyCameraShakeMultiplier: z.optional(z.coerce.number()),
  playerCameraShakeMultiplier: z.optional(z.coerce.number()),
  unk56: z.optional(z.coerce.number()),
  knockUpAngle: z.optional(z.coerce.number()),
  knockUpRange: z.optional(z.coerce.number()),
  unk68: z.optional(z.coerce.number()),
  multipleHitIntervalFrame: z.optional(z.coerce.number()),
  multipleHitCount: z.optional(z.coerce.number()),
  enemyStunDuration: z.optional(z.coerce.number()),
  playerStunDuration: z.optional(z.coerce.number()),
  hitVisualEffect: z.optional(z.coerce.number()),
  hitVisualEffectSizeMultiplier: z.optional(z.coerce.number()),
  hitSoundEffectHash: z.optional(z.coerce.number()),
  unk100: z.optional(z.coerce.number()),
  friendlyDamageFlag: z.optional(z.coerce.number()),
  unk108: z.optional(z.coerce.number()),
  hitboxGroupHash: z.optional(z.coerce.number()),
});

export const zUpdateHitboxGroupCommand = z.object({
  hash: z.coerce.number(),
  unitIds: z.optional(z.union([z.null(), z.array(z.coerce.number())])),
});

export const zUpdatePatchFileByIdCommand = z.object({
  id: z.uuid(),
  tblId: zPatchFileVersion,
  pathInfo: z.optional(zPathInfoDto),
  fileInfo: z.optional(zFileInfoDto),
  assetFileHash: z.optional(z.union([z.null(), z.coerce.number()])),
});

export const zUpdateProjectileByIdCommand = z.object({
  hash: z.coerce.number(),
  projectileType: z.optional(z.coerce.number()),
  hitboxHash: z.optional(z.union([z.null(), z.coerce.number()])),
  modelHash: z.optional(z.coerce.number()),
  skeletonIndex: z.optional(z.coerce.number()),
  aimType: z.optional(z.coerce.number()),
  translateY: z.optional(z.coerce.number()),
  translateZ: z.optional(z.coerce.number()),
  translateX: z.optional(z.coerce.number()),
  rotateX: z.optional(z.coerce.number()),
  rotateZ: z.optional(z.coerce.number()),
  cosmeticHash: z.optional(z.coerce.number()),
  unk44: z.optional(z.coerce.number()),
  unk48: z.optional(z.coerce.number()),
  unk52: z.optional(z.coerce.number()),
  unk56: z.optional(z.coerce.number()),
  ammoConsumption: z.optional(z.coerce.number()),
  durationFrame: z.optional(z.coerce.number()),
  maxTravelDistance: z.optional(z.coerce.number()),
  initialSpeed: z.optional(z.coerce.number()),
  acceleration: z.optional(z.coerce.number()),
  accelerationStartFrame: z.optional(z.coerce.number()),
  unk84: z.optional(z.coerce.number()),
  maxSpeed: z.optional(z.coerce.number()),
  reserved92: z.optional(z.coerce.number()),
  reserved96: z.optional(z.coerce.number()),
  reserved100: z.optional(z.coerce.number()),
  reserved104: z.optional(z.coerce.number()),
  reserved108: z.optional(z.coerce.number()),
  reserved112: z.optional(z.coerce.number()),
  reserved116: z.optional(z.coerce.number()),
  horizontalGuidance: z.optional(z.coerce.number()),
  horizontalGuidanceAngle: z.optional(z.coerce.number()),
  verticalGuidance: z.optional(z.coerce.number()),
  verticalGuidanceAngle: z.optional(z.coerce.number()),
  reserved136: z.optional(z.coerce.number()),
  reserved140: z.optional(z.coerce.number()),
  reserved144: z.optional(z.coerce.number()),
  reserved148: z.optional(z.coerce.number()),
  reserved152: z.optional(z.coerce.number()),
  reserved156: z.optional(z.coerce.number()),
  reserved160: z.optional(z.coerce.number()),
  reserved164: z.optional(z.coerce.number()),
  reserved168: z.optional(z.coerce.number()),
  reserved172: z.optional(z.coerce.number()),
  size: z.optional(z.coerce.number()),
  reserved180: z.optional(z.coerce.number()),
  reserved184: z.optional(z.coerce.number()),
  soundEffectHash: z.optional(z.coerce.number()),
  reserved192: z.optional(z.coerce.number()),
  reserved196: z.optional(z.coerce.number()),
  chainedProjectileHash: z.optional(z.coerce.number()),
  reserved204: z.optional(z.coerce.number()),
  reserved208: z.optional(z.coerce.number()),
  reserved212: z.optional(z.coerce.number()),
  reserved216: z.optional(z.coerce.number()),
  reserved220: z.optional(z.coerce.number()),
  reserved224: z.optional(z.coerce.number()),
  reserved228: z.optional(z.coerce.number()),
  reserved232: z.optional(z.coerce.number()),
  reserved236: z.optional(z.coerce.number()),
  reserved240: z.optional(z.coerce.number()),
  reserved244: z.optional(z.coerce.number()),
  reserved248: z.optional(z.coerce.number()),
  reserved252: z.optional(z.coerce.number()),
  reserved256: z.optional(z.coerce.number()),
  reserved260: z.optional(z.coerce.number()),
  reserved264: z.optional(z.coerce.number()),
  reserved268: z.optional(z.coerce.number()),
  reserved272: z.optional(z.coerce.number()),
  reserved276: z.optional(z.coerce.number()),
  unitId: z.optional(z.union([z.null(), z.coerce.number()])),
});

export const zUpdateStatCommand = z.object({
  id: z.uuid(),
  unitCost: z.optional(z.coerce.number()),
  unitCost2: z.optional(z.coerce.number()),
  maxHp: z.optional(z.coerce.number()),
  downValueThreshold: z.optional(z.coerce.number()),
  yorukeValueThreshold: z.optional(z.coerce.number()),
  unk20: z.optional(z.coerce.number()),
  unk24: z.optional(z.coerce.number()),
  unk28: z.optional(z.coerce.number()),
  maxBoost: z.optional(z.coerce.number()),
  unk36: z.optional(z.coerce.number()),
  unk40: z.optional(z.coerce.number()),
  unk44: z.optional(z.coerce.number()),
  gravityMultiplierAir: z.optional(z.coerce.number()),
  gravityMultiplierLand: z.optional(z.coerce.number()),
  unk56: z.optional(z.coerce.number()),
  unk60: z.optional(z.coerce.number()),
  unk64: z.optional(z.coerce.number()),
  unk68: z.optional(z.coerce.number()),
  unk72: z.optional(z.coerce.number()),
  unk76: z.optional(z.coerce.number()),
  unk80: z.optional(z.coerce.number()),
  cameraZoomMultiplier: z.optional(z.coerce.number()),
  unk88: z.optional(z.coerce.number()),
  unk92: z.optional(z.coerce.number()),
  unk96: z.optional(z.coerce.number()),
  unk100: z.optional(z.coerce.number()),
  unk104: z.optional(z.coerce.number()),
  unk108: z.optional(z.coerce.number()),
  sizeMultiplier: z.optional(z.coerce.number()),
  unk116: z.optional(z.coerce.number()),
  unk120: z.optional(z.coerce.number()),
  unk124: z.optional(z.coerce.number()),
  unk128: z.optional(z.coerce.number()),
  unk132: z.optional(z.coerce.number()),
  unk136: z.optional(z.coerce.number()),
  unk140: z.optional(z.coerce.number()),
  unk144: z.optional(z.coerce.number()),
  unk148: z.optional(z.coerce.number()),
  unk152: z.optional(z.coerce.number()),
  unk156: z.optional(z.coerce.number()),
  unk160: z.optional(z.coerce.number()),
  unk164: z.optional(z.coerce.number()),
  unk168: z.optional(z.coerce.number()),
  unk172: z.optional(z.coerce.number()),
  unk176: z.optional(z.coerce.number()),
  unk180: z.optional(z.coerce.number()),
  unk184: z.optional(z.coerce.number()),
  redLockRangeMelee: z.optional(z.coerce.number()),
  redLockRange: z.optional(z.coerce.number()),
  unk196: z.optional(z.coerce.number()),
  unk200: z.optional(z.coerce.number()),
  unk204: z.optional(z.coerce.number()),
  unk208: z.optional(z.coerce.number()),
  boostReplenish: z.optional(z.coerce.number()),
  unk216: z.optional(z.coerce.number()),
  boostInitialConsumption: z.optional(z.coerce.number()),
  boostFuwaInitialConsumption: z.optional(z.coerce.number()),
  boostFlyConsumption: z.optional(z.coerce.number()),
  boostGroundStepInitialConsumption: z.optional(z.coerce.number()),
  boostGroundStepConsumption: z.optional(z.coerce.number()),
  boostAirStepInitialConsumption: z.optional(z.coerce.number()),
  boostAirStepConsumption: z.optional(z.coerce.number()),
  boostBdInitialConsumption: z.optional(z.coerce.number()),
  boostBdConsumption: z.optional(z.coerce.number()),
  unk256: z.optional(z.coerce.number()),
  unk260: z.optional(z.coerce.number()),
  unk264: z.optional(z.coerce.number()),
  unk268: z.optional(z.coerce.number()),
  boostTransformInitialConsumption: z.optional(z.coerce.number()),
  boostTransformConsumption: z.optional(z.coerce.number()),
  boostNonVernierActionConsumption: z.optional(z.coerce.number()),
  boostPostActionConsumption: z.optional(z.coerce.number()),
  boostRainbowStepInitialConsumption: z.optional(z.coerce.number()),
  unk292: z.optional(z.coerce.number()),
  unk296: z.optional(z.coerce.number()),
  unk300: z.optional(z.coerce.number()),
  unk304: z.optional(z.coerce.number()),
  unk308: z.optional(z.coerce.number()),
  unk312: z.optional(z.coerce.number()),
  unk316: z.optional(z.coerce.number()),
  unk320: z.optional(z.coerce.number()),
  unk324: z.optional(z.coerce.number()),
  unk328: z.optional(z.coerce.number()),
  unk332: z.optional(z.coerce.number()),
  assaultBurstRedLockMelee: z.optional(z.coerce.number()),
  assaultBurstRedLock: z.optional(z.coerce.number()),
  assaultBurstDamageDealtMultiplier: z.optional(z.coerce.number()),
  assaultBurstDamageTakenMultiplier: z.optional(z.coerce.number()),
  assaultBurstMobilityMultiplier: z.optional(z.coerce.number()),
  assaultBurstDownValueDealtMultiplier: z.optional(z.coerce.number()),
  assaultBurstBoostConsumptionMultiplier: z.optional(z.coerce.number()),
  unk364: z.optional(z.coerce.number()),
  unk368: z.optional(z.coerce.number()),
  assaultBurstDamageDealtBurstGaugeIncreaseMultiplier: z.optional(
    z.coerce.number(),
  ),
  assaultBurstDamageTakenBurstGaugeIncreaseMultiplier: z.optional(
    z.coerce.number(),
  ),
  unk380: z.optional(z.coerce.number()),
  unk384: z.optional(z.coerce.number()),
  unk388: z.optional(z.coerce.number()),
  unk392: z.optional(z.coerce.number()),
  unk396: z.optional(z.coerce.number()),
  blastBurstRedLockMelee: z.optional(z.coerce.number()),
  blastBurstRedLock: z.optional(z.coerce.number()),
  blastBurstDamageDealtMultiplier: z.optional(z.coerce.number()),
  blastBurstDamageTakenMultiplier: z.optional(z.coerce.number()),
  blastBurstMobilityMultiplier: z.optional(z.coerce.number()),
  blastBurstDownValueDealtMultiplier: z.optional(z.coerce.number()),
  blastBurstBoostConsumptionMultiplier: z.optional(z.coerce.number()),
  unk428: z.optional(z.coerce.number()),
  unk432: z.optional(z.coerce.number()),
  blastBurstDamageDealtBurstGaugeIncreaseMultiplier: z.optional(
    z.coerce.number(),
  ),
  blastBurstDamageTakenBurstGaugeIncreaseMultiplier: z.optional(
    z.coerce.number(),
  ),
  unk444: z.optional(z.coerce.number()),
  unk448: z.optional(z.coerce.number()),
  unk452: z.optional(z.coerce.number()),
  unk456: z.optional(z.coerce.number()),
  unk460: z.optional(z.coerce.number()),
  thirdBurstRedLockMelee: z.optional(z.coerce.number()),
  thirdBurstRedLock: z.optional(z.coerce.number()),
  thirdBurstDamageDealtMultiplier: z.optional(z.coerce.number()),
  thirdBurstDamageTakenMultiplier: z.optional(z.coerce.number()),
  thirdBurstMobilityMultiplier: z.optional(z.coerce.number()),
  thirdBurstDownValueDealtMultiplier: z.optional(z.coerce.number()),
  thirdBurstBoostConsumptionMultiplier: z.optional(z.coerce.number()),
  unk492: z.optional(z.coerce.number()),
  unk496: z.optional(z.coerce.number()),
  thirdBurstDamageDealtBurstGaugeIncreaseMultiplier: z.optional(
    z.coerce.number(),
  ),
  thirdBurstDamageTakenBurstGaugeIncreaseMultiplier: z.optional(
    z.coerce.number(),
  ),
  unk508: z.optional(z.coerce.number()),
  unk512: z.optional(z.coerce.number()),
  unk516: z.optional(z.coerce.number()),
  unk520: z.optional(z.coerce.number()),
  unk524: z.optional(z.coerce.number()),
  fourthBurstRedLockMelee: z.optional(z.coerce.number()),
  fourthBurstRedLock: z.optional(z.coerce.number()),
  fourthBurstDamageDealtMultiplier: z.optional(z.coerce.number()),
  fourthBurstDamageTakenMultiplier: z.optional(z.coerce.number()),
  fourthBurstMobilityMultiplier: z.optional(z.coerce.number()),
  fourthBurstDownValueDealtMultiplier: z.optional(z.coerce.number()),
  fourthBurstBoostConsumptionMultiplier: z.optional(z.coerce.number()),
  unk572: z.optional(z.coerce.number()),
  unk576: z.optional(z.coerce.number()),
  fourthBurstDamageDealtBurstGaugeIncreaseMultiplier: z.optional(
    z.coerce.number(),
  ),
  fourthBurstDamageTakenBurstGaugeIncreaseMultiplier: z.optional(
    z.coerce.number(),
  ),
  unk588: z.optional(z.coerce.number()),
  unk592: z.optional(z.coerce.number()),
  unk596: z.optional(z.coerce.number()),
  unk600: z.optional(z.coerce.number()),
  unk604: z.optional(z.coerce.number()),
  unk608: z.optional(z.coerce.number()),
  order: z.optional(z.coerce.number()),
  unitId: z.optional(z.union([z.null(), z.coerce.number()])),
});

export const zUpdateUnitAmmoSlotCommand = z.object({
  id: z.uuid(),
  unitId: z.coerce.number(),
  slotOrder: z.optional(z.union([z.null(), z.coerce.number()])),
  ammoHash: z.optional(z.union([z.null(), z.coerce.number()])),
});

export const zUpdateUnitCommand = z.object({
  unitId: z.optional(z.coerce.number()),
  slugName: z.optional(z.union([z.null(), z.string()])),
  nameEnglish: z.optional(z.union([z.null(), z.string()])),
  nameJapanese: z.optional(z.union([z.null(), z.string()])),
  nameChinese: z.optional(z.union([z.null(), z.string()])),
  seriesId: z.optional(z.union([z.null(), z.coerce.number()])),
  series: z.optional(zSeriesVm),
});

export const zUpsertConfigCommand = z.object({
  key: z.string(),
  value: z.string(),
});

export const zUpsertPlayableCharactersCommand = z.object({
  unitId: z.coerce.number(),
  unitIndex: z.optional(z.coerce.number()),
  seriesId: z.optional(z.coerce.number()),
  unk2: z.optional(z.coerce.number()),
  fString: z.optional(z.union([z.null(), z.string()])),
  fOutString: z.optional(z.union([z.null(), z.string()])),
  pString: z.optional(z.union([z.null(), z.string()])),
  unitSelectOrderInSeries: z.optional(z.coerce.number()),
  arcadeSmallSpriteIndex: z.optional(z.coerce.number()),
  arcadeUnitNameSpriteIndex: z.optional(z.coerce.number()),
  unk27: z.optional(z.coerce.number()),
  unk112: z.optional(z.coerce.number()),
  figurineSpriteIndex: z.optional(z.coerce.number()),
  unk114: z.optional(z.coerce.number()),
  unk124: z.optional(z.coerce.number()),
  unk128: z.optional(z.coerce.number()),
  catalogStorePilotCostume2TString: z.optional(z.union([z.null(), z.string()])),
  catalogStorePilotCostume2String: z.optional(z.union([z.null(), z.string()])),
  catalogStorePilotCostume3TString: z.optional(z.union([z.null(), z.string()])),
  catalogStorePilotCostume3String: z.optional(z.union([z.null(), z.string()])),
  unk156: z.optional(z.coerce.number()),
  arcadeSelectionCostume1SpriteAssetHash: z.optional(z.coerce.number()),
  arcadeSelectionCostume2SpriteAssetHash: z.optional(z.coerce.number()),
  arcadeSelectionCostume3SpriteAssetHash: z.optional(z.coerce.number()),
  loadingLeftCostume1SpriteAssetHash: z.optional(z.coerce.number()),
  loadingLeftCostume2SpriteAssetHash: z.optional(z.coerce.number()),
  loadingLeftCostume3SpriteAssetHash: z.optional(z.coerce.number()),
  loadingRightCostume1SpriteAssetHash: z.optional(z.coerce.number()),
  loadingRightCostume2SpriteAssetHash: z.optional(z.coerce.number()),
  loadingRightCostume3SpriteAssetHash: z.optional(z.coerce.number()),
  genericSelectionCostume1SpriteAssetHash: z.optional(z.coerce.number()),
  genericSelectionCostume2SpriteAssetHash: z.optional(z.coerce.number()),
  genericSelectionCostume3SpriteAssetHash: z.optional(z.coerce.number()),
  loadingTargetUnitSpriteAssetHash: z.optional(z.coerce.number()),
  loadingTargetPilotCostume1SpriteAssetHash: z.optional(z.coerce.number()),
  loadingTargetPilotCostume2SpriteAssetHash: z.optional(z.coerce.number()),
  loadingTargetPilotCostume3SpriteAssetHash: z.optional(z.coerce.number()),
  inGameSortieAndAwakeningPilotCostume1SpriteAssetHash: z.optional(
    z.coerce.number(),
  ),
  inGameSortieAndAwakeningPilotCostume2SpriteAssetHash: z.optional(
    z.coerce.number(),
  ),
  inGameSortieAndAwakeningPilotCostume3SpriteAssetHash: z.optional(
    z.coerce.number(),
  ),
  spriteFramesAssetHash: z.optional(z.coerce.number()),
  resultSmallUnitSpriteAssetHash: z.optional(z.coerce.number()),
  figurineSpriteAssetHash: z.optional(z.coerce.number()),
  loadingTargetUnitSmallSpriteAssetHash: z.optional(z.coerce.number()),
  catalogStorePilotCostume2SpriteAssetHash: z.optional(z.coerce.number()),
  catalogStorePilotCostume3SpriteAssetHash: z.optional(z.coerce.number()),
});

export const zPostApiDebugData = z.object({
  body: zDebugCommand,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zGetApiUnitsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      Page: z.optional(z.coerce.number()).default(1),
      PerPage: z.optional(z.coerce.number()).default(10),
      ListAll: z.optional(z.boolean()).default(false),
      Search: z.optional(z.string()),
      UnitIds: z.optional(z.array(z.coerce.number())),
      Languages: z.optional(z.array(zLanguageSettings)),
      Includes: z.optional(z.array(zGetUnitSummaryQueryIncludes)),
    }),
  ),
});

/**
 * OK
 */
export const zGetApiUnitsResponse = zPaginatedListOfUnitSummaryVm;

export const zPostApiUnitsData = z.object({
  body: zCreateUnitCommand,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zGetApiUnitsByUnitIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    unitId: z.coerce.number(),
  }),
  query: z.optional(z.never()),
});

/**
 * OK
 */
export const zGetApiUnitsByUnitIdResponse = zUnitSummaryVm;

export const zPostApiUnitsByUnitIdData = z.object({
  body: zUpdateUnitCommand,
  path: z.object({
    unitId: z.coerce.number(),
  }),
  query: z.optional(z.never()),
});

/**
 * No Content
 */
export const zPostApiUnitsByUnitIdResponse = z.void();

export const zGetApiUnitsByUnitIdPlayableCharactersData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    unitId: z.coerce.number(),
  }),
  query: z.optional(z.never()),
});

/**
 * OK
 */
export const zGetApiUnitsByUnitIdPlayableCharactersResponse =
  zPlayableCharacterDto;

export const zPostApiUnitsByUnitIdPlayableCharactersData = z.object({
  body: zUpsertPlayableCharactersCommand,
  path: z.object({
    unitId: z.coerce.number(),
  }),
  query: z.optional(z.never()),
});

/**
 * No Content
 */
export const zPostApiUnitsByUnitIdPlayableCharactersResponse = z.void();

export const zPostApiUnitsBulkData = z.object({
  body: zBulkCreateUnitCommand,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zPostApiUnitsPlayableCharactersImportData = z.object({
  body: z.object({
    file: zIFormFile,
  }),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zPostApiUnitsPlayableCharactersExportData = z.object({
  body: zExportPlayableCharactersCommand,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * OK
 */
export const zPostApiUnitsPlayableCharactersExportResponse =
  zFileContentHttpResult;

export const zGetApiPatchFilesData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      Page: z.optional(z.coerce.number()).default(1),
      PerPage: z.optional(z.coerce.number()).default(10),
      Search: z.optional(z.string()),
      Versions: z.optional(z.array(zPatchFileVersion)),
      UnitIds: z.optional(z.array(z.coerce.number())),
    }),
  ),
});

/**
 * OK
 */
export const zGetApiPatchFilesResponse = zPaginatedListOfPatchFileVm;

export const zPostApiPatchFilesData = z.object({
  body: zCreatePatchFileCommand,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zGetApiPatchFilesSummaryData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      Page: z.optional(z.coerce.number()).default(1),
      PerPage: z.optional(z.coerce.number()).default(10),
      Versions: z.optional(z.array(zPatchFileVersion)),
      UnitIds: z.optional(z.array(z.coerce.number())),
      AssetFileHashes: z.optional(z.array(z.coerce.number())),
      AssetFileTypes: z.optional(z.array(zAssetFileType)),
    }),
  ),
});

/**
 * OK
 */
export const zGetApiPatchFilesSummaryResponse =
  zPaginatedListOfPatchFileSummaryVm;

export const zDeleteApiPatchFilesByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * No Content
 */
export const zDeleteApiPatchFilesByIdResponse = z.void();

export const zGetApiPatchFilesByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * OK
 */
export const zGetApiPatchFilesByIdResponse = zPatchFileVm;

export const zPostApiPatchFilesByIdData = z.object({
  body: zUpdatePatchFileByIdCommand,
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * No Content
 */
export const zPostApiPatchFilesByIdResponse = z.void();

export const zPostApiPatchFilesResizeData = z.object({
  body: zResizePatchFileCommand,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * No Content
 */
export const zPostApiPatchFilesResizeResponse = z.void();

export const zGetApiTblDeserializePathData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.object({
    filePath: z.string(),
  }),
});

/**
 * OK
 */
export const zGetApiTblDeserializePathResponse = zTblDto;

export const zPostApiTblDeserializeData = z.object({
  body: z.object({
    file: zIFormFile,
  }),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * OK
 */
export const zPostApiTblDeserializeResponse = zTblDto;

export const zGetApiTblSerializePathData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.object({
    filePath: z.string(),
  }),
});

export const zPostApiTblSerializeData = z.object({
  body: zSerializeTblCommand,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * OK
 */
export const zPostApiTblSerializeResponse = zFileContentHttpResult;

export const zGetApiTblByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: zPatchFileVersion,
  }),
  query: z.optional(z.never()),
});

/**
 * OK
 */
export const zGetApiTblByIdResponse = zTblVm;

export const zPostApiTblImportData = z.object({
  body: z.object({
    files: zIFormFileCollection,
  }),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zPostApiTblExportData = z.object({
  body: zExportTblCommand,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * OK
 */
export const zPostApiTblExportResponse = zFileContentHttpResult;

export const zGetApiStatsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      Page: z.optional(z.coerce.number()).default(1),
      PerPage: z.optional(z.coerce.number()).default(10),
      Ids: z.optional(z.array(z.uuid())),
      UnitIds: z.optional(z.array(z.coerce.number())),
    }),
  ),
});

/**
 * OK
 */
export const zGetApiStatsResponse = zPaginatedListOfStatDto;

export const zPostApiStatsData = z.object({
  body: zCreateStatCommand,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zDeleteApiStatsByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * No Content
 */
export const zDeleteApiStatsByIdResponse = z.void();

export const zGetApiStatsByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * OK
 */
export const zGetApiStatsByIdResponse = zStatDto;

export const zPostApiStatsByIdData = z.object({
  body: zUpdateStatCommand,
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * No Content
 */
export const zPostApiStatsByIdResponse = z.void();

export const zGetApiUnitStatsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      Page: z.optional(z.coerce.number()).default(1),
      PerPage: z.optional(z.coerce.number()).default(10),
      UnitIds: z.optional(z.array(z.coerce.number())),
    }),
  ),
});

/**
 * OK
 */
export const zGetApiUnitStatsResponse = zPaginatedListOfUnitStatDto;

export const zGetApiUnitStatsByUnitIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    unitId: z.coerce.number(),
  }),
  query: z.optional(z.never()),
});

/**
 * OK
 */
export const zGetApiUnitStatsByUnitIdResponse = zUnitStatDto;

export const zPostApiUnitStatsImportData = z.object({
  body: z.object({
    files: zIFormFileCollection,
  }),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zPostApiUnitStatsExportData = z.object({
  body: zExportUnitStatCommand,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * OK
 */
export const zPostApiUnitStatsExportResponse = zFileContentHttpResult;

export const zPostApiUnitStatsExportPathData = z.object({
  body: zExportUnitStatByPathCommand,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * No Content
 */
export const zPostApiUnitStatsExportPathResponse = z.void();

export const zGetApiUnitStatsAmmoSlotByUnitIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    unitId: z.coerce.number(),
  }),
  query: z.optional(z.never()),
});

/**
 * OK
 */
export const zGetApiUnitStatsAmmoSlotByUnitIdResponse =
  z.array(zUnitAmmoSlotDto);

export const zPostApiUnitStatsAmmoSlotData = z.object({
  body: zCreateUnitAmmoSlotCommand,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zDeleteApiUnitStatsAmmoSlotByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * No Content
 */
export const zDeleteApiUnitStatsAmmoSlotByIdResponse = z.void();

export const zPostApiUnitStatsAmmoSlotByIdData = z.object({
  body: zUpdateUnitAmmoSlotCommand,
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * No Content
 */
export const zPostApiUnitStatsAmmoSlotByIdResponse = z.void();

export const zGetApiSeriesData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      Page: z.optional(z.coerce.number()).default(1),
      PerPage: z.optional(z.coerce.number()).default(10),
      Search: z.optional(z.array(z.string())),
      ListAll: z.optional(z.boolean()).default(false),
    }),
  ),
});

/**
 * OK
 */
export const zGetApiSeriesResponse = zPaginatedListOfSeriesDto;

export const zPostApiSeriesData = z.object({
  body: zCreateSeriesCommand,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zGetApiSeriesUnitsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      Page: z.optional(z.coerce.number()).default(1),
      PerPage: z.optional(z.coerce.number()).default(10),
      UnitIds: z.optional(z.array(z.coerce.number())),
      ListAll: z.optional(z.boolean()).default(false),
    }),
  ),
});

/**
 * OK
 */
export const zGetApiSeriesUnitsResponse = zPaginatedListOfSeriesUnitsVm;

export const zPostApiSeriesImportData = z.object({
  body: z.object({
    file: zIFormFile,
  }),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zPostApiSeriesExportData = z.object({
  body: zExportPlayableSeriesCommand,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * OK
 */
export const zPostApiSeriesExportResponse = zFileContentHttpResult;

export const zGetApiScexDecompiledByUnitIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    unitId: z.coerce.number(),
  }),
  query: z.optional(z.never()),
});

/**
 * OK
 */
export const zGetApiScexDecompiledByUnitIdResponse = z.string();

export const zPostApiScexCompilePathData = z.object({
  body: zCompileScexByPathCommand,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * No Content
 */
export const zPostApiScexCompilePathResponse = z.void();

export const zPostApiScexDecompilePathData = z.object({
  body: zDecompileScexByPathCommand,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * No Content
 */
export const zPostApiScexDecompilePathResponse = z.void();

export const zPostApiScexHotReloadPathData = z.object({
  body: zHotReloadScex,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * No Content
 */
export const zPostApiScexHotReloadPathResponse = z.void();

export const zPostApiScexCompileUnitsData = z.object({
  body: zCompileScexByUnitsCommand,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * No Content
 */
export const zPostApiScexCompileUnitsResponse = z.void();

export const zPostApiScexDecompileUnitsData = z.object({
  body: zDecompileScexByUnitsCommand,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * No Content
 */
export const zPostApiScexDecompileUnitsResponse = z.void();

export const zPostApiPsarcPackPathData = z.object({
  body: zPackPsarcByPathCommand,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * No Content
 */
export const zPostApiPsarcPackPathResponse = z.void();

export const zPostApiPsarcUnpackPathData = z.object({
  body: zUnpackPsarcByPathCommand,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * No Content
 */
export const zPostApiPsarcUnpackPathResponse = z.void();

export const zPostApiPsarcPackPatchFilesData = z.object({
  body: zPackPsarcByPatchFilesCommand,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * No Content
 */
export const zPostApiPsarcPackPatchFilesResponse = z.void();

export const zPostApiPsarcUnpackPatchFilesData = z.object({
  body: zUnpackPsarcByPatchFilesCommand,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * No Content
 */
export const zPostApiPsarcUnpackPatchFilesResponse = z.void();

export const zGetApiProjectilesData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      Page: z.optional(z.coerce.number()).default(1),
      PerPage: z.optional(z.coerce.number()).default(10),
      Hashes: z.optional(z.array(z.coerce.number())),
      UnitIds: z.optional(z.array(z.coerce.number())),
      ModelHashes: z.optional(z.array(z.coerce.number())),
      Search: z.optional(z.string()),
    }),
  ),
});

/**
 * OK
 */
export const zGetApiProjectilesResponse = zPaginatedListOfProjectileDto;

export const zPostApiProjectilesData = z.object({
  body: zCreateProjectileCommand,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zDeleteApiProjectilesByHashData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    hash: z.coerce.number(),
  }),
  query: z.optional(z.never()),
});

export const zGetApiProjectilesByHashData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    hash: z.coerce.number(),
  }),
  query: z.optional(z.never()),
});

/**
 * OK
 */
export const zGetApiProjectilesByHashResponse = zProjectileDto;

export const zPostApiProjectilesByHashData = z.object({
  body: zUpdateProjectileByIdCommand,
  path: z.object({
    hash: z.coerce.number(),
  }),
  query: z.optional(z.never()),
});

export const zGetApiUnitProjectilesData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      Page: z.optional(z.coerce.number()).default(1),
      PerPage: z.optional(z.coerce.number()).default(10),
      UnitIds: z.optional(z.array(z.coerce.number())),
      Search: z.optional(z.string()),
    }),
  ),
});

/**
 * OK
 */
export const zGetApiUnitProjectilesResponse = zPaginatedListOfUnitProjectileDto;

export const zGetApiUnitProjectilesByUnitIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    unitId: z.coerce.number(),
  }),
  query: z.optional(z.never()),
});

/**
 * OK
 */
export const zGetApiUnitProjectilesByUnitIdResponse = zUnitProjectileDto;

export const zPostApiUnitProjectilesImportData = z.object({
  body: z.object({
    files: zIFormFileCollection,
  }),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zPostApiUnitProjectilesImportPathData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.object({
    directoryPath: z.string(),
  }),
});

export const zPostApiUnitProjectilesExportData = z.object({
  body: zExportUnitProjectileCommand,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * OK
 */
export const zPostApiUnitProjectilesExportResponse = zFileContentHttpResult;

export const zPostApiUnitProjectilesExportPathData = z.object({
  body: zExportUnitProjectileByPathCommand,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * No Content
 */
export const zPostApiUnitProjectilesExportPathResponse = z.void();

export const zGetApiHitboxesData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      Page: z.optional(z.coerce.number()).default(1),
      PerPage: z.optional(z.coerce.number()).default(10),
      Hashes: z.optional(z.array(z.coerce.number())),
      UnitIds: z.optional(z.array(z.coerce.number())),
      Search: z.optional(z.string()),
    }),
  ),
});

/**
 * OK
 */
export const zGetApiHitboxesResponse = zPaginatedListOfHitboxDto;

export const zPostApiHitboxesData = z.object({
  body: zCreateHitboxCommand,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zDeleteApiHitboxesByHashData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    hash: z.coerce.number(),
  }),
  query: z.optional(z.never()),
});

/**
 * No Content
 */
export const zDeleteApiHitboxesByHashResponse = z.void();

export const zGetApiHitboxesByHashData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    hash: z.coerce.number(),
  }),
  query: z.optional(z.never()),
});

/**
 * OK
 */
export const zGetApiHitboxesByHashResponse = zHitboxDto;

export const zPostApiHitboxesByHashData = z.object({
  body: zUpdateHitboxCommand,
  path: z.object({
    hash: z.coerce.number(),
  }),
  query: z.optional(z.never()),
});

/**
 * No Content
 */
export const zPostApiHitboxesByHashResponse = z.void();

export const zGetApiHitboxGroupsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      Page: z.optional(z.coerce.number()).default(1),
      PerPage: z.optional(z.coerce.number()).default(10),
      Hashes: z.optional(z.array(z.coerce.number())),
      UnitIds: z.optional(z.array(z.coerce.number())),
    }),
  ),
});

/**
 * OK
 */
export const zGetApiHitboxGroupsResponse = zPaginatedListOfHitboxGroupDto;

export const zPostApiHitboxGroupsData = z.object({
  body: zCreateHitboxGroupCommand,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zGetApiHitboxGroupsHashByHashData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    hash: z.coerce.number(),
  }),
  query: z.optional(z.never()),
});

/**
 * OK
 */
export const zGetApiHitboxGroupsHashByHashResponse = zHitboxGroupDto;

export const zGetApiHitboxGroupsUnitIdByUnitIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    unitId: z.coerce.number(),
  }),
  query: z.optional(z.never()),
});

/**
 * OK
 */
export const zGetApiHitboxGroupsUnitIdByUnitIdResponse = zHitboxGroupDto;

export const zPostApiHitboxGroupsByHashData = z.object({
  body: zUpdateHitboxGroupCommand,
  path: z.object({
    hash: z.coerce.number(),
  }),
  query: z.optional(z.never()),
});

/**
 * No Content
 */
export const zPostApiHitboxGroupsByHashResponse = z.void();

export const zPostApiHitboxGroupsImportData = z.object({
  body: z.object({
    file: zIFormFile,
  }),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      unitId: z.optional(z.coerce.number()),
    }),
  ),
});

export const zPostApiHitboxGroupsImportPathData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.object({
    directoryPath: z.string(),
  }),
});

export const zPostApiHitboxGroupsExportData = z.object({
  body: zExportHitboxGroupCommand,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * OK
 */
export const zPostApiHitboxGroupsExportResponse = zFileContentHttpResult;

export const zPostApiHitboxGroupsExportPathData = z.object({
  body: zExportHitboxGroupByPathCommand,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * No Content
 */
export const zPostApiHitboxGroupsExportPathResponse = z.void();

export const zGetApiFhmPackPathData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.object({
    SourcePath: z.string(),
    DestinationPath: z.string(),
    FileName: z.optional(z.string()),
  }),
});

/**
 * No Content
 */
export const zGetApiFhmPackPathResponse = z.void();

export const zGetApiFhmUnpackPathData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.object({
    SourceFilePath: z.string(),
    OutputDirectoryPath: z.string(),
    MultipleFiles: z.optional(z.boolean()).default(false),
  }),
});

/**
 * No Content
 */
export const zGetApiFhmUnpackPathResponse = z.void();

export const zPostApiFhmPackData = z.object({
  body: z.object({
    file: zIFormFile,
  }),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * OK
 */
export const zPostApiFhmPackResponse = zFileContentHttpResult;

export const zPostApiFhmUnpackData = z.object({
  body: z.object({
    file: zIFormFile,
  }),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      compressionFormat: z.optional(zCompressionFormats),
    }),
  ),
});

/**
 * OK
 */
export const zPostApiFhmUnpackResponse = zFileContentHttpResult;

export const zPostApiFhmPackAssetData = z.object({
  body: zPackFhmByAssetCommand,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * No Content
 */
export const zPostApiFhmPackAssetResponse = z.void();

export const zPostApiFhmUnpackAssetData = z.object({
  body: zUnpackFhmByAssetCommand,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * No Content
 */
export const zPostApiFhmUnpackAssetResponse = z.void();

export const zGetApiConfigsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.object({
    Keys: z.array(z.string()),
  }),
});

/**
 * OK
 */
export const zGetApiConfigsResponse = z.array(zConfigDto);

export const zPostApiConfigsData = z.object({
  body: zUpsertConfigCommand,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * No Content
 */
export const zPostApiConfigsResponse = z.void();

export const zDeleteApiConfigsByKeyData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    key: z.string(),
  }),
  query: z.optional(z.never()),
});

/**
 * No Content
 */
export const zDeleteApiConfigsByKeyResponse = z.void();

export const zGetApiConfigsByKeyData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    key: z.string(),
  }),
  query: z.optional(z.never()),
});

/**
 * OK
 */
export const zGetApiConfigsByKeyResponse = z.string();

export const zGetApiAssetsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      Page: z.optional(z.coerce.number()).default(1),
      PerPage: z.optional(z.coerce.number()).default(10),
      UnitIds: z.optional(z.array(z.coerce.number())),
      AssetFileTypes: z.optional(z.array(zAssetFileType)),
      ListAll: z.optional(z.boolean()).default(false),
    }),
  ),
});

/**
 * OK
 */
export const zGetApiAssetsResponse = zPaginatedListOfAssetFileVm;

export const zPostApiAssetsData = z.object({
  body: zCreateAssetFileCommand,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zDeleteApiAssetsByHashData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    hash: z.coerce.number(),
  }),
  query: z.optional(z.never()),
});

/**
 * No Content
 */
export const zDeleteApiAssetsByHashResponse = z.void();

export const zGetApiAssetsByHashData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    hash: z.coerce.number(),
  }),
  query: z.optional(z.never()),
});

/**
 * OK
 */
export const zGetApiAssetsByHashResponse = zAssetFileVm;

export const zPostApiAssetsByHashData = z.object({
  body: zUpdateAssetFileByHashCommand,
  path: z.object({
    hash: z.coerce.number(),
  }),
  query: z.optional(z.never()),
});

/**
 * No Content
 */
export const zPostApiAssetsByHashResponse = z.void();

export const zPostApiAssetsImportData = z.object({
  body: z.object({
    files: zIFormFileCollection,
  }),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zGetApiAmmoData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      Page: z.optional(z.coerce.number()).default(1),
      PerPage: z.optional(z.coerce.number()).default(10),
      Hash: z.optional(z.array(z.coerce.number())),
      UnitIds: z.optional(z.array(z.coerce.number())),
      Search: z.optional(z.string()),
      ListAll: z.optional(z.boolean()).default(false),
    }),
  ),
});

/**
 * OK
 */
export const zGetApiAmmoResponse = zPaginatedListOfAmmoDto;

export const zPostApiAmmoData = z.object({
  body: zCreateAmmoCommand,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zDeleteApiAmmoByHashData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    hash: z.coerce.number(),
  }),
  query: z.optional(z.never()),
});

/**
 * No Content
 */
export const zDeleteApiAmmoByHashResponse = z.void();

export const zGetApiAmmoByHashData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    hash: z.coerce.number(),
  }),
  query: z.optional(z.never()),
});

/**
 * OK
 */
export const zGetApiAmmoByHashResponse = zAmmoDto;

export const zPostApiAmmoByHashData = z.object({
  body: zUpdateAmmoCommand,
  path: z.object({
    hash: z.coerce.number(),
  }),
  query: z.optional(z.never()),
});

/**
 * No Content
 */
export const zPostApiAmmoByHashResponse = z.void();

export const zPostApiAmmoImportData = z.object({
  body: z.object({
    formFile: zIFormFile,
  }),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zPostApiAmmoExportData = z.object({
  body: zExportAmmoCommand,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * OK
 */
export const zPostApiAmmoExportResponse = zFileContentHttpResult;

export const zPostApiAmmoExportPathData = z.object({
  body: zExportAmmoByPathCommand,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * No Content
 */
export const zPostApiAmmoExportPathResponse = z.void();
