name: Build

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.scripts/**'
      - .gitignore
      - CODE_OF_CONDUCT.md
      - LICENSE
      - README.md

  workflow_call:
    inputs:
      build-artifacts:
        type: boolean
        required: true
        default: false

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Checkout code

    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore solution
      run: dotnet restore

    - name: Build solution
      run: dotnet build --no-restore --configuration Release
      
    - name: Test solution
      run: dotnet test --no-build --configuration Release --filter "FullyQualifiedName!~AcceptanceTests"

    - name: Publish website (win-x64)
      if: ${{ inputs.build-artifacts == true }}
      run: |
        dotnet publish --configuration Release --runtime win-x64 --self-contained -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false -p:PublishReadyToRun=true -p:IncludeNativeLibrariesForSelfExtract=true --output ./publish/win-x64
      working-directory: ./src/Core/Presentation/WebApi

    - name: Upload website artifacts (win-x64)
      if: ${{ inputs.build-artifacts == true }}
      uses: actions/upload-artifact@v3
      with:
        name: BoostStudio.Web-win-x64
        path: ./src/Core/Presentation/WebApi/publish/win-x64
        if-no-files-found: error

    - name: Publish website (linux-x64)
      if: ${{ inputs.build-artifacts == true }}
      run: |
        dotnet publish --configuration Release --runtime linux-x64 --self-contained -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false -p:PublishReadyToRun=true -p:IncludeNativeLibrariesForSelfExtract=true --output ./publish/linux-x64
      working-directory: ./src/Core/Presentation/WebApi

    - name: Upload website artifacts (linux-x64)
      if: ${{ inputs.build-artifacts == true }}
      uses: actions/upload-artifact@v3
      with:
        name: BoostStudio.Web-linux-x64
        path: ./src/Core/Presentation/WebApi/publish/linux-x64
        if-no-files-found: error
        
    - name: Publish console (win-x64)
      if: ${{ inputs.build-artifacts == true }}
      run: |
        dotnet publish --configuration Release --runtime win-x64 --self-contained -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false -p:PublishReadyToRun=true -p:IncludeNativeLibrariesForSelfExtract=true --output ./publish/win-x64
      working-directory: ./src/Core/Presentation/Console

    - name: Upload console artifacts (win-x64)
      if: ${{ inputs.build-artifacts == true }}
      uses: actions/upload-artifact@v3
      with:
        name: BoostStudio.Console-win-x64
        path: ./src/Core/Presentation/Console/publish/win-x64
        if-no-files-found: error
        
    - name: Publish console (linux-x64)
      if: ${{ inputs.build-artifacts == true }}
      run: |
        dotnet publish --configuration Release --runtime linux-x64 --self-contained -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false -p:PublishReadyToRun=true -p:IncludeNativeLibrariesForSelfExtract=true --output ./publish/linux-x64
      working-directory: ./src/Core/Presentation/Console

    - name: Upload console artifacts (linux-x64)
      if: ${{ inputs.build-artifacts == true }}
      uses: actions/upload-artifact@v3
      with:
        name: BoostStudio.Console-linux-x64
        path: ./src/Core/Presentation/Console/publish/linux-x64
        if-no-files-found: error

